RestClients:
  #Orchestrator API
  UI Path RPA (UiPath.WebApi 13.0):
    UUID: c700c640-4f76-4cbe-8724-dbc663d8bc0a
    Url: http://{ivy.engine.host}:{ivy.engine.http.port}/{ivy.request.application}/api/rpaMock
    Icon: res:/webContent/icons/uipath.png
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    - com.axonivy.connector.uipath.OAuth2Feature
    - com.axonivy.connector.uipath.TenantHeaderFeature
    - ch.ivyteam.ivy.rest.client.security.CsrfHeaderFeature
    Properties:
      AUTH.tenant: AXONTESTERS
      AUTH.clientId: '007'
      jersey.config.client.followRedirects: 'false'
      JSON.Serialization.PROPERTY_INCLUSION: NON_NULL
      JSON.Mapper.ACCEPT_CASE_INSENSITIVE_PROPERTIES: 'true'
      AUTH.userKey: ${decrypt:\u00F7\u0043\u0087\u0034\u00B6\u000C\u00F8\u00FF\u00C9\u0000\u002B\u0006\u0056\u0071\u006B\u0090\u0059\u00DD\u0049\u0060\u0094\u0036\u008E\u00DE\u003D\u0067\u009F\u006D\u009E\u00DE\u0031\u00D0}
      AUTH.baseUri: http://{ivy.engine.host}:{ivy.engine.http.port}/{ivy.request.application}/api/rpaMock
    OpenAPI:
      SpecUrl: https://cloud.uipath.com/AXONPRESALES/AXONPRESALES/swagger/v13.0/swagger.json
      Namespace: com.uipath.orchestrator
