/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.uipath.orchestrator.ErrorInfo;

/**
 * AjaxResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class AjaxResponse {
  @JsonProperty("result")
  private Object result = null;

  @JsonProperty("targetUrl")
  private String targetUrl = null;

  @JsonProperty("success")
  private Boolean success = null;

  @JsonProperty("error")
  private ErrorInfo error = null;

  @JsonProperty("unAuthorizedRequest")
  private Boolean unAuthorizedRequest = null;

  @JsonProperty("__abp")
  private Boolean _abp = null;

  public AjaxResponse result(Object result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  public Object getResult() {
    return result;
  }

  public void setResult(Object result) {
    this.result = result;
  }

  public AjaxResponse targetUrl(String targetUrl) {
    this.targetUrl = targetUrl;
    return this;
  }

   /**
   * Get targetUrl
   * @return targetUrl
  **/
  public String getTargetUrl() {
    return targetUrl;
  }

  public void setTargetUrl(String targetUrl) {
    this.targetUrl = targetUrl;
  }

  public AjaxResponse success(Boolean success) {
    this.success = success;
    return this;
  }

   /**
   * Get success
   * @return success
  **/
  public Boolean isSuccess() {
    return success;
  }

  public void setSuccess(Boolean success) {
    this.success = success;
  }

  public AjaxResponse error(ErrorInfo error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  public ErrorInfo getError() {
    return error;
  }

  public void setError(ErrorInfo error) {
    this.error = error;
  }

  public AjaxResponse unAuthorizedRequest(Boolean unAuthorizedRequest) {
    this.unAuthorizedRequest = unAuthorizedRequest;
    return this;
  }

   /**
   * Get unAuthorizedRequest
   * @return unAuthorizedRequest
  **/
  public Boolean isUnAuthorizedRequest() {
    return unAuthorizedRequest;
  }

  public void setUnAuthorizedRequest(Boolean unAuthorizedRequest) {
    this.unAuthorizedRequest = unAuthorizedRequest;
  }

   /**
   * Get _abp
   * @return _abp
  **/
  public Boolean isAbp() {
    return _abp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AjaxResponse ajaxResponse = (AjaxResponse) o;
    return Objects.equals(this.result, ajaxResponse.result) &&
        Objects.equals(this.targetUrl, ajaxResponse.targetUrl) &&
        Objects.equals(this.success, ajaxResponse.success) &&
        Objects.equals(this.error, ajaxResponse.error) &&
        Objects.equals(this.unAuthorizedRequest, ajaxResponse.unAuthorizedRequest) &&
        Objects.equals(this._abp, ajaxResponse._abp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(result, targetUrl, success, error, unAuthorizedRequest, _abp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AjaxResponse {\n");
    
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    targetUrl: ").append(toIndentedString(targetUrl)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    unAuthorizedRequest: ").append(toIndentedString(unAuthorizedRequest)).append("\n");
    sb.append("    _abp: ").append(toIndentedString(_abp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
