/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.uipath.orchestrator.ActionableMessageMetaData;
import com.uipath.orchestrator.TagDto;

import java.util.ArrayList;
import java.util.List;
/**
 * Class with only attributes needed for Creating Task (TaskType &#x3D; TaskType.AppTask)
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class AppTasksCreateRequest {
  @JsonProperty("taskDefinitionId")
  private Long taskDefinitionId = null;

  @JsonProperty("taskDefinitionVersion")
  private Integer taskDefinitionVersion = null;

  @JsonProperty("appId")
  private String appId = null;

  @JsonProperty("appVersion")
  private Integer appVersion = null;

  @JsonProperty("isActionableMessageEnabled")
  private Boolean isActionableMessageEnabled = null;

  @JsonProperty("actionableMessageMetaData")
  private ActionableMessageMetaData actionableMessageMetaData = null;

  /**
   * Gets or sets type of this task, allowed type is &#x27;ExternalTask&#x27;.
   */
  public enum TypeEnum {
    FORMTASK("FormTask"),
    EXTERNALTASK("ExternalTask"),
    DOCUMENTVALIDATIONTASK("DocumentValidationTask"),
    DOCUMENTCLASSIFICATIONTASK("DocumentClassificationTask"),
    DATALABELINGTASK("DataLabelingTask"),
    APPTASK("AppTask");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  @JsonProperty("title")
  private String title = null;

  /**
   * Gets or sets priority of this task.
   */
  public enum PriorityEnum {
    LOW("Low"),
    MEDIUM("Medium"),
    HIGH("High"),
    CRITICAL("Critical");

    private String value;

    PriorityEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PriorityEnum fromValue(String input) {
      for (PriorityEnum b : PriorityEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("priority")
  private PriorityEnum priority = null;

  @JsonProperty("data")
  private Object data = null;

  @JsonProperty("taskCatalogName")
  private String taskCatalogName = null;

  @JsonProperty("externalTag")
  private String externalTag = null;

  @JsonProperty("tags")
  private List<TagDto> tags = null;

  @JsonProperty("parentOperationId")
  private String parentOperationId = null;

  public AppTasksCreateRequest taskDefinitionId(Long taskDefinitionId) {
    this.taskDefinitionId = taskDefinitionId;
    return this;
  }

   /**
   * Id for associated task definition
   * @return taskDefinitionId
  **/
  public Long getTaskDefinitionId() {
    return taskDefinitionId;
  }

  public void setTaskDefinitionId(Long taskDefinitionId) {
    this.taskDefinitionId = taskDefinitionId;
  }

  public AppTasksCreateRequest taskDefinitionVersion(Integer taskDefinitionVersion) {
    this.taskDefinitionVersion = taskDefinitionVersion;
    return this;
  }

   /**
   * Version of Task Definition to get associated properties
   * @return taskDefinitionVersion
  **/
  public Integer getTaskDefinitionVersion() {
    return taskDefinitionVersion;
  }

  public void setTaskDefinitionVersion(Integer taskDefinitionVersion) {
    this.taskDefinitionVersion = taskDefinitionVersion;
  }

  public AppTasksCreateRequest appId(String appId) {
    this.appId = appId;
    return this;
  }

   /**
   * Id representing AppId for AppTask
   * @return appId
  **/
  public String getAppId() {
    return appId;
  }

  public void setAppId(String appId) {
    this.appId = appId;
  }

  public AppTasksCreateRequest appVersion(Integer appVersion) {
    this.appVersion = appVersion;
    return this;
  }

   /**
   * Version of App for AppTask
   * @return appVersion
  **/
  public Integer getAppVersion() {
    return appVersion;
  }

  public void setAppVersion(Integer appVersion) {
    this.appVersion = appVersion;
  }

  public AppTasksCreateRequest isActionableMessageEnabled(Boolean isActionableMessageEnabled) {
    this.isActionableMessageEnabled = isActionableMessageEnabled;
    return this;
  }

   /**
   * Is Acionable Message enabled
   * @return isActionableMessageEnabled
  **/
  public Boolean isIsActionableMessageEnabled() {
    return isActionableMessageEnabled;
  }

  public void setIsActionableMessageEnabled(Boolean isActionableMessageEnabled) {
    this.isActionableMessageEnabled = isActionableMessageEnabled;
  }

  public AppTasksCreateRequest actionableMessageMetaData(ActionableMessageMetaData actionableMessageMetaData) {
    this.actionableMessageMetaData = actionableMessageMetaData;
    return this;
  }

   /**
   * Get actionableMessageMetaData
   * @return actionableMessageMetaData
  **/
  public ActionableMessageMetaData getActionableMessageMetaData() {
    return actionableMessageMetaData;
  }

  public void setActionableMessageMetaData(ActionableMessageMetaData actionableMessageMetaData) {
    this.actionableMessageMetaData = actionableMessageMetaData;
  }

  public AppTasksCreateRequest type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Gets or sets type of this task, allowed type is &#x27;ExternalTask&#x27;.
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public AppTasksCreateRequest title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Gets or sets title of this task.
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public AppTasksCreateRequest priority(PriorityEnum priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Gets or sets priority of this task.
   * @return priority
  **/
  public PriorityEnum getPriority() {
    return priority;
  }

  public void setPriority(PriorityEnum priority) {
    this.priority = priority;
  }

  public AppTasksCreateRequest data(Object data) {
    this.data = data;
    return this;
  }

   /**
   * Task data
   * @return data
  **/
  public Object getData() {
    return data;
  }

  public void setData(Object data) {
    this.data = data;
  }

  public AppTasksCreateRequest taskCatalogName(String taskCatalogName) {
    this.taskCatalogName = taskCatalogName;
    return this;
  }

   /**
   * Gets or sets the task catalog/category of the task
   * @return taskCatalogName
  **/
  public String getTaskCatalogName() {
    return taskCatalogName;
  }

  public void setTaskCatalogName(String taskCatalogName) {
    this.taskCatalogName = taskCatalogName;
  }

  public AppTasksCreateRequest externalTag(String externalTag) {
    this.externalTag = externalTag;
    return this;
  }

   /**
   * Reference or name of external system
   * @return externalTag
  **/
  public String getExternalTag() {
    return externalTag;
  }

  public void setExternalTag(String externalTag) {
    this.externalTag = externalTag;
  }

  public AppTasksCreateRequest tags(List<TagDto> tags) {
    this.tags = tags;
    return this;
  }

  public AppTasksCreateRequest addTagsItem(TagDto tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * List of tags associated to the task.
   * @return tags
  **/
  public List<TagDto> getTags() {
    return tags;
  }

  public void setTags(List<TagDto> tags) {
    this.tags = tags;
  }

  public AppTasksCreateRequest parentOperationId(String parentOperationId) {
    this.parentOperationId = parentOperationId;
    return this;
  }

   /**
   * Operation id which created the task.
   * @return parentOperationId
  **/
  public String getParentOperationId() {
    return parentOperationId;
  }

  public void setParentOperationId(String parentOperationId) {
    this.parentOperationId = parentOperationId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppTasksCreateRequest appTasksCreateRequest = (AppTasksCreateRequest) o;
    return Objects.equals(this.taskDefinitionId, appTasksCreateRequest.taskDefinitionId) &&
        Objects.equals(this.taskDefinitionVersion, appTasksCreateRequest.taskDefinitionVersion) &&
        Objects.equals(this.appId, appTasksCreateRequest.appId) &&
        Objects.equals(this.appVersion, appTasksCreateRequest.appVersion) &&
        Objects.equals(this.isActionableMessageEnabled, appTasksCreateRequest.isActionableMessageEnabled) &&
        Objects.equals(this.actionableMessageMetaData, appTasksCreateRequest.actionableMessageMetaData) &&
        Objects.equals(this.type, appTasksCreateRequest.type) &&
        Objects.equals(this.title, appTasksCreateRequest.title) &&
        Objects.equals(this.priority, appTasksCreateRequest.priority) &&
        Objects.equals(this.data, appTasksCreateRequest.data) &&
        Objects.equals(this.taskCatalogName, appTasksCreateRequest.taskCatalogName) &&
        Objects.equals(this.externalTag, appTasksCreateRequest.externalTag) &&
        Objects.equals(this.tags, appTasksCreateRequest.tags) &&
        Objects.equals(this.parentOperationId, appTasksCreateRequest.parentOperationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taskDefinitionId, taskDefinitionVersion, appId, appVersion, isActionableMessageEnabled, actionableMessageMetaData, type, title, priority, data, taskCatalogName, externalTag, tags, parentOperationId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppTasksCreateRequest {\n");
    
    sb.append("    taskDefinitionId: ").append(toIndentedString(taskDefinitionId)).append("\n");
    sb.append("    taskDefinitionVersion: ").append(toIndentedString(taskDefinitionVersion)).append("\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    appVersion: ").append(toIndentedString(appVersion)).append("\n");
    sb.append("    isActionableMessageEnabled: ").append(toIndentedString(isActionableMessageEnabled)).append("\n");
    sb.append("    actionableMessageMetaData: ").append(toIndentedString(actionableMessageMetaData)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    taskCatalogName: ").append(toIndentedString(taskCatalogName)).append("\n");
    sb.append("    externalTag: ").append(toIndentedString(externalTag)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    parentOperationId: ").append(toIndentedString(parentOperationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
