/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.uipath.orchestrator.RobotAssetDto;

/**
 * AssetsSetRobotAssetsByKeyRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class AssetsSetRobotAssetsByKeyRequest {
  @JsonProperty("robotKey")
  private String robotKey = null;

  @JsonProperty("robotAsset")
  private RobotAssetDto robotAsset = null;

  public AssetsSetRobotAssetsByKeyRequest robotKey(String robotKey) {
    this.robotKey = robotKey;
    return this;
  }

   /**
   * Get robotKey
   * @return robotKey
  **/
  public String getRobotKey() {
    return robotKey;
  }

  public void setRobotKey(String robotKey) {
    this.robotKey = robotKey;
  }

  public AssetsSetRobotAssetsByKeyRequest robotAsset(RobotAssetDto robotAsset) {
    this.robotAsset = robotAsset;
    return this;
  }

   /**
   * Get robotAsset
   * @return robotAsset
  **/
  public RobotAssetDto getRobotAsset() {
    return robotAsset;
  }

  public void setRobotAsset(RobotAssetDto robotAsset) {
    this.robotAsset = robotAsset;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssetsSetRobotAssetsByKeyRequest assetsSetRobotAssetsByKeyRequest = (AssetsSetRobotAssetsByKeyRequest) o;
    return Objects.equals(this.robotKey, assetsSetRobotAssetsByKeyRequest.robotKey) &&
        Objects.equals(this.robotAsset, assetsSetRobotAssetsByKeyRequest.robotAsset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(robotKey, robotAsset);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssetsSetRobotAssetsByKeyRequest {\n");
    
    sb.append("    robotKey: ").append(toIndentedString(robotKey)).append("\n");
    sb.append("    robotAsset: ").append(toIndentedString(robotAsset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
