/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AssetsGetRobotByNameAndKeyRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class AssetsGetRobotByNameAndKeyRequest {
  @JsonProperty("robotKey")
  private String robotKey = null;

  @JsonProperty("assetName")
  private String assetName = null;

  @JsonProperty("supportsCredentialsProxyDisconnected")
  private Boolean supportsCredentialsProxyDisconnected = null;

  public AssetsGetRobotByNameAndKeyRequest robotKey(String robotKey) {
    this.robotKey = robotKey;
    return this;
  }

   /**
   * Get robotKey
   * @return robotKey
  **/
  public String getRobotKey() {
    return robotKey;
  }

  public void setRobotKey(String robotKey) {
    this.robotKey = robotKey;
  }

  public AssetsGetRobotByNameAndKeyRequest assetName(String assetName) {
    this.assetName = assetName;
    return this;
  }

   /**
   * Get assetName
   * @return assetName
  **/
  public String getAssetName() {
    return assetName;
  }

  public void setAssetName(String assetName) {
    this.assetName = assetName;
  }

  public AssetsGetRobotByNameAndKeyRequest supportsCredentialsProxyDisconnected(Boolean supportsCredentialsProxyDisconnected) {
    this.supportsCredentialsProxyDisconnected = supportsCredentialsProxyDisconnected;
    return this;
  }

   /**
   * Get supportsCredentialsProxyDisconnected
   * @return supportsCredentialsProxyDisconnected
  **/
  public Boolean isSupportsCredentialsProxyDisconnected() {
    return supportsCredentialsProxyDisconnected;
  }

  public void setSupportsCredentialsProxyDisconnected(Boolean supportsCredentialsProxyDisconnected) {
    this.supportsCredentialsProxyDisconnected = supportsCredentialsProxyDisconnected;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssetsGetRobotByNameAndKeyRequest assetsGetRobotByNameAndKeyRequest = (AssetsGetRobotByNameAndKeyRequest) o;
    return Objects.equals(this.robotKey, assetsGetRobotByNameAndKeyRequest.robotKey) &&
        Objects.equals(this.assetName, assetsGetRobotByNameAndKeyRequest.assetName) &&
        Objects.equals(this.supportsCredentialsProxyDisconnected, assetsGetRobotByNameAndKeyRequest.supportsCredentialsProxyDisconnected);
  }

  @Override
  public int hashCode() {
    return Objects.hash(robotKey, assetName, supportsCredentialsProxyDisconnected);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssetsGetRobotByNameAndKeyRequest {\n");
    
    sb.append("    robotKey: ").append(toIndentedString(robotKey)).append("\n");
    sb.append("    assetName: ").append(toIndentedString(assetName)).append("\n");
    sb.append("    supportsCredentialsProxyDisconnected: ").append(toIndentedString(supportsCredentialsProxyDisconnected)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
