/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.uipath.orchestrator.ResponseDictionaryDto;

/**
 * BlobFileAccessDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class BlobFileAccessDto {
  @JsonProperty("Uri")
  private String uri = null;

  @JsonProperty("Verb")
  private String verb = null;

  @JsonProperty("RequiresAuth")
  private Boolean requiresAuth = null;

  @JsonProperty("Headers")
  private ResponseDictionaryDto headers = null;

  public BlobFileAccessDto uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Get uri
   * @return uri
  **/
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public BlobFileAccessDto verb(String verb) {
    this.verb = verb;
    return this;
  }

   /**
   * Get verb
   * @return verb
  **/
  public String getVerb() {
    return verb;
  }

  public void setVerb(String verb) {
    this.verb = verb;
  }

  public BlobFileAccessDto requiresAuth(Boolean requiresAuth) {
    this.requiresAuth = requiresAuth;
    return this;
  }

   /**
   * Get requiresAuth
   * @return requiresAuth
  **/
  public Boolean isRequiresAuth() {
    return requiresAuth;
  }

  public void setRequiresAuth(Boolean requiresAuth) {
    this.requiresAuth = requiresAuth;
  }

  public BlobFileAccessDto headers(ResponseDictionaryDto headers) {
    this.headers = headers;
    return this;
  }

   /**
   * Get headers
   * @return headers
  **/
  public ResponseDictionaryDto getHeaders() {
    return headers;
  }

  public void setHeaders(ResponseDictionaryDto headers) {
    this.headers = headers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlobFileAccessDto blobFileAccessDto = (BlobFileAccessDto) o;
    return Objects.equals(this.uri, blobFileAccessDto.uri) &&
        Objects.equals(this.verb, blobFileAccessDto.verb) &&
        Objects.equals(this.requiresAuth, blobFileAccessDto.requiresAuth) &&
        Objects.equals(this.headers, blobFileAccessDto.headers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uri, verb, requiresAuth, headers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlobFileAccessDto {\n");
    
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    verb: ").append(toIndentedString(verb)).append("\n");
    sb.append("    requiresAuth: ").append(toIndentedString(requiresAuth)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
