/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.uipath.orchestrator.TagDto;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
/**
 * BucketUpdatedEvent
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class BucketUpdatedEvent {
  @JsonProperty("key")
  private UUID key = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("storageProvider")
  private String storageProvider = null;

  @JsonProperty("storageParameters")
  private String storageParameters = null;

  @JsonProperty("storageContainer")
  private String storageContainer = null;

  /**
   * Gets or Sets options
   */
  public enum OptionsEnum {
    NONE("None"),
    READONLY("ReadOnly"),
    AUDITREADACCESS("AuditReadAccess"),
    ACCESSDATATHROUGHORCHESTRATOR("AccessDataThroughOrchestrator");

    private String value;

    OptionsEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static OptionsEnum fromValue(String input) {
      for (OptionsEnum b : OptionsEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("options")
  private OptionsEnum options = null;

  @JsonProperty("externalName")
  private String externalName = null;

  @JsonProperty("tags")
  private List<TagDto> tags = null;

  @JsonProperty("folderKeys")
  private List<UUID> folderKeys = null;

  @JsonProperty("eventTime")
  private OffsetDateTime eventTime = null;

  @JsonProperty("eventSource")
  private Object eventSource = null;

   /**
   * Get key
   * @return key
  **/
  public UUID getKey() {
    return key;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

   /**
   * Get storageProvider
   * @return storageProvider
  **/
  public String getStorageProvider() {
    return storageProvider;
  }

   /**
   * Get storageParameters
   * @return storageParameters
  **/
  public String getStorageParameters() {
    return storageParameters;
  }

   /**
   * Get storageContainer
   * @return storageContainer
  **/
  public String getStorageContainer() {
    return storageContainer;
  }

   /**
   * Get options
   * @return options
  **/
  public OptionsEnum getOptions() {
    return options;
  }

   /**
   * Get externalName
   * @return externalName
  **/
  public String getExternalName() {
    return externalName;
  }

   /**
   * Get tags
   * @return tags
  **/
  public List<TagDto> getTags() {
    return tags;
  }

  public BucketUpdatedEvent folderKeys(List<UUID> folderKeys) {
    this.folderKeys = folderKeys;
    return this;
  }

  public BucketUpdatedEvent addFolderKeysItem(UUID folderKeysItem) {
    if (this.folderKeys == null) {
      this.folderKeys = new ArrayList<>();
    }
    this.folderKeys.add(folderKeysItem);
    return this;
  }

   /**
   * Get folderKeys
   * @return folderKeys
  **/
  public List<UUID> getFolderKeys() {
    return folderKeys;
  }

  public void setFolderKeys(List<UUID> folderKeys) {
    this.folderKeys = folderKeys;
  }

  public BucketUpdatedEvent eventTime(OffsetDateTime eventTime) {
    this.eventTime = eventTime;
    return this;
  }

   /**
   * Get eventTime
   * @return eventTime
  **/
  public OffsetDateTime getEventTime() {
    return eventTime;
  }

  public void setEventTime(OffsetDateTime eventTime) {
    this.eventTime = eventTime;
  }

  public BucketUpdatedEvent eventSource(Object eventSource) {
    this.eventSource = eventSource;
    return this;
  }

   /**
   * Get eventSource
   * @return eventSource
  **/
  public Object getEventSource() {
    return eventSource;
  }

  public void setEventSource(Object eventSource) {
    this.eventSource = eventSource;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BucketUpdatedEvent bucketUpdatedEvent = (BucketUpdatedEvent) o;
    return Objects.equals(this.key, bucketUpdatedEvent.key) &&
        Objects.equals(this.name, bucketUpdatedEvent.name) &&
        Objects.equals(this.description, bucketUpdatedEvent.description) &&
        Objects.equals(this.storageProvider, bucketUpdatedEvent.storageProvider) &&
        Objects.equals(this.storageParameters, bucketUpdatedEvent.storageParameters) &&
        Objects.equals(this.storageContainer, bucketUpdatedEvent.storageContainer) &&
        Objects.equals(this.options, bucketUpdatedEvent.options) &&
        Objects.equals(this.externalName, bucketUpdatedEvent.externalName) &&
        Objects.equals(this.tags, bucketUpdatedEvent.tags) &&
        Objects.equals(this.folderKeys, bucketUpdatedEvent.folderKeys) &&
        Objects.equals(this.eventTime, bucketUpdatedEvent.eventTime) &&
        Objects.equals(this.eventSource, bucketUpdatedEvent.eventSource);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, name, description, storageProvider, storageParameters, storageContainer, options, externalName, tags, folderKeys, eventTime, eventSource);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BucketUpdatedEvent {\n");
    
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    storageProvider: ").append(toIndentedString(storageProvider)).append("\n");
    sb.append("    storageParameters: ").append(toIndentedString(storageParameters)).append("\n");
    sb.append("    storageContainer: ").append(toIndentedString(storageContainer)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    externalName: ").append(toIndentedString(externalName)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    folderKeys: ").append(toIndentedString(folderKeys)).append("\n");
    sb.append("    eventTime: ").append(toIndentedString(eventTime)).append("\n");
    sb.append("    eventSource: ").append(toIndentedString(eventSource)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
