/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * BulkTasksCompletionRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class BulkTasksCompletionRequest {
  @JsonProperty("action")
  private String action = null;

  @JsonProperty("taskIds")
  private List<Long> taskIds = new ArrayList<>();

  @JsonProperty("data")
  private Object data = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("taskCatalogId")
  private Long taskCatalogId = null;

  @JsonProperty("unsetTaskCatalog")
  private Boolean unsetTaskCatalog = null;

  /**
   * Priority of tasks
   */
  public enum PriorityEnum {
    LOW("Low"),
    MEDIUM("Medium"),
    HIGH("High"),
    CRITICAL("Critical");

    private String value;

    PriorityEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PriorityEnum fromValue(String input) {
      for (PriorityEnum b : PriorityEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("priority")
  private PriorityEnum priority = null;

  @JsonProperty("noteText")
  private String noteText = null;

  public BulkTasksCompletionRequest action(String action) {
    this.action = action;
    return this;
  }

   /**
   * Action taken on this task
   * @return action
  **/
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public BulkTasksCompletionRequest taskIds(List<Long> taskIds) {
    this.taskIds = taskIds;
    return this;
  }

  public BulkTasksCompletionRequest addTaskIdsItem(Long taskIdsItem) {
    this.taskIds.add(taskIdsItem);
    return this;
  }

   /**
   * List of Task Ids which have to be Bulk edited
   * @return taskIds
  **/
  public List<Long> getTaskIds() {
    return taskIds;
  }

  public void setTaskIds(List<Long> taskIds) {
    this.taskIds = taskIds;
  }

  public BulkTasksCompletionRequest data(Object data) {
    this.data = data;
    return this;
  }

   /**
   * Task data json
   * @return data
  **/
  public Object getData() {
    return data;
  }

  public void setData(Object data) {
    this.data = data;
  }

  public BulkTasksCompletionRequest title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Title of tasks
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public BulkTasksCompletionRequest taskCatalogId(Long taskCatalogId) {
    this.taskCatalogId = taskCatalogId;
    return this;
  }

   /**
   * Action Catalog to be associated with the tasks
   * @return taskCatalogId
  **/
  public Long getTaskCatalogId() {
    return taskCatalogId;
  }

  public void setTaskCatalogId(Long taskCatalogId) {
    this.taskCatalogId = taskCatalogId;
  }

  public BulkTasksCompletionRequest unsetTaskCatalog(Boolean unsetTaskCatalog) {
    this.unsetTaskCatalog = unsetTaskCatalog;
    return this;
  }

   /**
   * Unset/Unassociate action catalogs with the tasks  Set to true for unassociating catalog
   * @return unsetTaskCatalog
  **/
  public Boolean isUnsetTaskCatalog() {
    return unsetTaskCatalog;
  }

  public void setUnsetTaskCatalog(Boolean unsetTaskCatalog) {
    this.unsetTaskCatalog = unsetTaskCatalog;
  }

  public BulkTasksCompletionRequest priority(PriorityEnum priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Priority of tasks
   * @return priority
  **/
  public PriorityEnum getPriority() {
    return priority;
  }

  public void setPriority(PriorityEnum priority) {
    this.priority = priority;
  }

  public BulkTasksCompletionRequest noteText(String noteText) {
    this.noteText = noteText;
    return this;
  }

   /**
   * Comment to be added while doing the bulk operation
   * @return noteText
  **/
  public String getNoteText() {
    return noteText;
  }

  public void setNoteText(String noteText) {
    this.noteText = noteText;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkTasksCompletionRequest bulkTasksCompletionRequest = (BulkTasksCompletionRequest) o;
    return Objects.equals(this.action, bulkTasksCompletionRequest.action) &&
        Objects.equals(this.taskIds, bulkTasksCompletionRequest.taskIds) &&
        Objects.equals(this.data, bulkTasksCompletionRequest.data) &&
        Objects.equals(this.title, bulkTasksCompletionRequest.title) &&
        Objects.equals(this.taskCatalogId, bulkTasksCompletionRequest.taskCatalogId) &&
        Objects.equals(this.unsetTaskCatalog, bulkTasksCompletionRequest.unsetTaskCatalog) &&
        Objects.equals(this.priority, bulkTasksCompletionRequest.priority) &&
        Objects.equals(this.noteText, bulkTasksCompletionRequest.noteText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, taskIds, data, title, taskCatalogId, unsetTaskCatalog, priority, noteText);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkTasksCompletionRequest {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    taskIds: ").append(toIndentedString(taskIds)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    taskCatalogId: ").append(toIndentedString(taskCatalogId)).append("\n");
    sb.append("    unsetTaskCatalog: ").append(toIndentedString(unsetTaskCatalog)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    noteText: ").append(toIndentedString(noteText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
