/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
/**
 * CalendarDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class CalendarDto {
  @JsonProperty("TimeZoneId")
  private String timeZoneId = null;

  @JsonProperty("ExcludedDates")
  private List<OffsetDateTime> excludedDates = null;

  public CalendarDto timeZoneId(String timeZoneId) {
    this.timeZoneId = timeZoneId;
    return this;
  }

   /**
   * Get timeZoneId
   * @return timeZoneId
  **/
  public String getTimeZoneId() {
    return timeZoneId;
  }

  public void setTimeZoneId(String timeZoneId) {
    this.timeZoneId = timeZoneId;
  }

  public CalendarDto excludedDates(List<OffsetDateTime> excludedDates) {
    this.excludedDates = excludedDates;
    return this;
  }

  public CalendarDto addExcludedDatesItem(OffsetDateTime excludedDatesItem) {
    if (this.excludedDates == null) {
      this.excludedDates = new ArrayList<>();
    }
    this.excludedDates.add(excludedDatesItem);
    return this;
  }

   /**
   * Get excludedDates
   * @return excludedDates
  **/
  public List<OffsetDateTime> getExcludedDates() {
    return excludedDates;
  }

  public void setExcludedDates(List<OffsetDateTime> excludedDates) {
    this.excludedDates = excludedDates;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CalendarDto calendarDto = (CalendarDto) o;
    return Objects.equals(this.timeZoneId, calendarDto.timeZoneId) &&
        Objects.equals(this.excludedDates, calendarDto.excludedDates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeZoneId, excludedDates);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CalendarDto {\n");
    
    sb.append("    timeZoneId: ").append(toIndentedString(timeZoneId)).append("\n");
    sb.append("    excludedDates: ").append(toIndentedString(excludedDates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
