/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * DeleteInactiveSessionsParameters
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class DeleteInactiveSessionsParameters {
  @JsonProperty("sessionIds")
  private List<Long> sessionIds = null;

  public DeleteInactiveSessionsParameters sessionIds(List<Long> sessionIds) {
    this.sessionIds = sessionIds;
    return this;
  }

  public DeleteInactiveSessionsParameters addSessionIdsItem(Long sessionIdsItem) {
    if (this.sessionIds == null) {
      this.sessionIds = new ArrayList<>();
    }
    this.sessionIds.add(sessionIdsItem);
    return this;
  }

   /**
   * Get sessionIds
   * @return sessionIds
  **/
  public List<Long> getSessionIds() {
    return sessionIds;
  }

  public void setSessionIds(List<Long> sessionIds) {
    this.sessionIds = sessionIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteInactiveSessionsParameters deleteInactiveSessionsParameters = (DeleteInactiveSessionsParameters) o;
    return Objects.equals(this.sessionIds, deleteInactiveSessionsParameters.sessionIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessionIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteInactiveSessionsParameters {\n");
    
    sb.append("    sessionIds: ").append(toIndentedString(sessionIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
