/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
import java.util.UUID;
/**
 * DeploymentSettingUpdatedEventDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class DeploymentSettingUpdatedEventDto {
  @JsonProperty("Type")
  private String type = null;

  @JsonProperty("EventId")
  private String eventId = null;

  @JsonProperty("EntityKey")
  private UUID entityKey = null;

  @JsonProperty("Timestamp")
  private OffsetDateTime timestamp = null;

  @JsonProperty("TenantKey")
  private String tenantKey = null;

  @JsonProperty("AccountKey")
  private String accountKey = null;

  @JsonProperty("EventTime")
  private OffsetDateTime eventTime = null;

  @JsonProperty("EventSourceId")
  private Long eventSourceId = null;

  @JsonProperty("TenantId")
  private Integer tenantId = null;

  @JsonProperty("OrganizationUnitId")
  private Long organizationUnitId = null;

  @JsonProperty("OrganizationUnitKey")
  private UUID organizationUnitKey = null;

  @JsonProperty("UserId")
  private Long userId = null;

  public DeploymentSettingUpdatedEventDto type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public DeploymentSettingUpdatedEventDto eventId(String eventId) {
    this.eventId = eventId;
    return this;
  }

   /**
   * Get eventId
   * @return eventId
  **/
  public String getEventId() {
    return eventId;
  }

  public void setEventId(String eventId) {
    this.eventId = eventId;
  }

  public DeploymentSettingUpdatedEventDto entityKey(UUID entityKey) {
    this.entityKey = entityKey;
    return this;
  }

   /**
   * Get entityKey
   * @return entityKey
  **/
  public UUID getEntityKey() {
    return entityKey;
  }

  public void setEntityKey(UUID entityKey) {
    this.entityKey = entityKey;
  }

  public DeploymentSettingUpdatedEventDto timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }

  public DeploymentSettingUpdatedEventDto tenantKey(String tenantKey) {
    this.tenantKey = tenantKey;
    return this;
  }

   /**
   * Get tenantKey
   * @return tenantKey
  **/
  public String getTenantKey() {
    return tenantKey;
  }

  public void setTenantKey(String tenantKey) {
    this.tenantKey = tenantKey;
  }

  public DeploymentSettingUpdatedEventDto accountKey(String accountKey) {
    this.accountKey = accountKey;
    return this;
  }

   /**
   * Get accountKey
   * @return accountKey
  **/
  public String getAccountKey() {
    return accountKey;
  }

  public void setAccountKey(String accountKey) {
    this.accountKey = accountKey;
  }

  public DeploymentSettingUpdatedEventDto eventTime(OffsetDateTime eventTime) {
    this.eventTime = eventTime;
    return this;
  }

   /**
   * Get eventTime
   * @return eventTime
  **/
  public OffsetDateTime getEventTime() {
    return eventTime;
  }

  public void setEventTime(OffsetDateTime eventTime) {
    this.eventTime = eventTime;
  }

   /**
   * Get eventSourceId
   * @return eventSourceId
  **/
  public Long getEventSourceId() {
    return eventSourceId;
  }

  public DeploymentSettingUpdatedEventDto tenantId(Integer tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Get tenantId
   * @return tenantId
  **/
  public Integer getTenantId() {
    return tenantId;
  }

  public void setTenantId(Integer tenantId) {
    this.tenantId = tenantId;
  }

  public DeploymentSettingUpdatedEventDto organizationUnitId(Long organizationUnitId) {
    this.organizationUnitId = organizationUnitId;
    return this;
  }

   /**
   * Get organizationUnitId
   * @return organizationUnitId
  **/
  public Long getOrganizationUnitId() {
    return organizationUnitId;
  }

  public void setOrganizationUnitId(Long organizationUnitId) {
    this.organizationUnitId = organizationUnitId;
  }

  public DeploymentSettingUpdatedEventDto organizationUnitKey(UUID organizationUnitKey) {
    this.organizationUnitKey = organizationUnitKey;
    return this;
  }

   /**
   * Get organizationUnitKey
   * @return organizationUnitKey
  **/
  public UUID getOrganizationUnitKey() {
    return organizationUnitKey;
  }

  public void setOrganizationUnitKey(UUID organizationUnitKey) {
    this.organizationUnitKey = organizationUnitKey;
  }

  public DeploymentSettingUpdatedEventDto userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeploymentSettingUpdatedEventDto deploymentSettingUpdatedEventDto = (DeploymentSettingUpdatedEventDto) o;
    return Objects.equals(this.type, deploymentSettingUpdatedEventDto.type) &&
        Objects.equals(this.eventId, deploymentSettingUpdatedEventDto.eventId) &&
        Objects.equals(this.entityKey, deploymentSettingUpdatedEventDto.entityKey) &&
        Objects.equals(this.timestamp, deploymentSettingUpdatedEventDto.timestamp) &&
        Objects.equals(this.tenantKey, deploymentSettingUpdatedEventDto.tenantKey) &&
        Objects.equals(this.accountKey, deploymentSettingUpdatedEventDto.accountKey) &&
        Objects.equals(this.eventTime, deploymentSettingUpdatedEventDto.eventTime) &&
        Objects.equals(this.eventSourceId, deploymentSettingUpdatedEventDto.eventSourceId) &&
        Objects.equals(this.tenantId, deploymentSettingUpdatedEventDto.tenantId) &&
        Objects.equals(this.organizationUnitId, deploymentSettingUpdatedEventDto.organizationUnitId) &&
        Objects.equals(this.organizationUnitKey, deploymentSettingUpdatedEventDto.organizationUnitKey) &&
        Objects.equals(this.userId, deploymentSettingUpdatedEventDto.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, eventId, entityKey, timestamp, tenantKey, accountKey, eventTime, eventSourceId, tenantId, organizationUnitId, organizationUnitKey, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeploymentSettingUpdatedEventDto {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    entityKey: ").append(toIndentedString(entityKey)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    tenantKey: ").append(toIndentedString(tenantKey)).append("\n");
    sb.append("    accountKey: ").append(toIndentedString(accountKey)).append("\n");
    sb.append("    eventTime: ").append(toIndentedString(eventTime)).append("\n");
    sb.append("    eventSourceId: ").append(toIndentedString(eventSourceId)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    organizationUnitId: ").append(toIndentedString(organizationUnitId)).append("\n");
    sb.append("    organizationUnitKey: ").append(toIndentedString(organizationUnitKey)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
