/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.uipath.orchestrator.ExecutionSettingDefinition;

import java.util.ArrayList;
import java.util.List;
/**
 * ExecutionSettingsConfiguration
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class ExecutionSettingsConfiguration {
  /**
   * Gets or Sets scope
   */
  public enum ScopeEnum {
    GLOBAL("Global"),
    ROBOT("Robot");

    private String value;

    ScopeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ScopeEnum fromValue(String input) {
      for (ScopeEnum b : ScopeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("Scope")
  private ScopeEnum scope = null;

  @JsonProperty("Configuration")
  private List<ExecutionSettingDefinition> _configuration = null;

  public ExecutionSettingsConfiguration scope(ScopeEnum scope) {
    this.scope = scope;
    return this;
  }

   /**
   * Get scope
   * @return scope
  **/
  public ScopeEnum getScope() {
    return scope;
  }

  public void setScope(ScopeEnum scope) {
    this.scope = scope;
  }

  public ExecutionSettingsConfiguration _configuration(List<ExecutionSettingDefinition> _configuration) {
    this._configuration = _configuration;
    return this;
  }

  public ExecutionSettingsConfiguration addConfigurationItem(ExecutionSettingDefinition _configurationItem) {
    if (this._configuration == null) {
      this._configuration = new ArrayList<>();
    }
    this._configuration.add(_configurationItem);
    return this;
  }

   /**
   * Get _configuration
   * @return _configuration
  **/
  public List<ExecutionSettingDefinition> getConfiguration() {
    return _configuration;
  }

  public void setConfiguration(List<ExecutionSettingDefinition> _configuration) {
    this._configuration = _configuration;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExecutionSettingsConfiguration executionSettingsConfiguration = (ExecutionSettingsConfiguration) o;
    return Objects.equals(this.scope, executionSettingsConfiguration.scope) &&
        Objects.equals(this._configuration, executionSettingsConfiguration._configuration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scope, _configuration);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecutionSettingsConfiguration {\n");
    
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
