/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.UUID;
/**
 * ExtendedFolderDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class ExtendedFolderDto {
  @JsonProperty("IsSelectable")
  private Boolean isSelectable = null;

  @JsonProperty("HasChildren")
  private Boolean hasChildren = null;

  @JsonProperty("Level")
  private Integer level = null;

  @JsonProperty("Key")
  private UUID key = null;

  @JsonProperty("DisplayName")
  private String displayName = null;

  @JsonProperty("FullyQualifiedName")
  private String fullyQualifiedName = null;

  @JsonProperty("Description")
  private String description = null;

  /**
   * Folder type
   */
  public enum FolderTypeEnum {
    STANDARD("Standard"),
    PERSONAL("Personal"),
    VIRTUAL("Virtual"),
    SOLUTION("Solution");

    private String value;

    FolderTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static FolderTypeEnum fromValue(String input) {
      for (FolderTypeEnum b : FolderTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("FolderType")
  private FolderTypeEnum folderType = null;

  @JsonProperty("IsPersonal")
  private Boolean isPersonal = null;

  /**
   * Robot provisioning type
   */
  public enum ProvisionTypeEnum {
    MANUAL("Manual"),
    AUTOMATIC("Automatic");

    private String value;

    ProvisionTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ProvisionTypeEnum fromValue(String input) {
      for (ProvisionTypeEnum b : ProvisionTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("ProvisionType")
  private ProvisionTypeEnum provisionType = null;

  /**
   * Folder permissions model
   */
  public enum PermissionModelEnum {
    INHERITFROMTENANT("InheritFromTenant"),
    FINEGRAINED("FineGrained");

    private String value;

    PermissionModelEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PermissionModelEnum fromValue(String input) {
      for (PermissionModelEnum b : PermissionModelEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("PermissionModel")
  private PermissionModelEnum permissionModel = null;

  @JsonProperty("ParentId")
  private Long parentId = null;

  @JsonProperty("ParentKey")
  private UUID parentKey = null;

  /**
   * Folder feed type
   */
  public enum FeedTypeEnum {
    UNDEFINED("Undefined"),
    PROCESSES("Processes"),
    LIBRARIES("Libraries"),
    PERSONALWORKSPACE("PersonalWorkspace"),
    FOLDERHIERARCHY("FolderHierarchy");

    private String value;

    FeedTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static FeedTypeEnum fromValue(String input) {
      for (FeedTypeEnum b : FeedTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("FeedType")
  private FeedTypeEnum feedType = null;

  @JsonProperty("Id")
  private Long id = null;

  public ExtendedFolderDto isSelectable(Boolean isSelectable) {
    this.isSelectable = isSelectable;
    return this;
  }

   /**
   * Determines whether this folder can be selected to view its entities
   * @return isSelectable
  **/
  public Boolean isIsSelectable() {
    return isSelectable;
  }

  public void setIsSelectable(Boolean isSelectable) {
    this.isSelectable = isSelectable;
  }

  public ExtendedFolderDto hasChildren(Boolean hasChildren) {
    this.hasChildren = hasChildren;
    return this;
  }

   /**
   * True if this folder has children
   * @return hasChildren
  **/
  public Boolean isHasChildren() {
    return hasChildren;
  }

  public void setHasChildren(Boolean hasChildren) {
    this.hasChildren = hasChildren;
  }

  public ExtendedFolderDto level(Integer level) {
    this.level = level;
    return this;
  }

   /**
   * Level in the Folders tree.
   * @return level
  **/
  public Integer getLevel() {
    return level;
  }

  public void setLevel(Integer level) {
    this.level = level;
  }

  public ExtendedFolderDto key(UUID key) {
    this.key = key;
    return this;
  }

   /**
   * Unique key for the folder
   * @return key
  **/
  public UUID getKey() {
    return key;
  }

  public void setKey(UUID key) {
    this.key = key;
  }

  public ExtendedFolderDto displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Display name for the folder.
   * @return displayName
  **/
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public ExtendedFolderDto fullyQualifiedName(String fullyQualifiedName) {
    this.fullyQualifiedName = fullyQualifiedName;
    return this;
  }

   /**
   * Name of folder prepended by the names of its ancestors.
   * @return fullyQualifiedName
  **/
  public String getFullyQualifiedName() {
    return fullyQualifiedName;
  }

  public void setFullyQualifiedName(String fullyQualifiedName) {
    this.fullyQualifiedName = fullyQualifiedName;
  }

  public ExtendedFolderDto description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of folder
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ExtendedFolderDto folderType(FolderTypeEnum folderType) {
    this.folderType = folderType;
    return this;
  }

   /**
   * Folder type
   * @return folderType
  **/
  public FolderTypeEnum getFolderType() {
    return folderType;
  }

  public void setFolderType(FolderTypeEnum folderType) {
    this.folderType = folderType;
  }

   /**
   * True if Personal
   * @return isPersonal
  **/
  public Boolean isIsPersonal() {
    return isPersonal;
  }

  public ExtendedFolderDto provisionType(ProvisionTypeEnum provisionType) {
    this.provisionType = provisionType;
    return this;
  }

   /**
   * Robot provisioning type
   * @return provisionType
  **/
  public ProvisionTypeEnum getProvisionType() {
    return provisionType;
  }

  public void setProvisionType(ProvisionTypeEnum provisionType) {
    this.provisionType = provisionType;
  }

  public ExtendedFolderDto permissionModel(PermissionModelEnum permissionModel) {
    this.permissionModel = permissionModel;
    return this;
  }

   /**
   * Folder permissions model
   * @return permissionModel
  **/
  public PermissionModelEnum getPermissionModel() {
    return permissionModel;
  }

  public void setPermissionModel(PermissionModelEnum permissionModel) {
    this.permissionModel = permissionModel;
  }

  public ExtendedFolderDto parentId(Long parentId) {
    this.parentId = parentId;
    return this;
  }

   /**
   * Id of parent folder in the folders hierarchy
   * @return parentId
  **/
  public Long getParentId() {
    return parentId;
  }

  public void setParentId(Long parentId) {
    this.parentId = parentId;
  }

  public ExtendedFolderDto parentKey(UUID parentKey) {
    this.parentKey = parentKey;
    return this;
  }

   /**
   * Unique key for the parent folder
   * @return parentKey
  **/
  public UUID getParentKey() {
    return parentKey;
  }

  public void setParentKey(UUID parentKey) {
    this.parentKey = parentKey;
  }

  public ExtendedFolderDto feedType(FeedTypeEnum feedType) {
    this.feedType = feedType;
    return this;
  }

   /**
   * Folder feed type
   * @return feedType
  **/
  public FeedTypeEnum getFeedType() {
    return feedType;
  }

  public void setFeedType(FeedTypeEnum feedType) {
    this.feedType = feedType;
  }

  public ExtendedFolderDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtendedFolderDto extendedFolderDto = (ExtendedFolderDto) o;
    return Objects.equals(this.isSelectable, extendedFolderDto.isSelectable) &&
        Objects.equals(this.hasChildren, extendedFolderDto.hasChildren) &&
        Objects.equals(this.level, extendedFolderDto.level) &&
        Objects.equals(this.key, extendedFolderDto.key) &&
        Objects.equals(this.displayName, extendedFolderDto.displayName) &&
        Objects.equals(this.fullyQualifiedName, extendedFolderDto.fullyQualifiedName) &&
        Objects.equals(this.description, extendedFolderDto.description) &&
        Objects.equals(this.folderType, extendedFolderDto.folderType) &&
        Objects.equals(this.isPersonal, extendedFolderDto.isPersonal) &&
        Objects.equals(this.provisionType, extendedFolderDto.provisionType) &&
        Objects.equals(this.permissionModel, extendedFolderDto.permissionModel) &&
        Objects.equals(this.parentId, extendedFolderDto.parentId) &&
        Objects.equals(this.parentKey, extendedFolderDto.parentKey) &&
        Objects.equals(this.feedType, extendedFolderDto.feedType) &&
        Objects.equals(this.id, extendedFolderDto.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isSelectable, hasChildren, level, key, displayName, fullyQualifiedName, description, folderType, isPersonal, provisionType, permissionModel, parentId, parentKey, feedType, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtendedFolderDto {\n");
    
    sb.append("    isSelectable: ").append(toIndentedString(isSelectable)).append("\n");
    sb.append("    hasChildren: ").append(toIndentedString(hasChildren)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    fullyQualifiedName: ").append(toIndentedString(fullyQualifiedName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    folderType: ").append(toIndentedString(folderType)).append("\n");
    sb.append("    isPersonal: ").append(toIndentedString(isPersonal)).append("\n");
    sb.append("    provisionType: ").append(toIndentedString(provisionType)).append("\n");
    sb.append("    permissionModel: ").append(toIndentedString(permissionModel)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    parentKey: ").append(toIndentedString(parentKey)).append("\n");
    sb.append("    feedType: ").append(toIndentedString(feedType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
