/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.uipath.orchestrator.WrappedJobDto;
import com.uipath.orchestrator.WrappedStartProcessDto;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
/**
 * This event is raised whenever jobs were created and queued for execution
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class JobsCreatedEventDto {
  @JsonProperty("Type")
  private String type = null;

  @JsonProperty("EventId")
  private String eventId = null;

  @JsonProperty("EntityKey")
  private UUID entityKey = null;

  @JsonProperty("Timestamp")
  private OffsetDateTime timestamp = null;

  @JsonProperty("StartInfo")
  private WrappedStartProcessDto startInfo = null;

  @JsonProperty("Jobs")
  private List<WrappedJobDto> jobs = null;

  @JsonProperty("EventTime")
  private OffsetDateTime eventTime = null;

  @JsonProperty("TenantId")
  private Integer tenantId = null;

  @JsonProperty("OrganizationUnitId")
  private Long organizationUnitId = null;

  @JsonProperty("OrganizationUnitKey")
  private UUID organizationUnitKey = null;

  @JsonProperty("UserId")
  private Long userId = null;

  public JobsCreatedEventDto type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public JobsCreatedEventDto eventId(String eventId) {
    this.eventId = eventId;
    return this;
  }

   /**
   * Get eventId
   * @return eventId
  **/
  public String getEventId() {
    return eventId;
  }

  public void setEventId(String eventId) {
    this.eventId = eventId;
  }

  public JobsCreatedEventDto entityKey(UUID entityKey) {
    this.entityKey = entityKey;
    return this;
  }

   /**
   * Get entityKey
   * @return entityKey
  **/
  public UUID getEntityKey() {
    return entityKey;
  }

  public void setEntityKey(UUID entityKey) {
    this.entityKey = entityKey;
  }

  public JobsCreatedEventDto timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }

  public JobsCreatedEventDto startInfo(WrappedStartProcessDto startInfo) {
    this.startInfo = startInfo;
    return this;
  }

   /**
   * Get startInfo
   * @return startInfo
  **/
  public WrappedStartProcessDto getStartInfo() {
    return startInfo;
  }

  public void setStartInfo(WrappedStartProcessDto startInfo) {
    this.startInfo = startInfo;
  }

   /**
   * List of jobs that were created and are in pending state
   * @return jobs
  **/
  public List<WrappedJobDto> getJobs() {
    return jobs;
  }

  public JobsCreatedEventDto eventTime(OffsetDateTime eventTime) {
    this.eventTime = eventTime;
    return this;
  }

   /**
   * Get eventTime
   * @return eventTime
  **/
  public OffsetDateTime getEventTime() {
    return eventTime;
  }

  public void setEventTime(OffsetDateTime eventTime) {
    this.eventTime = eventTime;
  }

  public JobsCreatedEventDto tenantId(Integer tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Get tenantId
   * @return tenantId
  **/
  public Integer getTenantId() {
    return tenantId;
  }

  public void setTenantId(Integer tenantId) {
    this.tenantId = tenantId;
  }

  public JobsCreatedEventDto organizationUnitId(Long organizationUnitId) {
    this.organizationUnitId = organizationUnitId;
    return this;
  }

   /**
   * Get organizationUnitId
   * @return organizationUnitId
  **/
  public Long getOrganizationUnitId() {
    return organizationUnitId;
  }

  public void setOrganizationUnitId(Long organizationUnitId) {
    this.organizationUnitId = organizationUnitId;
  }

  public JobsCreatedEventDto organizationUnitKey(UUID organizationUnitKey) {
    this.organizationUnitKey = organizationUnitKey;
    return this;
  }

   /**
   * Get organizationUnitKey
   * @return organizationUnitKey
  **/
  public UUID getOrganizationUnitKey() {
    return organizationUnitKey;
  }

  public void setOrganizationUnitKey(UUID organizationUnitKey) {
    this.organizationUnitKey = organizationUnitKey;
  }

  public JobsCreatedEventDto userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobsCreatedEventDto jobsCreatedEventDto = (JobsCreatedEventDto) o;
    return Objects.equals(this.type, jobsCreatedEventDto.type) &&
        Objects.equals(this.eventId, jobsCreatedEventDto.eventId) &&
        Objects.equals(this.entityKey, jobsCreatedEventDto.entityKey) &&
        Objects.equals(this.timestamp, jobsCreatedEventDto.timestamp) &&
        Objects.equals(this.startInfo, jobsCreatedEventDto.startInfo) &&
        Objects.equals(this.jobs, jobsCreatedEventDto.jobs) &&
        Objects.equals(this.eventTime, jobsCreatedEventDto.eventTime) &&
        Objects.equals(this.tenantId, jobsCreatedEventDto.tenantId) &&
        Objects.equals(this.organizationUnitId, jobsCreatedEventDto.organizationUnitId) &&
        Objects.equals(this.organizationUnitKey, jobsCreatedEventDto.organizationUnitKey) &&
        Objects.equals(this.userId, jobsCreatedEventDto.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, eventId, entityKey, timestamp, startInfo, jobs, eventTime, tenantId, organizationUnitId, organizationUnitKey, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobsCreatedEventDto {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    entityKey: ").append(toIndentedString(entityKey)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    startInfo: ").append(toIndentedString(startInfo)).append("\n");
    sb.append("    jobs: ").append(toIndentedString(jobs)).append("\n");
    sb.append("    eventTime: ").append(toIndentedString(eventTime)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    organizationUnitId: ").append(toIndentedString(organizationUnitId)).append("\n");
    sb.append("    organizationUnitKey: ").append(toIndentedString(organizationUnitKey)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
