/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * Stores information about the license used to activate a tenant.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class LicenseDto {
  @JsonProperty("HostLicenseId")
  private Long hostLicenseId = null;

  @JsonProperty("Id")
  private Long id = null;

  @JsonProperty("ExpireDate")
  private Long expireDate = null;

  @JsonProperty("GracePeriodEndDate")
  private Long gracePeriodEndDate = null;

  @JsonProperty("GracePeriod")
  private Long gracePeriod = null;

  @JsonProperty("VersionControl")
  private String versionControl = null;

  @JsonProperty("Allowed")
  private Map<String, Long> allowed = null;

  @JsonProperty("Used")
  private Map<String, Long> used = null;

  @JsonProperty("AttendedConcurrent")
  private Boolean attendedConcurrent = null;

  @JsonProperty("DevelopmentConcurrent")
  private Boolean developmentConcurrent = null;

  @JsonProperty("StudioXConcurrent")
  private Boolean studioXConcurrent = null;

  @JsonProperty("StudioProConcurrent")
  private Boolean studioProConcurrent = null;

  @JsonProperty("LicensedFeatures")
  private List<String> licensedFeatures = null;

  @JsonProperty("IsRegistered")
  private Boolean isRegistered = null;

  @JsonProperty("IsCommunity")
  private Boolean isCommunity = null;

  @JsonProperty("IsProOrEnterprise")
  private Boolean isProOrEnterprise = null;

  @JsonProperty("SubscriptionCode")
  private String subscriptionCode = null;

  @JsonProperty("SubscriptionPlan")
  private String subscriptionPlan = null;

  @JsonProperty("IsExpired")
  private Boolean isExpired = null;

  @JsonProperty("CreationTime")
  private OffsetDateTime creationTime = null;

  @JsonProperty("Code")
  private String code = null;

  @JsonProperty("UserLicensingEnabled")
  private Boolean userLicensingEnabled = null;

  public LicenseDto hostLicenseId(Long hostLicenseId) {
    this.hostLicenseId = hostLicenseId;
    return this;
  }

   /**
   * Get hostLicenseId
   * @return hostLicenseId
  **/
  public Long getHostLicenseId() {
    return hostLicenseId;
  }

  public void setHostLicenseId(Long hostLicenseId) {
    this.hostLicenseId = hostLicenseId;
  }

  public LicenseDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * License Id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public LicenseDto expireDate(Long expireDate) {
    this.expireDate = expireDate;
    return this;
  }

   /**
   * License expiration date in Epoch format
   * @return expireDate
  **/
  public Long getExpireDate() {
    return expireDate;
  }

  public void setExpireDate(Long expireDate) {
    this.expireDate = expireDate;
  }

  public LicenseDto gracePeriodEndDate(Long gracePeriodEndDate) {
    this.gracePeriodEndDate = gracePeriodEndDate;
    return this;
  }

   /**
   * License grace period end date in Epoch format
   * @return gracePeriodEndDate
  **/
  public Long getGracePeriodEndDate() {
    return gracePeriodEndDate;
  }

  public void setGracePeriodEndDate(Long gracePeriodEndDate) {
    this.gracePeriodEndDate = gracePeriodEndDate;
  }

  public LicenseDto gracePeriod(Long gracePeriod) {
    this.gracePeriod = gracePeriod;
    return this;
  }

   /**
   * Number of grace period days
   * @return gracePeriod
  **/
  public Long getGracePeriod() {
    return gracePeriod;
  }

  public void setGracePeriod(Long gracePeriod) {
    this.gracePeriod = gracePeriod;
  }

  public LicenseDto versionControl(String versionControl) {
    this.versionControl = versionControl;
    return this;
  }

   /**
   * The product version which can use this license
   * @return versionControl
  **/
  public String getVersionControl() {
    return versionControl;
  }

  public void setVersionControl(String versionControl) {
    this.versionControl = versionControl;
  }

  public LicenseDto allowed(Map<String, Long> allowed) {
    this.allowed = allowed;
    return this;
  }

  public LicenseDto putAllowedItem(String key, Long allowedItem) {
    if (this.allowed == null) {
      this.allowed = new HashMap<>();
    }
    this.allowed.put(key, allowedItem);
    return this;
  }

   /**
   * Contains the number of allowed licenses for each type
   * @return allowed
  **/
  public Map<String, Long> getAllowed() {
    return allowed;
  }

  public void setAllowed(Map<String, Long> allowed) {
    this.allowed = allowed;
  }

  public LicenseDto used(Map<String, Long> used) {
    this.used = used;
    return this;
  }

  public LicenseDto putUsedItem(String key, Long usedItem) {
    if (this.used == null) {
      this.used = new HashMap<>();
    }
    this.used.put(key, usedItem);
    return this;
  }

   /**
   * Contains the number of used licenses for each type
   * @return used
  **/
  public Map<String, Long> getUsed() {
    return used;
  }

  public void setUsed(Map<String, Long> used) {
    this.used = used;
  }

  public LicenseDto attendedConcurrent(Boolean attendedConcurrent) {
    this.attendedConcurrent = attendedConcurrent;
    return this;
  }

   /**
   * States whether the license is Attended Concurrent
   * @return attendedConcurrent
  **/
  public Boolean isAttendedConcurrent() {
    return attendedConcurrent;
  }

  public void setAttendedConcurrent(Boolean attendedConcurrent) {
    this.attendedConcurrent = attendedConcurrent;
  }

  public LicenseDto developmentConcurrent(Boolean developmentConcurrent) {
    this.developmentConcurrent = developmentConcurrent;
    return this;
  }

   /**
   * States whether the license is Development Concurrent
   * @return developmentConcurrent
  **/
  public Boolean isDevelopmentConcurrent() {
    return developmentConcurrent;
  }

  public void setDevelopmentConcurrent(Boolean developmentConcurrent) {
    this.developmentConcurrent = developmentConcurrent;
  }

  public LicenseDto studioXConcurrent(Boolean studioXConcurrent) {
    this.studioXConcurrent = studioXConcurrent;
    return this;
  }

   /**
   * States whether the license is Studio Business Concurrent
   * @return studioXConcurrent
  **/
  public Boolean isStudioXConcurrent() {
    return studioXConcurrent;
  }

  public void setStudioXConcurrent(Boolean studioXConcurrent) {
    this.studioXConcurrent = studioXConcurrent;
  }

  public LicenseDto studioProConcurrent(Boolean studioProConcurrent) {
    this.studioProConcurrent = studioProConcurrent;
    return this;
  }

   /**
   * States whether the license is Studio Pro Concurrent
   * @return studioProConcurrent
  **/
  public Boolean isStudioProConcurrent() {
    return studioProConcurrent;
  }

  public void setStudioProConcurrent(Boolean studioProConcurrent) {
    this.studioProConcurrent = studioProConcurrent;
  }

  public LicenseDto licensedFeatures(List<String> licensedFeatures) {
    this.licensedFeatures = licensedFeatures;
    return this;
  }

  public LicenseDto addLicensedFeaturesItem(String licensedFeaturesItem) {
    if (this.licensedFeatures == null) {
      this.licensedFeatures = new ArrayList<>();
    }
    this.licensedFeatures.add(licensedFeaturesItem);
    return this;
  }

   /**
   * What features are licensed (valid for individually-licensed features, like Analytics)
   * @return licensedFeatures
  **/
  public List<String> getLicensedFeatures() {
    return licensedFeatures;
  }

  public void setLicensedFeatures(List<String> licensedFeatures) {
    this.licensedFeatures = licensedFeatures;
  }

  public LicenseDto isRegistered(Boolean isRegistered) {
    this.isRegistered = isRegistered;
    return this;
  }

   /**
   * True if the current tenant is registered with a license. False otherwise.
   * @return isRegistered
  **/
  public Boolean isIsRegistered() {
    return isRegistered;
  }

  public void setIsRegistered(Boolean isRegistered) {
    this.isRegistered = isRegistered;
  }

  public LicenseDto isCommunity(Boolean isCommunity) {
    this.isCommunity = isCommunity;
    return this;
  }

   /**
   * True if the current tenant is registered with a community license.
   * @return isCommunity
  **/
  public Boolean isIsCommunity() {
    return isCommunity;
  }

  public void setIsCommunity(Boolean isCommunity) {
    this.isCommunity = isCommunity;
  }

  public LicenseDto isProOrEnterprise(Boolean isProOrEnterprise) {
    this.isProOrEnterprise = isProOrEnterprise;
    return this;
  }

   /**
   * True if the current tenant is registered with a pro license.
   * @return isProOrEnterprise
  **/
  public Boolean isIsProOrEnterprise() {
    return isProOrEnterprise;
  }

  public void setIsProOrEnterprise(Boolean isProOrEnterprise) {
    this.isProOrEnterprise = isProOrEnterprise;
  }

  public LicenseDto subscriptionCode(String subscriptionCode) {
    this.subscriptionCode = subscriptionCode;
    return this;
  }

   /**
   * The license subscription code
   * @return subscriptionCode
  **/
  public String getSubscriptionCode() {
    return subscriptionCode;
  }

  public void setSubscriptionCode(String subscriptionCode) {
    this.subscriptionCode = subscriptionCode;
  }

  public LicenseDto subscriptionPlan(String subscriptionPlan) {
    this.subscriptionPlan = subscriptionPlan;
    return this;
  }

   /**
   * The license subscription plan
   * @return subscriptionPlan
  **/
  public String getSubscriptionPlan() {
    return subscriptionPlan;
  }

  public void setSubscriptionPlan(String subscriptionPlan) {
    this.subscriptionPlan = subscriptionPlan;
  }

  public LicenseDto isExpired(Boolean isExpired) {
    this.isExpired = isExpired;
    return this;
  }

   /**
   * States whether the license is still valid or not.
   * @return isExpired
  **/
  public Boolean isIsExpired() {
    return isExpired;
  }

  public void setIsExpired(Boolean isExpired) {
    this.isExpired = isExpired;
  }

  public LicenseDto creationTime(OffsetDateTime creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * The date when the license was uploaded.
   * @return creationTime
  **/
  public OffsetDateTime getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(OffsetDateTime creationTime) {
    this.creationTime = creationTime;
  }

  public LicenseDto code(String code) {
    this.code = code;
    return this;
  }

   /**
   * The license code.
   * @return code
  **/
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public LicenseDto userLicensingEnabled(Boolean userLicensingEnabled) {
    this.userLicensingEnabled = userLicensingEnabled;
    return this;
  }

   /**
   * Whether user licensing is enabled or not.
   * @return userLicensingEnabled
  **/
  public Boolean isUserLicensingEnabled() {
    return userLicensingEnabled;
  }

  public void setUserLicensingEnabled(Boolean userLicensingEnabled) {
    this.userLicensingEnabled = userLicensingEnabled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LicenseDto licenseDto = (LicenseDto) o;
    return Objects.equals(this.hostLicenseId, licenseDto.hostLicenseId) &&
        Objects.equals(this.id, licenseDto.id) &&
        Objects.equals(this.expireDate, licenseDto.expireDate) &&
        Objects.equals(this.gracePeriodEndDate, licenseDto.gracePeriodEndDate) &&
        Objects.equals(this.gracePeriod, licenseDto.gracePeriod) &&
        Objects.equals(this.versionControl, licenseDto.versionControl) &&
        Objects.equals(this.allowed, licenseDto.allowed) &&
        Objects.equals(this.used, licenseDto.used) &&
        Objects.equals(this.attendedConcurrent, licenseDto.attendedConcurrent) &&
        Objects.equals(this.developmentConcurrent, licenseDto.developmentConcurrent) &&
        Objects.equals(this.studioXConcurrent, licenseDto.studioXConcurrent) &&
        Objects.equals(this.studioProConcurrent, licenseDto.studioProConcurrent) &&
        Objects.equals(this.licensedFeatures, licenseDto.licensedFeatures) &&
        Objects.equals(this.isRegistered, licenseDto.isRegistered) &&
        Objects.equals(this.isCommunity, licenseDto.isCommunity) &&
        Objects.equals(this.isProOrEnterprise, licenseDto.isProOrEnterprise) &&
        Objects.equals(this.subscriptionCode, licenseDto.subscriptionCode) &&
        Objects.equals(this.subscriptionPlan, licenseDto.subscriptionPlan) &&
        Objects.equals(this.isExpired, licenseDto.isExpired) &&
        Objects.equals(this.creationTime, licenseDto.creationTime) &&
        Objects.equals(this.code, licenseDto.code) &&
        Objects.equals(this.userLicensingEnabled, licenseDto.userLicensingEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hostLicenseId, id, expireDate, gracePeriodEndDate, gracePeriod, versionControl, allowed, used, attendedConcurrent, developmentConcurrent, studioXConcurrent, studioProConcurrent, licensedFeatures, isRegistered, isCommunity, isProOrEnterprise, subscriptionCode, subscriptionPlan, isExpired, creationTime, code, userLicensingEnabled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LicenseDto {\n");
    
    sb.append("    hostLicenseId: ").append(toIndentedString(hostLicenseId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    expireDate: ").append(toIndentedString(expireDate)).append("\n");
    sb.append("    gracePeriodEndDate: ").append(toIndentedString(gracePeriodEndDate)).append("\n");
    sb.append("    gracePeriod: ").append(toIndentedString(gracePeriod)).append("\n");
    sb.append("    versionControl: ").append(toIndentedString(versionControl)).append("\n");
    sb.append("    allowed: ").append(toIndentedString(allowed)).append("\n");
    sb.append("    used: ").append(toIndentedString(used)).append("\n");
    sb.append("    attendedConcurrent: ").append(toIndentedString(attendedConcurrent)).append("\n");
    sb.append("    developmentConcurrent: ").append(toIndentedString(developmentConcurrent)).append("\n");
    sb.append("    studioXConcurrent: ").append(toIndentedString(studioXConcurrent)).append("\n");
    sb.append("    studioProConcurrent: ").append(toIndentedString(studioProConcurrent)).append("\n");
    sb.append("    licensedFeatures: ").append(toIndentedString(licensedFeatures)).append("\n");
    sb.append("    isRegistered: ").append(toIndentedString(isRegistered)).append("\n");
    sb.append("    isCommunity: ").append(toIndentedString(isCommunity)).append("\n");
    sb.append("    isProOrEnterprise: ").append(toIndentedString(isProOrEnterprise)).append("\n");
    sb.append("    subscriptionCode: ").append(toIndentedString(subscriptionCode)).append("\n");
    sb.append("    subscriptionPlan: ").append(toIndentedString(subscriptionPlan)).append("\n");
    sb.append("    isExpired: ").append(toIndentedString(isExpired)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    userLicensingEnabled: ").append(toIndentedString(userLicensingEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
