/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
import java.util.UUID;
/**
 * Logs generated by Robots and execution reports. Can be stored in ElasticSearch and/or to a local SQL database.  &lt;para /&gt;Note: The endpoint for this type is /odata/RobotLogs URL.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class LogDto {
  /**
   * Defines the log severity.
   */
  public enum LevelEnum {
    TRACE("Trace"),
    DEBUG("Debug"),
    INFO("Info"),
    WARN("Warn"),
    ERROR("Error"),
    FATAL("Fatal");

    private String value;

    LevelEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static LevelEnum fromValue(String input) {
      for (LevelEnum b : LevelEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("Level")
  private LevelEnum level = null;

  @JsonProperty("WindowsIdentity")
  private String windowsIdentity = null;

  @JsonProperty("ProcessName")
  private String processName = null;

  @JsonProperty("TimeStamp")
  private OffsetDateTime timeStamp = null;

  @JsonProperty("Message")
  private String message = null;

  @JsonProperty("JobKey")
  private UUID jobKey = null;

  @JsonProperty("RawMessage")
  private String rawMessage = null;

  @JsonProperty("RobotName")
  private String robotName = null;

  @JsonProperty("HostMachineName")
  private String hostMachineName = null;

  @JsonProperty("MachineId")
  private Long machineId = null;

  @JsonProperty("MachineKey")
  private UUID machineKey = null;

  /**
   * The RuntimeType of the job referenced by the JobKey field
   */
  public enum RuntimeTypeEnum {
    NONPRODUCTION("NonProduction"),
    ATTENDED("Attended"),
    UNATTENDED("Unattended"),
    DEVELOPMENT("Development"),
    STUDIO("Studio"),
    RPADEVELOPER("RpaDeveloper"),
    STUDIOX("StudioX"),
    CITIZENDEVELOPER("CitizenDeveloper"),
    HEADLESS("Headless"),
    STUDIOPRO("StudioPro"),
    RPADEVELOPERPRO("RpaDeveloperPro"),
    TESTAUTOMATION("TestAutomation"),
    AUTOMATIONCLOUD("AutomationCloud"),
    SERVERLESS("Serverless"),
    AUTOMATIONKIT("AutomationKit"),
    SERVERLESSTESTAUTOMATION("ServerlessTestAutomation"),
    AUTOMATIONCLOUDTESTAUTOMATION("AutomationCloudTestAutomation"),
    ATTENDEDSTUDIOWEB("AttendedStudioWeb");

    private String value;

    RuntimeTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static RuntimeTypeEnum fromValue(String input) {
      for (RuntimeTypeEnum b : RuntimeTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("RuntimeType")
  private RuntimeTypeEnum runtimeType = null;

  @JsonProperty("Id")
  private Long id = null;

  public LogDto level(LevelEnum level) {
    this.level = level;
    return this;
  }

   /**
   * Defines the log severity.
   * @return level
  **/
  public LevelEnum getLevel() {
    return level;
  }

  public void setLevel(LevelEnum level) {
    this.level = level;
  }

  public LogDto windowsIdentity(String windowsIdentity) {
    this.windowsIdentity = windowsIdentity;
    return this;
  }

   /**
   * The name of the user that performed the action that was logged.
   * @return windowsIdentity
  **/
  public String getWindowsIdentity() {
    return windowsIdentity;
  }

  public void setWindowsIdentity(String windowsIdentity) {
    this.windowsIdentity = windowsIdentity;
  }

  public LogDto processName(String processName) {
    this.processName = processName;
    return this;
  }

   /**
   * The name of the process.
   * @return processName
  **/
  public String getProcessName() {
    return processName;
  }

  public void setProcessName(String processName) {
    this.processName = processName;
  }

  public LogDto timeStamp(OffsetDateTime timeStamp) {
    this.timeStamp = timeStamp;
    return this;
  }

   /**
   * The exact date and time the action was performed.
   * @return timeStamp
  **/
  public OffsetDateTime getTimeStamp() {
    return timeStamp;
  }

  public void setTimeStamp(OffsetDateTime timeStamp) {
    this.timeStamp = timeStamp;
  }

  public LogDto message(String message) {
    this.message = message;
    return this;
  }

   /**
   * The log message. This can also be a message logged through the Log Message activity in UiPath Studio.
   * @return message
  **/
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public LogDto jobKey(UUID jobKey) {
    this.jobKey = jobKey;
    return this;
  }

   /**
   * The key of the job running the process that generated the log, if any.
   * @return jobKey
  **/
  public UUID getJobKey() {
    return jobKey;
  }

  public void setJobKey(UUID jobKey) {
    this.jobKey = jobKey;
  }

  public LogDto rawMessage(String rawMessage) {
    this.rawMessage = rawMessage;
    return this;
  }

   /**
   * A JSON format message containing all the above fields.
   * @return rawMessage
  **/
  public String getRawMessage() {
    return rawMessage;
  }

  public void setRawMessage(String rawMessage) {
    this.rawMessage = rawMessage;
  }

  public LogDto robotName(String robotName) {
    this.robotName = robotName;
    return this;
  }

   /**
   * The name of the Robot that generated the log.
   * @return robotName
  **/
  public String getRobotName() {
    return robotName;
  }

  public void setRobotName(String robotName) {
    this.robotName = robotName;
  }

  public LogDto hostMachineName(String hostMachineName) {
    this.hostMachineName = hostMachineName;
    return this;
  }

   /**
   * The name of the machine that generated the log
   * @return hostMachineName
  **/
  public String getHostMachineName() {
    return hostMachineName;
  }

  public void setHostMachineName(String hostMachineName) {
    this.hostMachineName = hostMachineName;
  }

  public LogDto machineId(Long machineId) {
    this.machineId = machineId;
    return this;
  }

   /**
   * The Id of the Machine on which the Robot that generated the log is running.
   * @return machineId
  **/
  public Long getMachineId() {
    return machineId;
  }

  public void setMachineId(Long machineId) {
    this.machineId = machineId;
  }

  public LogDto machineKey(UUID machineKey) {
    this.machineKey = machineKey;
    return this;
  }

   /**
   * The Key of the Machine on which the Robot that generated the log is running.
   * @return machineKey
  **/
  public UUID getMachineKey() {
    return machineKey;
  }

  public void setMachineKey(UUID machineKey) {
    this.machineKey = machineKey;
  }

  public LogDto runtimeType(RuntimeTypeEnum runtimeType) {
    this.runtimeType = runtimeType;
    return this;
  }

   /**
   * The RuntimeType of the job referenced by the JobKey field
   * @return runtimeType
  **/
  public RuntimeTypeEnum getRuntimeType() {
    return runtimeType;
  }

  public void setRuntimeType(RuntimeTypeEnum runtimeType) {
    this.runtimeType = runtimeType;
  }

  public LogDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LogDto logDto = (LogDto) o;
    return Objects.equals(this.level, logDto.level) &&
        Objects.equals(this.windowsIdentity, logDto.windowsIdentity) &&
        Objects.equals(this.processName, logDto.processName) &&
        Objects.equals(this.timeStamp, logDto.timeStamp) &&
        Objects.equals(this.message, logDto.message) &&
        Objects.equals(this.jobKey, logDto.jobKey) &&
        Objects.equals(this.rawMessage, logDto.rawMessage) &&
        Objects.equals(this.robotName, logDto.robotName) &&
        Objects.equals(this.hostMachineName, logDto.hostMachineName) &&
        Objects.equals(this.machineId, logDto.machineId) &&
        Objects.equals(this.machineKey, logDto.machineKey) &&
        Objects.equals(this.runtimeType, logDto.runtimeType) &&
        Objects.equals(this.id, logDto.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(level, windowsIdentity, processName, timeStamp, message, jobKey, rawMessage, robotName, hostMachineName, machineId, machineKey, runtimeType, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LogDto {\n");
    
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    windowsIdentity: ").append(toIndentedString(windowsIdentity)).append("\n");
    sb.append("    processName: ").append(toIndentedString(processName)).append("\n");
    sb.append("    timeStamp: ").append(toIndentedString(timeStamp)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    jobKey: ").append(toIndentedString(jobKey)).append("\n");
    sb.append("    rawMessage: ").append(toIndentedString(rawMessage)).append("\n");
    sb.append("    robotName: ").append(toIndentedString(robotName)).append("\n");
    sb.append("    hostMachineName: ").append(toIndentedString(hostMachineName)).append("\n");
    sb.append("    machineId: ").append(toIndentedString(machineId)).append("\n");
    sb.append("    machineKey: ").append(toIndentedString(machineKey)).append("\n");
    sb.append("    runtimeType: ").append(toIndentedString(runtimeType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
