/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MachineRuntimeDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class MachineRuntimeDto {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    NONPRODUCTION("NonProduction"),
    ATTENDED("Attended"),
    UNATTENDED("Unattended"),
    DEVELOPMENT("Development"),
    STUDIO("Studio"),
    RPADEVELOPER("RpaDeveloper"),
    STUDIOX("StudioX"),
    CITIZENDEVELOPER("CitizenDeveloper"),
    HEADLESS("Headless"),
    STUDIOPRO("StudioPro"),
    RPADEVELOPERPRO("RpaDeveloperPro"),
    TESTAUTOMATION("TestAutomation"),
    AUTOMATIONCLOUD("AutomationCloud"),
    SERVERLESS("Serverless"),
    AUTOMATIONKIT("AutomationKit"),
    SERVERLESSTESTAUTOMATION("ServerlessTestAutomation"),
    AUTOMATIONCLOUDTESTAUTOMATION("AutomationCloudTestAutomation"),
    ATTENDEDSTUDIOWEB("AttendedStudioWeb");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("Type")
  private TypeEnum type = null;

  @JsonProperty("Total")
  private Long total = null;

  @JsonProperty("Connected")
  private Long connected = null;

  @JsonProperty("Available")
  private Long available = null;

  public MachineRuntimeDto type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public MachineRuntimeDto total(Long total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  public Long getTotal() {
    return total;
  }

  public void setTotal(Long total) {
    this.total = total;
  }

  public MachineRuntimeDto connected(Long connected) {
    this.connected = connected;
    return this;
  }

   /**
   * Get connected
   * @return connected
  **/
  public Long getConnected() {
    return connected;
  }

  public void setConnected(Long connected) {
    this.connected = connected;
  }

  public MachineRuntimeDto available(Long available) {
    this.available = available;
    return this;
  }

   /**
   * Get available
   * @return available
  **/
  public Long getAvailable() {
    return available;
  }

  public void setAvailable(Long available) {
    this.available = available;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MachineRuntimeDto machineRuntimeDto = (MachineRuntimeDto) o;
    return Objects.equals(this.type, machineRuntimeDto.type) &&
        Objects.equals(this.total, machineRuntimeDto.total) &&
        Objects.equals(this.connected, machineRuntimeDto.connected) &&
        Objects.equals(this.available, machineRuntimeDto.available);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, total, connected, available);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MachineRuntimeDto {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    connected: ").append(toIndentedString(connected)).append("\n");
    sb.append("    available: ").append(toIndentedString(available)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
