/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * MachineDeleteBulkRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class MachineDeleteBulkRequest {
  @JsonProperty("machineIds")
  private List<Long> machineIds = null;

  public MachineDeleteBulkRequest machineIds(List<Long> machineIds) {
    this.machineIds = machineIds;
    return this;
  }

  public MachineDeleteBulkRequest addMachineIdsItem(Long machineIdsItem) {
    if (this.machineIds == null) {
      this.machineIds = new ArrayList<>();
    }
    this.machineIds.add(machineIdsItem);
    return this;
  }

   /**
   * Get machineIds
   * @return machineIds
  **/
  public List<Long> getMachineIds() {
    return machineIds;
  }

  public void setMachineIds(List<Long> machineIds) {
    this.machineIds = machineIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MachineDeleteBulkRequest machineDeleteBulkRequest = (MachineDeleteBulkRequest) o;
    return Objects.equals(this.machineIds, machineDeleteBulkRequest.machineIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(machineIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MachineDeleteBulkRequest {\n");
    
    sb.append("    machineIds: ").append(toIndentedString(machineIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
