/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MachineRobotSessionDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class MachineRobotSessionDto {
  @JsonProperty("MachineId")
  private Long machineId = null;

  @JsonProperty("MachineName")
  private String machineName = null;

  @JsonProperty("RobotId")
  private Long robotId = null;

  @JsonProperty("RobotUserName")
  private String robotUserName = null;

  @JsonProperty("SessionId")
  private Long sessionId = null;

  @JsonProperty("SessionName")
  private String sessionName = null;

  public MachineRobotSessionDto machineId(Long machineId) {
    this.machineId = machineId;
    return this;
  }

   /**
   * Get machineId
   * @return machineId
  **/
  public Long getMachineId() {
    return machineId;
  }

  public void setMachineId(Long machineId) {
    this.machineId = machineId;
  }

  public MachineRobotSessionDto machineName(String machineName) {
    this.machineName = machineName;
    return this;
  }

   /**
   * Get machineName
   * @return machineName
  **/
  public String getMachineName() {
    return machineName;
  }

  public void setMachineName(String machineName) {
    this.machineName = machineName;
  }

  public MachineRobotSessionDto robotId(Long robotId) {
    this.robotId = robotId;
    return this;
  }

   /**
   * Get robotId
   * @return robotId
  **/
  public Long getRobotId() {
    return robotId;
  }

  public void setRobotId(Long robotId) {
    this.robotId = robotId;
  }

  public MachineRobotSessionDto robotUserName(String robotUserName) {
    this.robotUserName = robotUserName;
    return this;
  }

   /**
   * Get robotUserName
   * @return robotUserName
  **/
  public String getRobotUserName() {
    return robotUserName;
  }

  public void setRobotUserName(String robotUserName) {
    this.robotUserName = robotUserName;
  }

  public MachineRobotSessionDto sessionId(Long sessionId) {
    this.sessionId = sessionId;
    return this;
  }

   /**
   * Get sessionId
   * @return sessionId
  **/
  public Long getSessionId() {
    return sessionId;
  }

  public void setSessionId(Long sessionId) {
    this.sessionId = sessionId;
  }

  public MachineRobotSessionDto sessionName(String sessionName) {
    this.sessionName = sessionName;
    return this;
  }

   /**
   * Get sessionName
   * @return sessionName
  **/
  public String getSessionName() {
    return sessionName;
  }

  public void setSessionName(String sessionName) {
    this.sessionName = sessionName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MachineRobotSessionDto machineRobotSessionDto = (MachineRobotSessionDto) o;
    return Objects.equals(this.machineId, machineRobotSessionDto.machineId) &&
        Objects.equals(this.machineName, machineRobotSessionDto.machineName) &&
        Objects.equals(this.robotId, machineRobotSessionDto.robotId) &&
        Objects.equals(this.robotUserName, machineRobotSessionDto.robotUserName) &&
        Objects.equals(this.sessionId, machineRobotSessionDto.sessionId) &&
        Objects.equals(this.sessionName, machineRobotSessionDto.sessionName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(machineId, machineName, robotId, robotUserName, sessionId, sessionName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MachineRobotSessionDto {\n");
    
    sb.append("    machineId: ").append(toIndentedString(machineId)).append("\n");
    sb.append("    machineName: ").append(toIndentedString(machineName)).append("\n");
    sb.append("    robotId: ").append(toIndentedString(robotId)).append("\n");
    sb.append("    robotUserName: ").append(toIndentedString(robotUserName)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    sessionName: ").append(toIndentedString(sessionName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
