/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.uipath.orchestrator.MaintenanceStateLog;

import java.util.ArrayList;
import java.util.List;
/**
 * MaintenanceSetting
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class MaintenanceSetting {
  /**
   * Gets or Sets state
   */
  public enum StateEnum {
    NONE("None"),
    DRAINING("Draining"),
    SUSPENDED("Suspended");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StateEnum fromValue(String input) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("state")
  private StateEnum state = null;

  @JsonProperty("maintenanceLogs")
  private List<MaintenanceStateLog> maintenanceLogs = null;

  @JsonProperty("jobStopsAttempted")
  private Integer jobStopsAttempted = null;

  @JsonProperty("jobKillsAttempted")
  private Integer jobKillsAttempted = null;

  @JsonProperty("triggersSkipped")
  private Integer triggersSkipped = null;

  @JsonProperty("systemTriggersSkipped")
  private Integer systemTriggersSkipped = null;

  public MaintenanceSetting state(StateEnum state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }

   /**
   * Get maintenanceLogs
   * @return maintenanceLogs
  **/
  public List<MaintenanceStateLog> getMaintenanceLogs() {
    return maintenanceLogs;
  }

  public MaintenanceSetting jobStopsAttempted(Integer jobStopsAttempted) {
    this.jobStopsAttempted = jobStopsAttempted;
    return this;
  }

   /**
   * Get jobStopsAttempted
   * @return jobStopsAttempted
  **/
  public Integer getJobStopsAttempted() {
    return jobStopsAttempted;
  }

  public void setJobStopsAttempted(Integer jobStopsAttempted) {
    this.jobStopsAttempted = jobStopsAttempted;
  }

  public MaintenanceSetting jobKillsAttempted(Integer jobKillsAttempted) {
    this.jobKillsAttempted = jobKillsAttempted;
    return this;
  }

   /**
   * Get jobKillsAttempted
   * @return jobKillsAttempted
  **/
  public Integer getJobKillsAttempted() {
    return jobKillsAttempted;
  }

  public void setJobKillsAttempted(Integer jobKillsAttempted) {
    this.jobKillsAttempted = jobKillsAttempted;
  }

  public MaintenanceSetting triggersSkipped(Integer triggersSkipped) {
    this.triggersSkipped = triggersSkipped;
    return this;
  }

   /**
   * Get triggersSkipped
   * @return triggersSkipped
  **/
  public Integer getTriggersSkipped() {
    return triggersSkipped;
  }

  public void setTriggersSkipped(Integer triggersSkipped) {
    this.triggersSkipped = triggersSkipped;
  }

  public MaintenanceSetting systemTriggersSkipped(Integer systemTriggersSkipped) {
    this.systemTriggersSkipped = systemTriggersSkipped;
    return this;
  }

   /**
   * Get systemTriggersSkipped
   * @return systemTriggersSkipped
  **/
  public Integer getSystemTriggersSkipped() {
    return systemTriggersSkipped;
  }

  public void setSystemTriggersSkipped(Integer systemTriggersSkipped) {
    this.systemTriggersSkipped = systemTriggersSkipped;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MaintenanceSetting maintenanceSetting = (MaintenanceSetting) o;
    return Objects.equals(this.state, maintenanceSetting.state) &&
        Objects.equals(this.maintenanceLogs, maintenanceSetting.maintenanceLogs) &&
        Objects.equals(this.jobStopsAttempted, maintenanceSetting.jobStopsAttempted) &&
        Objects.equals(this.jobKillsAttempted, maintenanceSetting.jobKillsAttempted) &&
        Objects.equals(this.triggersSkipped, maintenanceSetting.triggersSkipped) &&
        Objects.equals(this.systemTriggersSkipped, maintenanceSetting.systemTriggersSkipped);
  }

  @Override
  public int hashCode() {
    return Objects.hash(state, maintenanceLogs, jobStopsAttempted, jobKillsAttempted, triggersSkipped, systemTriggersSkipped);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MaintenanceSetting {\n");
    
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    maintenanceLogs: ").append(toIndentedString(maintenanceLogs)).append("\n");
    sb.append("    jobStopsAttempted: ").append(toIndentedString(jobStopsAttempted)).append("\n");
    sb.append("    jobKillsAttempted: ").append(toIndentedString(jobKillsAttempted)).append("\n");
    sb.append("    triggersSkipped: ").append(toIndentedString(triggersSkipped)).append("\n");
    sb.append("    systemTriggersSkipped: ").append(toIndentedString(systemTriggersSkipped)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
