/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * Represents a maintenance window for a cloud machine
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class MaintenanceWindowDto {
  @JsonProperty("enabled")
  private Boolean enabled = null;

  /**
   * The strategy for stopping jobs when the window begins
   */
  public enum JobStopStrategyEnum {
    NONE("None"),
    KILL("Kill");

    private String value;

    JobStopStrategyEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static JobStopStrategyEnum fromValue(String input) {
      for (JobStopStrategyEnum b : JobStopStrategyEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("jobStopStrategy")
  private JobStopStrategyEnum jobStopStrategy = null;

  @JsonProperty("cronExpression")
  private String cronExpression = null;

  @JsonProperty("timezoneId")
  private String timezoneId = null;

  @JsonProperty("duration")
  private Integer duration = null;

  @JsonProperty("nextExecutionTime")
  private OffsetDateTime nextExecutionTime = null;

  public MaintenanceWindowDto enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Whether the maintenance window is enabled
   * @return enabled
  **/
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public MaintenanceWindowDto jobStopStrategy(JobStopStrategyEnum jobStopStrategy) {
    this.jobStopStrategy = jobStopStrategy;
    return this;
  }

   /**
   * The strategy for stopping jobs when the window begins
   * @return jobStopStrategy
  **/
  public JobStopStrategyEnum getJobStopStrategy() {
    return jobStopStrategy;
  }

  public void setJobStopStrategy(JobStopStrategyEnum jobStopStrategy) {
    this.jobStopStrategy = jobStopStrategy;
  }

  public MaintenanceWindowDto cronExpression(String cronExpression) {
    this.cronExpression = cronExpression;
    return this;
  }

   /**
   * The recurrence pattern as a cron expression
   * @return cronExpression
  **/
  public String getCronExpression() {
    return cronExpression;
  }

  public void setCronExpression(String cronExpression) {
    this.cronExpression = cronExpression;
  }

  public MaintenanceWindowDto timezoneId(String timezoneId) {
    this.timezoneId = timezoneId;
    return this;
  }

   /**
   * The Timezone Id
   * @return timezoneId
  **/
  public String getTimezoneId() {
    return timezoneId;
  }

  public void setTimezoneId(String timezoneId) {
    this.timezoneId = timezoneId;
  }

  public MaintenanceWindowDto duration(Integer duration) {
    this.duration = duration;
    return this;
  }

   /**
   * The duration of the maintenance window in minutes
   * @return duration
  **/
  public Integer getDuration() {
    return duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  public MaintenanceWindowDto nextExecutionTime(OffsetDateTime nextExecutionTime) {
    this.nextExecutionTime = nextExecutionTime;
    return this;
  }

   /**
   * The next execution time of the maintenance window
   * @return nextExecutionTime
  **/
  public OffsetDateTime getNextExecutionTime() {
    return nextExecutionTime;
  }

  public void setNextExecutionTime(OffsetDateTime nextExecutionTime) {
    this.nextExecutionTime = nextExecutionTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MaintenanceWindowDto maintenanceWindowDto = (MaintenanceWindowDto) o;
    return Objects.equals(this.enabled, maintenanceWindowDto.enabled) &&
        Objects.equals(this.jobStopStrategy, maintenanceWindowDto.jobStopStrategy) &&
        Objects.equals(this.cronExpression, maintenanceWindowDto.cronExpression) &&
        Objects.equals(this.timezoneId, maintenanceWindowDto.timezoneId) &&
        Objects.equals(this.duration, maintenanceWindowDto.duration) &&
        Objects.equals(this.nextExecutionTime, maintenanceWindowDto.nextExecutionTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, jobStopStrategy, cronExpression, timezoneId, duration, nextExecutionTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MaintenanceWindowDto {\n");
    
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    jobStopStrategy: ").append(toIndentedString(jobStopStrategy)).append("\n");
    sb.append("    cronExpression: ").append(toIndentedString(cronExpression)).append("\n");
    sb.append("    timezoneId: ").append(toIndentedString(timezoneId)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    nextExecutionTime: ").append(toIndentedString(nextExecutionTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
