/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.uipath.orchestrator.ExtendedMachineDto;

import java.util.ArrayList;
import java.util.List;
/**
 * ODataValueOfIEnumerableOfExtendedMachineDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class ODataValueOfIEnumerableOfExtendedMachineDto {
  @JsonProperty("value")
  private List<ExtendedMachineDto> value = null;

  public ODataValueOfIEnumerableOfExtendedMachineDto value(List<ExtendedMachineDto> value) {
    this.value = value;
    return this;
  }

  public ODataValueOfIEnumerableOfExtendedMachineDto addValueItem(ExtendedMachineDto valueItem) {
    if (this.value == null) {
      this.value = new ArrayList<>();
    }
    this.value.add(valueItem);
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  public List<ExtendedMachineDto> getValue() {
    return value;
  }

  public void setValue(List<ExtendedMachineDto> value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ODataValueOfIEnumerableOfExtendedMachineDto odataValueOfIEnumerableOfExtendedMachineDto = (ODataValueOfIEnumerableOfExtendedMachineDto) o;
    return Objects.equals(this.value, odataValueOfIEnumerableOfExtendedMachineDto.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ODataValueOfIEnumerableOfExtendedMachineDto {\n");
    
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
