/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
import java.util.UUID;
/**
 * PackageDeletedEvent
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class PackageDeletedEvent {
  @JsonProperty("key")
  private UUID key = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("version")
  private String version = null;

  /**
   * Gets or Sets projectType
   */
  public enum ProjectTypeEnum {
    UNDEFINED("Undefined"),
    PROCESS("Process"),
    PROCESSLIBRARY("ProcessLibrary"),
    BUSINESSPROCESS("BusinessProcess"),
    BUSINESSPROCESSLIBRARY("BusinessProcessLibrary"),
    TESTAUTOMATIONPROCESS("TestAutomationProcess");

    private String value;

    ProjectTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ProjectTypeEnum fromValue(String input) {
      for (ProjectTypeEnum b : ProjectTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("projectType")
  private ProjectTypeEnum projectType = null;

  @JsonProperty("feedId")
  private UUID feedId = null;

  @JsonProperty("eventTime")
  private OffsetDateTime eventTime = null;

  @JsonProperty("eventSource")
  private Object eventSource = null;

  public PackageDeletedEvent key(UUID key) {
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  public UUID getKey() {
    return key;
  }

  public void setKey(UUID key) {
    this.key = key;
  }

  public PackageDeletedEvent name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PackageDeletedEvent version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public PackageDeletedEvent projectType(ProjectTypeEnum projectType) {
    this.projectType = projectType;
    return this;
  }

   /**
   * Get projectType
   * @return projectType
  **/
  public ProjectTypeEnum getProjectType() {
    return projectType;
  }

  public void setProjectType(ProjectTypeEnum projectType) {
    this.projectType = projectType;
  }

  public PackageDeletedEvent feedId(UUID feedId) {
    this.feedId = feedId;
    return this;
  }

   /**
   * Get feedId
   * @return feedId
  **/
  public UUID getFeedId() {
    return feedId;
  }

  public void setFeedId(UUID feedId) {
    this.feedId = feedId;
  }

  public PackageDeletedEvent eventTime(OffsetDateTime eventTime) {
    this.eventTime = eventTime;
    return this;
  }

   /**
   * Get eventTime
   * @return eventTime
  **/
  public OffsetDateTime getEventTime() {
    return eventTime;
  }

  public void setEventTime(OffsetDateTime eventTime) {
    this.eventTime = eventTime;
  }

  public PackageDeletedEvent eventSource(Object eventSource) {
    this.eventSource = eventSource;
    return this;
  }

   /**
   * Get eventSource
   * @return eventSource
  **/
  public Object getEventSource() {
    return eventSource;
  }

  public void setEventSource(Object eventSource) {
    this.eventSource = eventSource;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PackageDeletedEvent packageDeletedEvent = (PackageDeletedEvent) o;
    return Objects.equals(this.key, packageDeletedEvent.key) &&
        Objects.equals(this.name, packageDeletedEvent.name) &&
        Objects.equals(this.version, packageDeletedEvent.version) &&
        Objects.equals(this.projectType, packageDeletedEvent.projectType) &&
        Objects.equals(this.feedId, packageDeletedEvent.feedId) &&
        Objects.equals(this.eventTime, packageDeletedEvent.eventTime) &&
        Objects.equals(this.eventSource, packageDeletedEvent.eventSource);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, name, version, projectType, feedId, eventTime, eventSource);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PackageDeletedEvent {\n");
    
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    projectType: ").append(toIndentedString(projectType)).append("\n");
    sb.append("    feedId: ").append(toIndentedString(feedId)).append("\n");
    sb.append("    eventTime: ").append(toIndentedString(eventTime)).append("\n");
    sb.append("    eventSource: ").append(toIndentedString(eventSource)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
