/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.uipath.orchestrator.TagDto;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
/**
 * ProcessScheduleUpdatedEvent
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class ProcessScheduleUpdatedEvent {
  @JsonProperty("key")
  private UUID key = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("enabled")
  private Boolean enabled = null;

  @JsonProperty("releaseName")
  private String releaseName = null;

  @JsonProperty("packageName")
  private String packageName = null;

  @JsonProperty("environmentName")
  private String environmentName = null;

  @JsonProperty("specificPriorityValue")
  private Integer specificPriorityValue = null;

  /**
   * Gets or Sets runtimeType
   */
  public enum RuntimeTypeEnum {
    NONPRODUCTION("NonProduction"),
    ATTENDED("Attended"),
    UNATTENDED("Unattended"),
    DEVELOPMENT("Development"),
    STUDIO("Studio"),
    RPADEVELOPER("RpaDeveloper"),
    STUDIOX("StudioX"),
    CITIZENDEVELOPER("CitizenDeveloper"),
    HEADLESS("Headless"),
    STUDIOPRO("StudioPro"),
    RPADEVELOPERPRO("RpaDeveloperPro"),
    TESTAUTOMATION("TestAutomation"),
    AUTOMATIONCLOUD("AutomationCloud"),
    SERVERLESS("Serverless"),
    AUTOMATIONKIT("AutomationKit"),
    SERVERLESSTESTAUTOMATION("ServerlessTestAutomation"),
    AUTOMATIONCLOUDTESTAUTOMATION("AutomationCloudTestAutomation"),
    ATTENDEDSTUDIOWEB("AttendedStudioWeb");

    private String value;

    RuntimeTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static RuntimeTypeEnum fromValue(String input) {
      for (RuntimeTypeEnum b : RuntimeTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("runtimeType")
  private RuntimeTypeEnum runtimeType = null;

  @JsonProperty("stopProcessExpression")
  private String stopProcessExpression = null;

  /**
   * Gets or Sets stopStrategy
   */
  public enum StopStrategyEnum {
    SOFTSTOP("SoftStop"),
    KILL("Kill");

    private String value;

    StopStrategyEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StopStrategyEnum fromValue(String input) {
      for (StopStrategyEnum b : StopStrategyEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("stopStrategy")
  private StopStrategyEnum stopStrategy = null;

  @JsonProperty("killProcessExpression")
  private String killProcessExpression = null;

  @JsonProperty("timeZoneId")
  private String timeZoneId = null;

  @JsonProperty("stopProcessDate")
  private OffsetDateTime stopProcessDate = null;

  @JsonProperty("inputArguments")
  private String inputArguments = null;

  @JsonProperty("queueDefinitionName")
  private String queueDefinitionName = null;

  @JsonProperty("activateOnJobComplete")
  private Boolean activateOnJobComplete = null;

  @JsonProperty("itemsActivationThreshold")
  private Long itemsActivationThreshold = null;

  @JsonProperty("itemsPerJobActivationTarget")
  private Long itemsPerJobActivationTarget = null;

  @JsonProperty("maxJobsForActivation")
  private Long maxJobsForActivation = null;

  @JsonProperty("resumeOnSameContext")
  private Boolean resumeOnSameContext = null;

  @JsonProperty("tags")
  private List<TagDto> tags = null;

  @JsonProperty("alertPendingExpression")
  private String alertPendingExpression = null;

  @JsonProperty("alertRunningExpression")
  private String alertRunningExpression = null;

  @JsonProperty("runAsMe")
  private Boolean runAsMe = null;

  @JsonProperty("consecutiveJobFailuresThreshold")
  private Integer consecutiveJobFailuresThreshold = null;

  @JsonProperty("jobFailuresGracePeriodInHours")
  private Integer jobFailuresGracePeriodInHours = null;

  @JsonProperty("isConnected")
  private Boolean isConnected = null;

  @JsonProperty("releaseKey")
  private UUID releaseKey = null;

  @JsonProperty("queueDefinitionKey")
  private UUID queueDefinitionKey = null;

  @JsonProperty("folderKeys")
  private List<UUID> folderKeys = null;

  @JsonProperty("eventTime")
  private OffsetDateTime eventTime = null;

  @JsonProperty("eventSource")
  private Object eventSource = null;

   /**
   * Get key
   * @return key
  **/
  public UUID getKey() {
    return key;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  public Boolean isEnabled() {
    return enabled;
  }

   /**
   * Get releaseName
   * @return releaseName
  **/
  public String getReleaseName() {
    return releaseName;
  }

   /**
   * Get packageName
   * @return packageName
  **/
  public String getPackageName() {
    return packageName;
  }

   /**
   * Get environmentName
   * @return environmentName
  **/
  public String getEnvironmentName() {
    return environmentName;
  }

   /**
   * Get specificPriorityValue
   * @return specificPriorityValue
  **/
  public Integer getSpecificPriorityValue() {
    return specificPriorityValue;
  }

   /**
   * Get runtimeType
   * @return runtimeType
  **/
  public RuntimeTypeEnum getRuntimeType() {
    return runtimeType;
  }

   /**
   * Get stopProcessExpression
   * @return stopProcessExpression
  **/
  public String getStopProcessExpression() {
    return stopProcessExpression;
  }

   /**
   * Get stopStrategy
   * @return stopStrategy
  **/
  public StopStrategyEnum getStopStrategy() {
    return stopStrategy;
  }

   /**
   * Get killProcessExpression
   * @return killProcessExpression
  **/
  public String getKillProcessExpression() {
    return killProcessExpression;
  }

   /**
   * Get timeZoneId
   * @return timeZoneId
  **/
  public String getTimeZoneId() {
    return timeZoneId;
  }

   /**
   * Get stopProcessDate
   * @return stopProcessDate
  **/
  public OffsetDateTime getStopProcessDate() {
    return stopProcessDate;
  }

   /**
   * Get inputArguments
   * @return inputArguments
  **/
  public String getInputArguments() {
    return inputArguments;
  }

   /**
   * Get queueDefinitionName
   * @return queueDefinitionName
  **/
  public String getQueueDefinitionName() {
    return queueDefinitionName;
  }

   /**
   * Get activateOnJobComplete
   * @return activateOnJobComplete
  **/
  public Boolean isActivateOnJobComplete() {
    return activateOnJobComplete;
  }

   /**
   * Get itemsActivationThreshold
   * @return itemsActivationThreshold
  **/
  public Long getItemsActivationThreshold() {
    return itemsActivationThreshold;
  }

   /**
   * Get itemsPerJobActivationTarget
   * @return itemsPerJobActivationTarget
  **/
  public Long getItemsPerJobActivationTarget() {
    return itemsPerJobActivationTarget;
  }

   /**
   * Get maxJobsForActivation
   * @return maxJobsForActivation
  **/
  public Long getMaxJobsForActivation() {
    return maxJobsForActivation;
  }

   /**
   * Get resumeOnSameContext
   * @return resumeOnSameContext
  **/
  public Boolean isResumeOnSameContext() {
    return resumeOnSameContext;
  }

   /**
   * Get tags
   * @return tags
  **/
  public List<TagDto> getTags() {
    return tags;
  }

   /**
   * Get alertPendingExpression
   * @return alertPendingExpression
  **/
  public String getAlertPendingExpression() {
    return alertPendingExpression;
  }

   /**
   * Get alertRunningExpression
   * @return alertRunningExpression
  **/
  public String getAlertRunningExpression() {
    return alertRunningExpression;
  }

   /**
   * Get runAsMe
   * @return runAsMe
  **/
  public Boolean isRunAsMe() {
    return runAsMe;
  }

   /**
   * Get consecutiveJobFailuresThreshold
   * @return consecutiveJobFailuresThreshold
  **/
  public Integer getConsecutiveJobFailuresThreshold() {
    return consecutiveJobFailuresThreshold;
  }

   /**
   * Get jobFailuresGracePeriodInHours
   * @return jobFailuresGracePeriodInHours
  **/
  public Integer getJobFailuresGracePeriodInHours() {
    return jobFailuresGracePeriodInHours;
  }

   /**
   * Get isConnected
   * @return isConnected
  **/
  public Boolean isIsConnected() {
    return isConnected;
  }

  public ProcessScheduleUpdatedEvent releaseKey(UUID releaseKey) {
    this.releaseKey = releaseKey;
    return this;
  }

   /**
   * Get releaseKey
   * @return releaseKey
  **/
  public UUID getReleaseKey() {
    return releaseKey;
  }

  public void setReleaseKey(UUID releaseKey) {
    this.releaseKey = releaseKey;
  }

  public ProcessScheduleUpdatedEvent queueDefinitionKey(UUID queueDefinitionKey) {
    this.queueDefinitionKey = queueDefinitionKey;
    return this;
  }

   /**
   * Get queueDefinitionKey
   * @return queueDefinitionKey
  **/
  public UUID getQueueDefinitionKey() {
    return queueDefinitionKey;
  }

  public void setQueueDefinitionKey(UUID queueDefinitionKey) {
    this.queueDefinitionKey = queueDefinitionKey;
  }

  public ProcessScheduleUpdatedEvent folderKeys(List<UUID> folderKeys) {
    this.folderKeys = folderKeys;
    return this;
  }

  public ProcessScheduleUpdatedEvent addFolderKeysItem(UUID folderKeysItem) {
    if (this.folderKeys == null) {
      this.folderKeys = new ArrayList<>();
    }
    this.folderKeys.add(folderKeysItem);
    return this;
  }

   /**
   * Get folderKeys
   * @return folderKeys
  **/
  public List<UUID> getFolderKeys() {
    return folderKeys;
  }

  public void setFolderKeys(List<UUID> folderKeys) {
    this.folderKeys = folderKeys;
  }

  public ProcessScheduleUpdatedEvent eventTime(OffsetDateTime eventTime) {
    this.eventTime = eventTime;
    return this;
  }

   /**
   * Get eventTime
   * @return eventTime
  **/
  public OffsetDateTime getEventTime() {
    return eventTime;
  }

  public void setEventTime(OffsetDateTime eventTime) {
    this.eventTime = eventTime;
  }

  public ProcessScheduleUpdatedEvent eventSource(Object eventSource) {
    this.eventSource = eventSource;
    return this;
  }

   /**
   * Get eventSource
   * @return eventSource
  **/
  public Object getEventSource() {
    return eventSource;
  }

  public void setEventSource(Object eventSource) {
    this.eventSource = eventSource;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessScheduleUpdatedEvent processScheduleUpdatedEvent = (ProcessScheduleUpdatedEvent) o;
    return Objects.equals(this.key, processScheduleUpdatedEvent.key) &&
        Objects.equals(this.name, processScheduleUpdatedEvent.name) &&
        Objects.equals(this.description, processScheduleUpdatedEvent.description) &&
        Objects.equals(this.enabled, processScheduleUpdatedEvent.enabled) &&
        Objects.equals(this.releaseName, processScheduleUpdatedEvent.releaseName) &&
        Objects.equals(this.packageName, processScheduleUpdatedEvent.packageName) &&
        Objects.equals(this.environmentName, processScheduleUpdatedEvent.environmentName) &&
        Objects.equals(this.specificPriorityValue, processScheduleUpdatedEvent.specificPriorityValue) &&
        Objects.equals(this.runtimeType, processScheduleUpdatedEvent.runtimeType) &&
        Objects.equals(this.stopProcessExpression, processScheduleUpdatedEvent.stopProcessExpression) &&
        Objects.equals(this.stopStrategy, processScheduleUpdatedEvent.stopStrategy) &&
        Objects.equals(this.killProcessExpression, processScheduleUpdatedEvent.killProcessExpression) &&
        Objects.equals(this.timeZoneId, processScheduleUpdatedEvent.timeZoneId) &&
        Objects.equals(this.stopProcessDate, processScheduleUpdatedEvent.stopProcessDate) &&
        Objects.equals(this.inputArguments, processScheduleUpdatedEvent.inputArguments) &&
        Objects.equals(this.queueDefinitionName, processScheduleUpdatedEvent.queueDefinitionName) &&
        Objects.equals(this.activateOnJobComplete, processScheduleUpdatedEvent.activateOnJobComplete) &&
        Objects.equals(this.itemsActivationThreshold, processScheduleUpdatedEvent.itemsActivationThreshold) &&
        Objects.equals(this.itemsPerJobActivationTarget, processScheduleUpdatedEvent.itemsPerJobActivationTarget) &&
        Objects.equals(this.maxJobsForActivation, processScheduleUpdatedEvent.maxJobsForActivation) &&
        Objects.equals(this.resumeOnSameContext, processScheduleUpdatedEvent.resumeOnSameContext) &&
        Objects.equals(this.tags, processScheduleUpdatedEvent.tags) &&
        Objects.equals(this.alertPendingExpression, processScheduleUpdatedEvent.alertPendingExpression) &&
        Objects.equals(this.alertRunningExpression, processScheduleUpdatedEvent.alertRunningExpression) &&
        Objects.equals(this.runAsMe, processScheduleUpdatedEvent.runAsMe) &&
        Objects.equals(this.consecutiveJobFailuresThreshold, processScheduleUpdatedEvent.consecutiveJobFailuresThreshold) &&
        Objects.equals(this.jobFailuresGracePeriodInHours, processScheduleUpdatedEvent.jobFailuresGracePeriodInHours) &&
        Objects.equals(this.isConnected, processScheduleUpdatedEvent.isConnected) &&
        Objects.equals(this.releaseKey, processScheduleUpdatedEvent.releaseKey) &&
        Objects.equals(this.queueDefinitionKey, processScheduleUpdatedEvent.queueDefinitionKey) &&
        Objects.equals(this.folderKeys, processScheduleUpdatedEvent.folderKeys) &&
        Objects.equals(this.eventTime, processScheduleUpdatedEvent.eventTime) &&
        Objects.equals(this.eventSource, processScheduleUpdatedEvent.eventSource);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, name, description, enabled, releaseName, packageName, environmentName, specificPriorityValue, runtimeType, stopProcessExpression, stopStrategy, killProcessExpression, timeZoneId, stopProcessDate, inputArguments, queueDefinitionName, activateOnJobComplete, itemsActivationThreshold, itemsPerJobActivationTarget, maxJobsForActivation, resumeOnSameContext, tags, alertPendingExpression, alertRunningExpression, runAsMe, consecutiveJobFailuresThreshold, jobFailuresGracePeriodInHours, isConnected, releaseKey, queueDefinitionKey, folderKeys, eventTime, eventSource);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessScheduleUpdatedEvent {\n");
    
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    releaseName: ").append(toIndentedString(releaseName)).append("\n");
    sb.append("    packageName: ").append(toIndentedString(packageName)).append("\n");
    sb.append("    environmentName: ").append(toIndentedString(environmentName)).append("\n");
    sb.append("    specificPriorityValue: ").append(toIndentedString(specificPriorityValue)).append("\n");
    sb.append("    runtimeType: ").append(toIndentedString(runtimeType)).append("\n");
    sb.append("    stopProcessExpression: ").append(toIndentedString(stopProcessExpression)).append("\n");
    sb.append("    stopStrategy: ").append(toIndentedString(stopStrategy)).append("\n");
    sb.append("    killProcessExpression: ").append(toIndentedString(killProcessExpression)).append("\n");
    sb.append("    timeZoneId: ").append(toIndentedString(timeZoneId)).append("\n");
    sb.append("    stopProcessDate: ").append(toIndentedString(stopProcessDate)).append("\n");
    sb.append("    inputArguments: ").append(toIndentedString(inputArguments)).append("\n");
    sb.append("    queueDefinitionName: ").append(toIndentedString(queueDefinitionName)).append("\n");
    sb.append("    activateOnJobComplete: ").append(toIndentedString(activateOnJobComplete)).append("\n");
    sb.append("    itemsActivationThreshold: ").append(toIndentedString(itemsActivationThreshold)).append("\n");
    sb.append("    itemsPerJobActivationTarget: ").append(toIndentedString(itemsPerJobActivationTarget)).append("\n");
    sb.append("    maxJobsForActivation: ").append(toIndentedString(maxJobsForActivation)).append("\n");
    sb.append("    resumeOnSameContext: ").append(toIndentedString(resumeOnSameContext)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    alertPendingExpression: ").append(toIndentedString(alertPendingExpression)).append("\n");
    sb.append("    alertRunningExpression: ").append(toIndentedString(alertRunningExpression)).append("\n");
    sb.append("    runAsMe: ").append(toIndentedString(runAsMe)).append("\n");
    sb.append("    consecutiveJobFailuresThreshold: ").append(toIndentedString(consecutiveJobFailuresThreshold)).append("\n");
    sb.append("    jobFailuresGracePeriodInHours: ").append(toIndentedString(jobFailuresGracePeriodInHours)).append("\n");
    sb.append("    isConnected: ").append(toIndentedString(isConnected)).append("\n");
    sb.append("    releaseKey: ").append(toIndentedString(releaseKey)).append("\n");
    sb.append("    queueDefinitionKey: ").append(toIndentedString(queueDefinitionKey)).append("\n");
    sb.append("    folderKeys: ").append(toIndentedString(folderKeys)).append("\n");
    sb.append("    eventTime: ").append(toIndentedString(eventTime)).append("\n");
    sb.append("    eventSource: ").append(toIndentedString(eventSource)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
