/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.uipath.orchestrator.QueueDefinitionEventDto;
import com.uipath.orchestrator.QueueItemSimpleEventDto;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
/**
 * This event is raised whenever new queue items were added
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class QueueItemAddedEventDto {
  @JsonProperty("Type")
  private String type = null;

  @JsonProperty("EventId")
  private String eventId = null;

  @JsonProperty("EntityKey")
  private UUID entityKey = null;

  @JsonProperty("Timestamp")
  private OffsetDateTime timestamp = null;

  @JsonProperty("Queue")
  private QueueDefinitionEventDto queue = null;

  @JsonProperty("QueueItems")
  private List<QueueItemSimpleEventDto> queueItems = null;

  @JsonProperty("EventTime")
  private OffsetDateTime eventTime = null;

  @JsonProperty("TenantId")
  private Integer tenantId = null;

  @JsonProperty("OrganizationUnitId")
  private Long organizationUnitId = null;

  @JsonProperty("OrganizationUnitKey")
  private UUID organizationUnitKey = null;

  @JsonProperty("UserId")
  private Long userId = null;

  public QueueItemAddedEventDto type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public QueueItemAddedEventDto eventId(String eventId) {
    this.eventId = eventId;
    return this;
  }

   /**
   * Get eventId
   * @return eventId
  **/
  public String getEventId() {
    return eventId;
  }

  public void setEventId(String eventId) {
    this.eventId = eventId;
  }

  public QueueItemAddedEventDto entityKey(UUID entityKey) {
    this.entityKey = entityKey;
    return this;
  }

   /**
   * Get entityKey
   * @return entityKey
  **/
  public UUID getEntityKey() {
    return entityKey;
  }

  public void setEntityKey(UUID entityKey) {
    this.entityKey = entityKey;
  }

  public QueueItemAddedEventDto timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }

  public QueueItemAddedEventDto queue(QueueDefinitionEventDto queue) {
    this.queue = queue;
    return this;
  }

   /**
   * Get queue
   * @return queue
  **/
  public QueueDefinitionEventDto getQueue() {
    return queue;
  }

  public void setQueue(QueueDefinitionEventDto queue) {
    this.queue = queue;
  }

   /**
   * Get queueItems
   * @return queueItems
  **/
  public List<QueueItemSimpleEventDto> getQueueItems() {
    return queueItems;
  }

  public QueueItemAddedEventDto eventTime(OffsetDateTime eventTime) {
    this.eventTime = eventTime;
    return this;
  }

   /**
   * Get eventTime
   * @return eventTime
  **/
  public OffsetDateTime getEventTime() {
    return eventTime;
  }

  public void setEventTime(OffsetDateTime eventTime) {
    this.eventTime = eventTime;
  }

  public QueueItemAddedEventDto tenantId(Integer tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Get tenantId
   * @return tenantId
  **/
  public Integer getTenantId() {
    return tenantId;
  }

  public void setTenantId(Integer tenantId) {
    this.tenantId = tenantId;
  }

  public QueueItemAddedEventDto organizationUnitId(Long organizationUnitId) {
    this.organizationUnitId = organizationUnitId;
    return this;
  }

   /**
   * Get organizationUnitId
   * @return organizationUnitId
  **/
  public Long getOrganizationUnitId() {
    return organizationUnitId;
  }

  public void setOrganizationUnitId(Long organizationUnitId) {
    this.organizationUnitId = organizationUnitId;
  }

  public QueueItemAddedEventDto organizationUnitKey(UUID organizationUnitKey) {
    this.organizationUnitKey = organizationUnitKey;
    return this;
  }

   /**
   * Get organizationUnitKey
   * @return organizationUnitKey
  **/
  public UUID getOrganizationUnitKey() {
    return organizationUnitKey;
  }

  public void setOrganizationUnitKey(UUID organizationUnitKey) {
    this.organizationUnitKey = organizationUnitKey;
  }

  public QueueItemAddedEventDto userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueueItemAddedEventDto queueItemAddedEventDto = (QueueItemAddedEventDto) o;
    return Objects.equals(this.type, queueItemAddedEventDto.type) &&
        Objects.equals(this.eventId, queueItemAddedEventDto.eventId) &&
        Objects.equals(this.entityKey, queueItemAddedEventDto.entityKey) &&
        Objects.equals(this.timestamp, queueItemAddedEventDto.timestamp) &&
        Objects.equals(this.queue, queueItemAddedEventDto.queue) &&
        Objects.equals(this.queueItems, queueItemAddedEventDto.queueItems) &&
        Objects.equals(this.eventTime, queueItemAddedEventDto.eventTime) &&
        Objects.equals(this.tenantId, queueItemAddedEventDto.tenantId) &&
        Objects.equals(this.organizationUnitId, queueItemAddedEventDto.organizationUnitId) &&
        Objects.equals(this.organizationUnitKey, queueItemAddedEventDto.organizationUnitKey) &&
        Objects.equals(this.userId, queueItemAddedEventDto.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, eventId, entityKey, timestamp, queue, queueItems, eventTime, tenantId, organizationUnitId, organizationUnitKey, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueueItemAddedEventDto {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    entityKey: ").append(toIndentedString(entityKey)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    queue: ").append(toIndentedString(queue)).append("\n");
    sb.append("    queueItems: ").append(toIndentedString(queueItems)).append("\n");
    sb.append("    eventTime: ").append(toIndentedString(eventTime)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    organizationUnitId: ").append(toIndentedString(organizationUnitId)).append("\n");
    sb.append("    organizationUnitKey: ").append(toIndentedString(organizationUnitKey)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
