/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.uipath.orchestrator.QueueDefinitionDto;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
/**
 * Stores aggregated report information about the processing status of all the items from a given queue in a specific time period.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class QueueProcessingRecordDto {
  @JsonProperty("QueueDefinitionId")
  private Long queueDefinitionId = null;

  @JsonProperty("UiQueueMetadata")
  private QueueDefinitionDto uiQueueMetadata = null;

  @JsonProperty("ProcessingTime")
  private OffsetDateTime processingTime = null;

  /**
   * The aggregation period used in the report.
   */
  public enum ReportTypeEnum {
    ALL("All"),
    MINUTE("Minute"),
    HOUR("Hour"),
    DAY("Day");

    private String value;

    ReportTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ReportTypeEnum fromValue(String input) {
      for (ReportTypeEnum b : ReportTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("ReportType")
  private ReportTypeEnum reportType = null;

  @JsonProperty("NumberOfRemainingTransactions")
  private Integer numberOfRemainingTransactions = null;

  @JsonProperty("NumberOfInProgressTransactions")
  private Integer numberOfInProgressTransactions = null;

  @JsonProperty("NumberOfApplicationExceptions")
  private Integer numberOfApplicationExceptions = null;

  @JsonProperty("NumberOfBusinessExceptions")
  private Integer numberOfBusinessExceptions = null;

  @JsonProperty("NumberOfSuccessfulTransactions")
  private Integer numberOfSuccessfulTransactions = null;

  @JsonProperty("NumberOfRetriedItems")
  private Integer numberOfRetriedItems = null;

  @JsonProperty("ApplicationExceptionsProcessingTime")
  private BigDecimal applicationExceptionsProcessingTime = null;

  @JsonProperty("BusinessExceptionsProcessingTime")
  private BigDecimal businessExceptionsProcessingTime = null;

  @JsonProperty("SuccessfulTransactionsProcessingTime")
  private BigDecimal successfulTransactionsProcessingTime = null;

  @JsonProperty("TotalNumberOfTransactions")
  private Integer totalNumberOfTransactions = null;

  @JsonProperty("TenantId")
  private Integer tenantId = null;

  @JsonProperty("Id")
  private Long id = null;

  public QueueProcessingRecordDto queueDefinitionId(Long queueDefinitionId) {
    this.queueDefinitionId = queueDefinitionId;
    return this;
  }

   /**
   * The Id of the queue for which the report is done.
   * @return queueDefinitionId
  **/
  public Long getQueueDefinitionId() {
    return queueDefinitionId;
  }

  public void setQueueDefinitionId(Long queueDefinitionId) {
    this.queueDefinitionId = queueDefinitionId;
  }

  public QueueProcessingRecordDto uiQueueMetadata(QueueDefinitionDto uiQueueMetadata) {
    this.uiQueueMetadata = uiQueueMetadata;
    return this;
  }

   /**
   * Get uiQueueMetadata
   * @return uiQueueMetadata
  **/
  public QueueDefinitionDto getUiQueueMetadata() {
    return uiQueueMetadata;
  }

  public void setUiQueueMetadata(QueueDefinitionDto uiQueueMetadata) {
    this.uiQueueMetadata = uiQueueMetadata;
  }

  public QueueProcessingRecordDto processingTime(OffsetDateTime processingTime) {
    this.processingTime = processingTime;
    return this;
  }

   /**
   * The date and time when the report is computed.
   * @return processingTime
  **/
  public OffsetDateTime getProcessingTime() {
    return processingTime;
  }

  public void setProcessingTime(OffsetDateTime processingTime) {
    this.processingTime = processingTime;
  }

  public QueueProcessingRecordDto reportType(ReportTypeEnum reportType) {
    this.reportType = reportType;
    return this;
  }

   /**
   * The aggregation period used in the report.
   * @return reportType
  **/
  public ReportTypeEnum getReportType() {
    return reportType;
  }

  public void setReportType(ReportTypeEnum reportType) {
    this.reportType = reportType;
  }

  public QueueProcessingRecordDto numberOfRemainingTransactions(Integer numberOfRemainingTransactions) {
    this.numberOfRemainingTransactions = numberOfRemainingTransactions;
    return this;
  }

   /**
   * The number of unprocessed (new) items.
   * @return numberOfRemainingTransactions
  **/
  public Integer getNumberOfRemainingTransactions() {
    return numberOfRemainingTransactions;
  }

  public void setNumberOfRemainingTransactions(Integer numberOfRemainingTransactions) {
    this.numberOfRemainingTransactions = numberOfRemainingTransactions;
  }

  public QueueProcessingRecordDto numberOfInProgressTransactions(Integer numberOfInProgressTransactions) {
    this.numberOfInProgressTransactions = numberOfInProgressTransactions;
    return this;
  }

   /**
   * The number of items in progress.
   * @return numberOfInProgressTransactions
  **/
  public Integer getNumberOfInProgressTransactions() {
    return numberOfInProgressTransactions;
  }

  public void setNumberOfInProgressTransactions(Integer numberOfInProgressTransactions) {
    this.numberOfInProgressTransactions = numberOfInProgressTransactions;
  }

  public QueueProcessingRecordDto numberOfApplicationExceptions(Integer numberOfApplicationExceptions) {
    this.numberOfApplicationExceptions = numberOfApplicationExceptions;
    return this;
  }

   /**
   * The total number of application exceptions thrown while processing queue items in the given time period.
   * @return numberOfApplicationExceptions
  **/
  public Integer getNumberOfApplicationExceptions() {
    return numberOfApplicationExceptions;
  }

  public void setNumberOfApplicationExceptions(Integer numberOfApplicationExceptions) {
    this.numberOfApplicationExceptions = numberOfApplicationExceptions;
  }

  public QueueProcessingRecordDto numberOfBusinessExceptions(Integer numberOfBusinessExceptions) {
    this.numberOfBusinessExceptions = numberOfBusinessExceptions;
    return this;
  }

   /**
   * The total number of business exceptions thrown while processing queue items in the given time period.
   * @return numberOfBusinessExceptions
  **/
  public Integer getNumberOfBusinessExceptions() {
    return numberOfBusinessExceptions;
  }

  public void setNumberOfBusinessExceptions(Integer numberOfBusinessExceptions) {
    this.numberOfBusinessExceptions = numberOfBusinessExceptions;
  }

  public QueueProcessingRecordDto numberOfSuccessfulTransactions(Integer numberOfSuccessfulTransactions) {
    this.numberOfSuccessfulTransactions = numberOfSuccessfulTransactions;
    return this;
  }

   /**
   * The total number of successfully processed queue items in the given time period.
   * @return numberOfSuccessfulTransactions
  **/
  public Integer getNumberOfSuccessfulTransactions() {
    return numberOfSuccessfulTransactions;
  }

  public void setNumberOfSuccessfulTransactions(Integer numberOfSuccessfulTransactions) {
    this.numberOfSuccessfulTransactions = numberOfSuccessfulTransactions;
  }

  public QueueProcessingRecordDto numberOfRetriedItems(Integer numberOfRetriedItems) {
    this.numberOfRetriedItems = numberOfRetriedItems;
    return this;
  }

   /**
   * The total number of processing retries occurred in the given time period.
   * @return numberOfRetriedItems
  **/
  public Integer getNumberOfRetriedItems() {
    return numberOfRetriedItems;
  }

  public void setNumberOfRetriedItems(Integer numberOfRetriedItems) {
    this.numberOfRetriedItems = numberOfRetriedItems;
  }

  public QueueProcessingRecordDto applicationExceptionsProcessingTime(BigDecimal applicationExceptionsProcessingTime) {
    this.applicationExceptionsProcessingTime = applicationExceptionsProcessingTime;
    return this;
  }

   /**
   * The total number of seconds spent processing queue items that failed with application exception in the given time period.
   * @return applicationExceptionsProcessingTime
  **/
  public BigDecimal getApplicationExceptionsProcessingTime() {
    return applicationExceptionsProcessingTime;
  }

  public void setApplicationExceptionsProcessingTime(BigDecimal applicationExceptionsProcessingTime) {
    this.applicationExceptionsProcessingTime = applicationExceptionsProcessingTime;
  }

  public QueueProcessingRecordDto businessExceptionsProcessingTime(BigDecimal businessExceptionsProcessingTime) {
    this.businessExceptionsProcessingTime = businessExceptionsProcessingTime;
    return this;
  }

   /**
   * The total number of seconds spent processing queue items that failed with business exception in the given time period.
   * @return businessExceptionsProcessingTime
  **/
  public BigDecimal getBusinessExceptionsProcessingTime() {
    return businessExceptionsProcessingTime;
  }

  public void setBusinessExceptionsProcessingTime(BigDecimal businessExceptionsProcessingTime) {
    this.businessExceptionsProcessingTime = businessExceptionsProcessingTime;
  }

  public QueueProcessingRecordDto successfulTransactionsProcessingTime(BigDecimal successfulTransactionsProcessingTime) {
    this.successfulTransactionsProcessingTime = successfulTransactionsProcessingTime;
    return this;
  }

   /**
   * The total number of seconds spent processing successful queue items in the given time period.
   * @return successfulTransactionsProcessingTime
  **/
  public BigDecimal getSuccessfulTransactionsProcessingTime() {
    return successfulTransactionsProcessingTime;
  }

  public void setSuccessfulTransactionsProcessingTime(BigDecimal successfulTransactionsProcessingTime) {
    this.successfulTransactionsProcessingTime = successfulTransactionsProcessingTime;
  }

  public QueueProcessingRecordDto totalNumberOfTransactions(Integer totalNumberOfTransactions) {
    this.totalNumberOfTransactions = totalNumberOfTransactions;
    return this;
  }

   /**
   * The total number of item processing transactions, both failed and successful.
   * @return totalNumberOfTransactions
  **/
  public Integer getTotalNumberOfTransactions() {
    return totalNumberOfTransactions;
  }

  public void setTotalNumberOfTransactions(Integer totalNumberOfTransactions) {
    this.totalNumberOfTransactions = totalNumberOfTransactions;
  }

  public QueueProcessingRecordDto tenantId(Integer tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * The Id of the queue tenant.
   * @return tenantId
  **/
  public Integer getTenantId() {
    return tenantId;
  }

  public void setTenantId(Integer tenantId) {
    this.tenantId = tenantId;
  }

  public QueueProcessingRecordDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueueProcessingRecordDto queueProcessingRecordDto = (QueueProcessingRecordDto) o;
    return Objects.equals(this.queueDefinitionId, queueProcessingRecordDto.queueDefinitionId) &&
        Objects.equals(this.uiQueueMetadata, queueProcessingRecordDto.uiQueueMetadata) &&
        Objects.equals(this.processingTime, queueProcessingRecordDto.processingTime) &&
        Objects.equals(this.reportType, queueProcessingRecordDto.reportType) &&
        Objects.equals(this.numberOfRemainingTransactions, queueProcessingRecordDto.numberOfRemainingTransactions) &&
        Objects.equals(this.numberOfInProgressTransactions, queueProcessingRecordDto.numberOfInProgressTransactions) &&
        Objects.equals(this.numberOfApplicationExceptions, queueProcessingRecordDto.numberOfApplicationExceptions) &&
        Objects.equals(this.numberOfBusinessExceptions, queueProcessingRecordDto.numberOfBusinessExceptions) &&
        Objects.equals(this.numberOfSuccessfulTransactions, queueProcessingRecordDto.numberOfSuccessfulTransactions) &&
        Objects.equals(this.numberOfRetriedItems, queueProcessingRecordDto.numberOfRetriedItems) &&
        Objects.equals(this.applicationExceptionsProcessingTime, queueProcessingRecordDto.applicationExceptionsProcessingTime) &&
        Objects.equals(this.businessExceptionsProcessingTime, queueProcessingRecordDto.businessExceptionsProcessingTime) &&
        Objects.equals(this.successfulTransactionsProcessingTime, queueProcessingRecordDto.successfulTransactionsProcessingTime) &&
        Objects.equals(this.totalNumberOfTransactions, queueProcessingRecordDto.totalNumberOfTransactions) &&
        Objects.equals(this.tenantId, queueProcessingRecordDto.tenantId) &&
        Objects.equals(this.id, queueProcessingRecordDto.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(queueDefinitionId, uiQueueMetadata, processingTime, reportType, numberOfRemainingTransactions, numberOfInProgressTransactions, numberOfApplicationExceptions, numberOfBusinessExceptions, numberOfSuccessfulTransactions, numberOfRetriedItems, applicationExceptionsProcessingTime, businessExceptionsProcessingTime, successfulTransactionsProcessingTime, totalNumberOfTransactions, tenantId, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueueProcessingRecordDto {\n");
    
    sb.append("    queueDefinitionId: ").append(toIndentedString(queueDefinitionId)).append("\n");
    sb.append("    uiQueueMetadata: ").append(toIndentedString(uiQueueMetadata)).append("\n");
    sb.append("    processingTime: ").append(toIndentedString(processingTime)).append("\n");
    sb.append("    reportType: ").append(toIndentedString(reportType)).append("\n");
    sb.append("    numberOfRemainingTransactions: ").append(toIndentedString(numberOfRemainingTransactions)).append("\n");
    sb.append("    numberOfInProgressTransactions: ").append(toIndentedString(numberOfInProgressTransactions)).append("\n");
    sb.append("    numberOfApplicationExceptions: ").append(toIndentedString(numberOfApplicationExceptions)).append("\n");
    sb.append("    numberOfBusinessExceptions: ").append(toIndentedString(numberOfBusinessExceptions)).append("\n");
    sb.append("    numberOfSuccessfulTransactions: ").append(toIndentedString(numberOfSuccessfulTransactions)).append("\n");
    sb.append("    numberOfRetriedItems: ").append(toIndentedString(numberOfRetriedItems)).append("\n");
    sb.append("    applicationExceptionsProcessingTime: ").append(toIndentedString(applicationExceptionsProcessingTime)).append("\n");
    sb.append("    businessExceptionsProcessingTime: ").append(toIndentedString(businessExceptionsProcessingTime)).append("\n");
    sb.append("    successfulTransactionsProcessingTime: ").append(toIndentedString(successfulTransactionsProcessingTime)).append("\n");
    sb.append("    totalNumberOfTransactions: ").append(toIndentedString(totalNumberOfTransactions)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
