/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.uipath.orchestrator.TestCaseExecutionArgumentsDto;

import java.util.ArrayList;
import java.util.List;
/**
 * ReexecuteTestCasesOptionsDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class ReexecuteTestCasesOptionsDto {
  @JsonProperty("testCaseExecutions")
  private List<TestCaseExecutionArgumentsDto> testCaseExecutions = new ArrayList<>();

  @JsonProperty("robotId")
  private Long robotId = null;

  @JsonProperty("machineId")
  private Long machineId = null;

  @JsonProperty("machineSessionId")
  private Long machineSessionId = null;

  /**
   * Gets or Sets runtimeType
   */
  public enum RuntimeTypeEnum {
    NONPRODUCTION("NonProduction"),
    ATTENDED("Attended"),
    UNATTENDED("Unattended"),
    DEVELOPMENT("Development"),
    STUDIO("Studio"),
    RPADEVELOPER("RpaDeveloper"),
    STUDIOX("StudioX"),
    CITIZENDEVELOPER("CitizenDeveloper"),
    HEADLESS("Headless"),
    STUDIOPRO("StudioPro"),
    RPADEVELOPERPRO("RpaDeveloperPro"),
    TESTAUTOMATION("TestAutomation"),
    AUTOMATIONCLOUD("AutomationCloud"),
    SERVERLESS("Serverless"),
    AUTOMATIONKIT("AutomationKit"),
    SERVERLESSTESTAUTOMATION("ServerlessTestAutomation"),
    AUTOMATIONCLOUDTESTAUTOMATION("AutomationCloudTestAutomation"),
    ATTENDEDSTUDIOWEB("AttendedStudioWeb");

    private String value;

    RuntimeTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static RuntimeTypeEnum fromValue(String input) {
      for (RuntimeTypeEnum b : RuntimeTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("runtimeType")
  private RuntimeTypeEnum runtimeType = null;

  @JsonProperty("enforceExecutionOrder")
  private Boolean enforceExecutionOrder = null;

  public ReexecuteTestCasesOptionsDto testCaseExecutions(List<TestCaseExecutionArgumentsDto> testCaseExecutions) {
    this.testCaseExecutions = testCaseExecutions;
    return this;
  }

  public ReexecuteTestCasesOptionsDto addTestCaseExecutionsItem(TestCaseExecutionArgumentsDto testCaseExecutionsItem) {
    this.testCaseExecutions.add(testCaseExecutionsItem);
    return this;
  }

   /**
   * Get testCaseExecutions
   * @return testCaseExecutions
  **/
  public List<TestCaseExecutionArgumentsDto> getTestCaseExecutions() {
    return testCaseExecutions;
  }

  public void setTestCaseExecutions(List<TestCaseExecutionArgumentsDto> testCaseExecutions) {
    this.testCaseExecutions = testCaseExecutions;
  }

  public ReexecuteTestCasesOptionsDto robotId(Long robotId) {
    this.robotId = robotId;
    return this;
  }

   /**
   * Get robotId
   * @return robotId
  **/
  public Long getRobotId() {
    return robotId;
  }

  public void setRobotId(Long robotId) {
    this.robotId = robotId;
  }

  public ReexecuteTestCasesOptionsDto machineId(Long machineId) {
    this.machineId = machineId;
    return this;
  }

   /**
   * Get machineId
   * @return machineId
  **/
  public Long getMachineId() {
    return machineId;
  }

  public void setMachineId(Long machineId) {
    this.machineId = machineId;
  }

  public ReexecuteTestCasesOptionsDto machineSessionId(Long machineSessionId) {
    this.machineSessionId = machineSessionId;
    return this;
  }

   /**
   * Get machineSessionId
   * @return machineSessionId
  **/
  public Long getMachineSessionId() {
    return machineSessionId;
  }

  public void setMachineSessionId(Long machineSessionId) {
    this.machineSessionId = machineSessionId;
  }

  public ReexecuteTestCasesOptionsDto runtimeType(RuntimeTypeEnum runtimeType) {
    this.runtimeType = runtimeType;
    return this;
  }

   /**
   * Get runtimeType
   * @return runtimeType
  **/
  public RuntimeTypeEnum getRuntimeType() {
    return runtimeType;
  }

  public void setRuntimeType(RuntimeTypeEnum runtimeType) {
    this.runtimeType = runtimeType;
  }

  public ReexecuteTestCasesOptionsDto enforceExecutionOrder(Boolean enforceExecutionOrder) {
    this.enforceExecutionOrder = enforceExecutionOrder;
    return this;
  }

   /**
   * Get enforceExecutionOrder
   * @return enforceExecutionOrder
  **/
  public Boolean isEnforceExecutionOrder() {
    return enforceExecutionOrder;
  }

  public void setEnforceExecutionOrder(Boolean enforceExecutionOrder) {
    this.enforceExecutionOrder = enforceExecutionOrder;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReexecuteTestCasesOptionsDto reexecuteTestCasesOptionsDto = (ReexecuteTestCasesOptionsDto) o;
    return Objects.equals(this.testCaseExecutions, reexecuteTestCasesOptionsDto.testCaseExecutions) &&
        Objects.equals(this.robotId, reexecuteTestCasesOptionsDto.robotId) &&
        Objects.equals(this.machineId, reexecuteTestCasesOptionsDto.machineId) &&
        Objects.equals(this.machineSessionId, reexecuteTestCasesOptionsDto.machineSessionId) &&
        Objects.equals(this.runtimeType, reexecuteTestCasesOptionsDto.runtimeType) &&
        Objects.equals(this.enforceExecutionOrder, reexecuteTestCasesOptionsDto.enforceExecutionOrder);
  }

  @Override
  public int hashCode() {
    return Objects.hash(testCaseExecutions, robotId, machineId, machineSessionId, runtimeType, enforceExecutionOrder);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReexecuteTestCasesOptionsDto {\n");
    
    sb.append("    testCaseExecutions: ").append(toIndentedString(testCaseExecutions)).append("\n");
    sb.append("    robotId: ").append(toIndentedString(robotId)).append("\n");
    sb.append("    machineId: ").append(toIndentedString(machineId)).append("\n");
    sb.append("    machineSessionId: ").append(toIndentedString(machineSessionId)).append("\n");
    sb.append("    runtimeType: ").append(toIndentedString(runtimeType)).append("\n");
    sb.append("    enforceExecutionOrder: ").append(toIndentedString(enforceExecutionOrder)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
