/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.uipath.orchestrator.NameValueDto;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * ResourceOverwriteDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class ResourceOverwriteDto {
  @JsonProperty("properties2")
  private List<NameValueDto> properties2 = null;

  /**
   * The type of the resource to be overwritten
   */
  public enum ResourceTypeEnum {
    UNKNOWN("Unknown"),
    QUEUE("Queue"),
    ASSET("Asset"),
    BUCKET("Bucket"),
    PROCESS("Process"),
    TASKCATALOG("TaskCatalog"),
    ENTITY("Entity"),
    CONNECTION("Connection"),
    TIMETRIGGER("TimeTrigger"),
    EVENTTRIGGER("EventTrigger"),
    QUEUETRIGGER("QueueTrigger"),
    APPSTRIGGER("AppsTrigger"),
    PROPERTY("Property");

    private String value;

    ResourceTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ResourceTypeEnum fromValue(String input) {
      for (ResourceTypeEnum b : ResourceTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("resourceType")
  private ResourceTypeEnum resourceType = null;

  @JsonProperty("resourceKey")
  private String resourceKey = null;

  @JsonProperty("entityId")
  private String entityId = null;

  @JsonProperty("properties")
  private Map<String, Object> properties = null;

  @JsonProperty("entityDisplayName")
  private String entityDisplayName = null;

  @JsonProperty("entityFolderId")
  private Long entityFolderId = null;

  public ResourceOverwriteDto properties2(List<NameValueDto> properties2) {
    this.properties2 = properties2;
    return this;
  }

  public ResourceOverwriteDto addProperties2Item(NameValueDto properties2Item) {
    if (this.properties2 == null) {
      this.properties2 = new ArrayList<>();
    }
    this.properties2.add(properties2Item);
    return this;
  }

   /**
   * Get properties2
   * @return properties2
  **/
  public List<NameValueDto> getProperties2() {
    return properties2;
  }

  public void setProperties2(List<NameValueDto> properties2) {
    this.properties2 = properties2;
  }

  public ResourceOverwriteDto resourceType(ResourceTypeEnum resourceType) {
    this.resourceType = resourceType;
    return this;
  }

   /**
   * The type of the resource to be overwritten
   * @return resourceType
  **/
  public ResourceTypeEnum getResourceType() {
    return resourceType;
  }

  public void setResourceType(ResourceTypeEnum resourceType) {
    this.resourceType = resourceType;
  }

  public ResourceOverwriteDto resourceKey(String resourceKey) {
    this.resourceKey = resourceKey;
    return this;
  }

   /**
   * The key of the resource to be overwritten
   * @return resourceKey
  **/
  public String getResourceKey() {
    return resourceKey;
  }

  public void setResourceKey(String resourceKey) {
    this.resourceKey = resourceKey;
  }

  public ResourceOverwriteDto entityId(String entityId) {
    this.entityId = entityId;
    return this;
  }

   /**
   * The id of the entity that overwrites the resource (e.g. ConnectionId)
   * @return entityId
  **/
  public String getEntityId() {
    return entityId;
  }

  public void setEntityId(String entityId) {
    this.entityId = entityId;
  }

  public ResourceOverwriteDto properties(Map<String, Object> properties) {
    this.properties = properties;
    return this;
  }

  public ResourceOverwriteDto putPropertiesItem(String key, Object propertiesItem) {
    if (this.properties == null) {
      this.properties = new HashMap<>();
    }
    this.properties.put(key, propertiesItem);
    return this;
  }

   /**
   * Custom property overwrites
   * @return properties
  **/
  public Map<String, Object> getProperties() {
    return properties;
  }

  public void setProperties(Map<String, Object> properties) {
    this.properties = properties;
  }

  public ResourceOverwriteDto entityDisplayName(String entityDisplayName) {
    this.entityDisplayName = entityDisplayName;
    return this;
  }

   /**
   * The name of the entity that overwrites the resource (e.g. ConnectionName)
   * @return entityDisplayName
  **/
  public String getEntityDisplayName() {
    return entityDisplayName;
  }

  public void setEntityDisplayName(String entityDisplayName) {
    this.entityDisplayName = entityDisplayName;
  }

  public ResourceOverwriteDto entityFolderId(Long entityFolderId) {
    this.entityFolderId = entityFolderId;
    return this;
  }

   /**
   * Get entityFolderId
   * @return entityFolderId
  **/
  public Long getEntityFolderId() {
    return entityFolderId;
  }

  public void setEntityFolderId(Long entityFolderId) {
    this.entityFolderId = entityFolderId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceOverwriteDto resourceOverwriteDto = (ResourceOverwriteDto) o;
    return Objects.equals(this.properties2, resourceOverwriteDto.properties2) &&
        Objects.equals(this.resourceType, resourceOverwriteDto.resourceType) &&
        Objects.equals(this.resourceKey, resourceOverwriteDto.resourceKey) &&
        Objects.equals(this.entityId, resourceOverwriteDto.entityId) &&
        Objects.equals(this.properties, resourceOverwriteDto.properties) &&
        Objects.equals(this.entityDisplayName, resourceOverwriteDto.entityDisplayName) &&
        Objects.equals(this.entityFolderId, resourceOverwriteDto.entityFolderId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(properties2, resourceType, resourceKey, entityId, properties, entityDisplayName, entityFolderId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceOverwriteDto {\n");
    
    sb.append("    properties2: ").append(toIndentedString(properties2)).append("\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    resourceKey: ").append(toIndentedString(resourceKey)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    entityDisplayName: ").append(toIndentedString(entityDisplayName)).append("\n");
    sb.append("    entityFolderId: ").append(toIndentedString(entityFolderId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
