/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.uipath.orchestrator.CredentialsConnectionData;
import com.uipath.orchestrator.CustomKeyValuePair;

import java.util.ArrayList;
import java.util.List;
/**
 * A robot asset stores the information of a per robot asset for a specific robot, without specifying the robot.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class RobotAssetDto {
  @JsonProperty("Name")
  private String name = null;

  /**
   * Defines the type of value stored by the asset.
   */
  public enum ValueTypeEnum {
    DBCONNECTIONSTRING("DBConnectionString"),
    HTTPCONNECTIONSTRING("HttpConnectionString"),
    TEXT("Text"),
    BOOL("Bool"),
    INTEGER("Integer"),
    CREDENTIAL("Credential"),
    WINDOWSCREDENTIAL("WindowsCredential"),
    KEYVALUELIST("KeyValueList");

    private String value;

    ValueTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ValueTypeEnum fromValue(String input) {
      for (ValueTypeEnum b : ValueTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("ValueType")
  private ValueTypeEnum valueType = null;

  @JsonProperty("StringValue")
  private String stringValue = null;

  @JsonProperty("BoolValue")
  private Boolean boolValue = null;

  @JsonProperty("IntValue")
  private Integer intValue = null;

  @JsonProperty("CredentialUsername")
  private String credentialUsername = null;

  @JsonProperty("CredentialPassword")
  private String credentialPassword = null;

  @JsonProperty("ExternalName")
  private String externalName = null;

  @JsonProperty("CredentialStoreId")
  private Long credentialStoreId = null;

  @JsonProperty("KeyValueList")
  private List<CustomKeyValuePair> keyValueList = null;

  @JsonProperty("ConnectionData")
  private CredentialsConnectionData connectionData = null;

  @JsonProperty("Id")
  private Long id = null;

  public RobotAssetDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The asset name.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RobotAssetDto valueType(ValueTypeEnum valueType) {
    this.valueType = valueType;
    return this;
  }

   /**
   * Defines the type of value stored by the asset.
   * @return valueType
  **/
  public ValueTypeEnum getValueType() {
    return valueType;
  }

  public void setValueType(ValueTypeEnum valueType) {
    this.valueType = valueType;
  }

  public RobotAssetDto stringValue(String stringValue) {
    this.stringValue = stringValue;
    return this;
  }

   /**
   * The value of the asset when the value type is Text. Empty when the value type is not Text.
   * @return stringValue
  **/
  public String getStringValue() {
    return stringValue;
  }

  public void setStringValue(String stringValue) {
    this.stringValue = stringValue;
  }

  public RobotAssetDto boolValue(Boolean boolValue) {
    this.boolValue = boolValue;
    return this;
  }

   /**
   * The value of the asset when the value type is Bool. False when the value type is not Bool.
   * @return boolValue
  **/
  public Boolean isBoolValue() {
    return boolValue;
  }

  public void setBoolValue(Boolean boolValue) {
    this.boolValue = boolValue;
  }

  public RobotAssetDto intValue(Integer intValue) {
    this.intValue = intValue;
    return this;
  }

   /**
   * The value of the asset when the value type is Integer. 0 when the value type is not Integer.
   * @return intValue
  **/
  public Integer getIntValue() {
    return intValue;
  }

  public void setIntValue(Integer intValue) {
    this.intValue = intValue;
  }

  public RobotAssetDto credentialUsername(String credentialUsername) {
    this.credentialUsername = credentialUsername;
    return this;
  }

   /**
   * The user name when the value type is Credential. Empty when the value type is not Credential.
   * @return credentialUsername
  **/
  public String getCredentialUsername() {
    return credentialUsername;
  }

  public void setCredentialUsername(String credentialUsername) {
    this.credentialUsername = credentialUsername;
  }

  public RobotAssetDto credentialPassword(String credentialPassword) {
    this.credentialPassword = credentialPassword;
    return this;
  }

   /**
   * The password when the value type is Credential. Empty when the value type is not Credential.
   * @return credentialPassword
  **/
  public String getCredentialPassword() {
    return credentialPassword;
  }

  public void setCredentialPassword(String credentialPassword) {
    this.credentialPassword = credentialPassword;
  }

  public RobotAssetDto externalName(String externalName) {
    this.externalName = externalName;
    return this;
  }

   /**
   * Contains the value of the key in the external store used to store the credentials.
   * @return externalName
  **/
  public String getExternalName() {
    return externalName;
  }

  public void setExternalName(String externalName) {
    this.externalName = externalName;
  }

  public RobotAssetDto credentialStoreId(Long credentialStoreId) {
    this.credentialStoreId = credentialStoreId;
    return this;
  }

   /**
   * The Credential Store used to store the credentials.
   * @return credentialStoreId
  **/
  public Long getCredentialStoreId() {
    return credentialStoreId;
  }

  public void setCredentialStoreId(Long credentialStoreId) {
    this.credentialStoreId = credentialStoreId;
  }

  public RobotAssetDto keyValueList(List<CustomKeyValuePair> keyValueList) {
    this.keyValueList = keyValueList;
    return this;
  }

  public RobotAssetDto addKeyValueListItem(CustomKeyValuePair keyValueListItem) {
    if (this.keyValueList == null) {
      this.keyValueList = new ArrayList<>();
    }
    this.keyValueList.add(keyValueListItem);
    return this;
  }

   /**
   * A collection of key value pairs when the type is KeyValueList. Empty when the value type is not KeyValueList.
   * @return keyValueList
  **/
  public List<CustomKeyValuePair> getKeyValueList() {
    return keyValueList;
  }

  public void setKeyValueList(List<CustomKeyValuePair> keyValueList) {
    this.keyValueList = keyValueList;
  }

  public RobotAssetDto connectionData(CredentialsConnectionData connectionData) {
    this.connectionData = connectionData;
    return this;
  }

   /**
   * Get connectionData
   * @return connectionData
  **/
  public CredentialsConnectionData getConnectionData() {
    return connectionData;
  }

  public void setConnectionData(CredentialsConnectionData connectionData) {
    this.connectionData = connectionData;
  }

  public RobotAssetDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RobotAssetDto robotAssetDto = (RobotAssetDto) o;
    return Objects.equals(this.name, robotAssetDto.name) &&
        Objects.equals(this.valueType, robotAssetDto.valueType) &&
        Objects.equals(this.stringValue, robotAssetDto.stringValue) &&
        Objects.equals(this.boolValue, robotAssetDto.boolValue) &&
        Objects.equals(this.intValue, robotAssetDto.intValue) &&
        Objects.equals(this.credentialUsername, robotAssetDto.credentialUsername) &&
        Objects.equals(this.credentialPassword, robotAssetDto.credentialPassword) &&
        Objects.equals(this.externalName, robotAssetDto.externalName) &&
        Objects.equals(this.credentialStoreId, robotAssetDto.credentialStoreId) &&
        Objects.equals(this.keyValueList, robotAssetDto.keyValueList) &&
        Objects.equals(this.connectionData, robotAssetDto.connectionData) &&
        Objects.equals(this.id, robotAssetDto.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, valueType, stringValue, boolValue, intValue, credentialUsername, credentialPassword, externalName, credentialStoreId, keyValueList, connectionData, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RobotAssetDto {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    valueType: ").append(toIndentedString(valueType)).append("\n");
    sb.append("    stringValue: ").append(toIndentedString(stringValue)).append("\n");
    sb.append("    boolValue: ").append(toIndentedString(boolValue)).append("\n");
    sb.append("    intValue: ").append(toIndentedString(intValue)).append("\n");
    sb.append("    credentialUsername: ").append(toIndentedString(credentialUsername)).append("\n");
    sb.append("    credentialPassword: ").append(toIndentedString(credentialPassword)).append("\n");
    sb.append("    externalName: ").append(toIndentedString(externalName)).append("\n");
    sb.append("    credentialStoreId: ").append(toIndentedString(credentialStoreId)).append("\n");
    sb.append("    keyValueList: ").append(toIndentedString(keyValueList)).append("\n");
    sb.append("    connectionData: ").append(toIndentedString(connectionData)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
