/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SessionMaintenanceModeParameters
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class SessionMaintenanceModeParameters {
  @JsonProperty("sessionId")
  private Long sessionId = null;

  /**
   * Gets or Sets maintenanceMode
   */
  public enum MaintenanceModeEnum {
    DEFAULT("Default"),
    ENABLED("Enabled");

    private String value;

    MaintenanceModeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static MaintenanceModeEnum fromValue(String input) {
      for (MaintenanceModeEnum b : MaintenanceModeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("maintenanceMode")
  private MaintenanceModeEnum maintenanceMode = null;

  /**
   * Gets or Sets stopJobsStrategy
   */
  public enum StopJobsStrategyEnum {
    SOFTSTOP("SoftStop"),
    KILL("Kill");

    private String value;

    StopJobsStrategyEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StopJobsStrategyEnum fromValue(String input) {
      for (StopJobsStrategyEnum b : StopJobsStrategyEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("stopJobsStrategy")
  private StopJobsStrategyEnum stopJobsStrategy = null;

  public SessionMaintenanceModeParameters sessionId(Long sessionId) {
    this.sessionId = sessionId;
    return this;
  }

   /**
   * Get sessionId
   * @return sessionId
  **/
  public Long getSessionId() {
    return sessionId;
  }

  public void setSessionId(Long sessionId) {
    this.sessionId = sessionId;
  }

  public SessionMaintenanceModeParameters maintenanceMode(MaintenanceModeEnum maintenanceMode) {
    this.maintenanceMode = maintenanceMode;
    return this;
  }

   /**
   * Get maintenanceMode
   * @return maintenanceMode
  **/
  public MaintenanceModeEnum getMaintenanceMode() {
    return maintenanceMode;
  }

  public void setMaintenanceMode(MaintenanceModeEnum maintenanceMode) {
    this.maintenanceMode = maintenanceMode;
  }

  public SessionMaintenanceModeParameters stopJobsStrategy(StopJobsStrategyEnum stopJobsStrategy) {
    this.stopJobsStrategy = stopJobsStrategy;
    return this;
  }

   /**
   * Get stopJobsStrategy
   * @return stopJobsStrategy
  **/
  public StopJobsStrategyEnum getStopJobsStrategy() {
    return stopJobsStrategy;
  }

  public void setStopJobsStrategy(StopJobsStrategyEnum stopJobsStrategy) {
    this.stopJobsStrategy = stopJobsStrategy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionMaintenanceModeParameters sessionMaintenanceModeParameters = (SessionMaintenanceModeParameters) o;
    return Objects.equals(this.sessionId, sessionMaintenanceModeParameters.sessionId) &&
        Objects.equals(this.maintenanceMode, sessionMaintenanceModeParameters.maintenanceMode) &&
        Objects.equals(this.stopJobsStrategy, sessionMaintenanceModeParameters.stopJobsStrategy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessionId, maintenanceMode, stopJobsStrategy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionMaintenanceModeParameters {\n");
    
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    maintenanceMode: ").append(toIndentedString(maintenanceMode)).append("\n");
    sb.append("    stopJobsStrategy: ").append(toIndentedString(stopJobsStrategy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
