/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
import java.util.UUID;
/**
 * SessionEventData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class SessionEventData {
  @JsonProperty("SessionId")
  private Long sessionId = null;

  @JsonProperty("RobotId")
  private Long robotId = null;

  @JsonProperty("MachineId")
  private Long machineId = null;

  @JsonProperty("MachineKey")
  private UUID machineKey = null;

  @JsonProperty("HostMachineName")
  private String hostMachineName = null;

  @JsonProperty("ServiceUsername")
  private String serviceUsername = null;

  /**
   * Gets or Sets state
   */
  public enum StateEnum {
    AVAILABLE("Available"),
    BUSY("Busy"),
    DISCONNECTED("Disconnected"),
    UNKNOWN("Unknown");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StateEnum fromValue(String input) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("State")
  private StateEnum state = null;

  @JsonProperty("ReportingTime")
  private OffsetDateTime reportingTime = null;

  @JsonProperty("IsUnresponsive")
  private Boolean isUnresponsive = null;

  /**
   * Gets or Sets licenseErrorCode
   */
  public enum LicenseErrorCodeEnum {
    NOLICENSE("NoLicense"),
    LICENSEEXPIRED("LicenseExpired"),
    LICENSEUNREGISTERED("LicenseUnregistered"),
    NOAVAILABLELICENSES("NoAvailableLicenses"),
    NOTENOUGHAVAILABLESLOTS("NotEnoughAvailableSlots"),
    NOTENOUGHRUNTIMELICENSES("NotEnoughRuntimeLicenses"),
    LICENSEISALREADYINUSE("LicenseIsAlreadyInUse"),
    INVALIDREQUEST("InvalidRequest"),
    SLOTSEXCEEDLICENSELIMIT("SlotsExceedLicenseLimit"),
    RUNTIMEDISABLED("RuntimeDisabled"),
    EXTERNALNOTSUPPORTED("ExternalNotSupported"),
    USAGEEXCEEDSLICENSELIMIT("UsageExceedsLicenseLimit"),
    LICENSENOTCOMPATIBLE("LicenseNotCompatible");

    private String value;

    LicenseErrorCodeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static LicenseErrorCodeEnum fromValue(String input) {
      for (LicenseErrorCodeEnum b : LicenseErrorCodeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("LicenseErrorCode")
  private LicenseErrorCodeEnum licenseErrorCode = null;

   /**
   * Get sessionId
   * @return sessionId
  **/
  public Long getSessionId() {
    return sessionId;
  }

   /**
   * Get robotId
   * @return robotId
  **/
  public Long getRobotId() {
    return robotId;
  }

   /**
   * Get machineId
   * @return machineId
  **/
  public Long getMachineId() {
    return machineId;
  }

   /**
   * Get machineKey
   * @return machineKey
  **/
  public UUID getMachineKey() {
    return machineKey;
  }

   /**
   * Get hostMachineName
   * @return hostMachineName
  **/
  public String getHostMachineName() {
    return hostMachineName;
  }

   /**
   * Get serviceUsername
   * @return serviceUsername
  **/
  public String getServiceUsername() {
    return serviceUsername;
  }

   /**
   * Get state
   * @return state
  **/
  public StateEnum getState() {
    return state;
  }

   /**
   * Get reportingTime
   * @return reportingTime
  **/
  public OffsetDateTime getReportingTime() {
    return reportingTime;
  }

   /**
   * Get isUnresponsive
   * @return isUnresponsive
  **/
  public Boolean isIsUnresponsive() {
    return isUnresponsive;
  }

   /**
   * Get licenseErrorCode
   * @return licenseErrorCode
  **/
  public LicenseErrorCodeEnum getLicenseErrorCode() {
    return licenseErrorCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionEventData sessionEventData = (SessionEventData) o;
    return Objects.equals(this.sessionId, sessionEventData.sessionId) &&
        Objects.equals(this.robotId, sessionEventData.robotId) &&
        Objects.equals(this.machineId, sessionEventData.machineId) &&
        Objects.equals(this.machineKey, sessionEventData.machineKey) &&
        Objects.equals(this.hostMachineName, sessionEventData.hostMachineName) &&
        Objects.equals(this.serviceUsername, sessionEventData.serviceUsername) &&
        Objects.equals(this.state, sessionEventData.state) &&
        Objects.equals(this.reportingTime, sessionEventData.reportingTime) &&
        Objects.equals(this.isUnresponsive, sessionEventData.isUnresponsive) &&
        Objects.equals(this.licenseErrorCode, sessionEventData.licenseErrorCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessionId, robotId, machineId, machineKey, hostMachineName, serviceUsername, state, reportingTime, isUnresponsive, licenseErrorCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionEventData {\n");
    
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    robotId: ").append(toIndentedString(robotId)).append("\n");
    sb.append("    machineId: ").append(toIndentedString(machineId)).append("\n");
    sb.append("    machineKey: ").append(toIndentedString(machineKey)).append("\n");
    sb.append("    hostMachineName: ").append(toIndentedString(hostMachineName)).append("\n");
    sb.append("    serviceUsername: ").append(toIndentedString(serviceUsername)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    reportingTime: ").append(toIndentedString(reportingTime)).append("\n");
    sb.append("    isUnresponsive: ").append(toIndentedString(isUnresponsive)).append("\n");
    sb.append("    licenseErrorCode: ").append(toIndentedString(licenseErrorCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
