/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Used to store various predefined application configurations like time zone or account e-mail information.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class SettingsDto {
  @JsonProperty("Name")
  private String name = null;

  @JsonProperty("Value")
  private String value = null;

  /**
   * The scope of a specific setting.
   */
  public enum ScopeEnum {
    APPLICATION("Application"),
    TENANT("Tenant"),
    USER("User"),
    ALL("All");

    private String value;

    ScopeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ScopeEnum fromValue(String input) {
      for (ScopeEnum b : ScopeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("Scope")
  private ScopeEnum scope = null;

  @JsonProperty("Id")
  private String id = null;

  public SettingsDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of a specific setting (e.g. Abp.Net.Mail.DefaultFromAddress).
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SettingsDto value(String value) {
    this.value = value;
    return this;
  }

   /**
   * The value assigned to a specific setting (e.g. admin@mydomain.com).
   * @return value
  **/
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public SettingsDto scope(ScopeEnum scope) {
    this.scope = scope;
    return this;
  }

   /**
   * The scope of a specific setting.
   * @return scope
  **/
  public ScopeEnum getScope() {
    return scope;
  }

  public void setScope(ScopeEnum scope) {
    this.scope = scope;
  }

  public SettingsDto id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SettingsDto settingsDto = (SettingsDto) o;
    return Objects.equals(this.name, settingsDto.name) &&
        Objects.equals(this.value, settingsDto.value) &&
        Objects.equals(this.scope, settingsDto.scope) &&
        Objects.equals(this.id, settingsDto.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, value, scope, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SettingsDto {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
