/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.uipath.orchestrator.SimpleMachineDto;
import com.uipath.orchestrator.SimpleReleaseEventDto;
import com.uipath.orchestrator.SimpleRobotEventDto;

import java.time.OffsetDateTime;
import java.util.UUID;
/**
 * SimpleJobEventDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class SimpleJobEventDto {
  @JsonProperty("Id")
  private Long id = null;

  @JsonProperty("Key")
  private UUID key = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    UNATTENDED("Unattended"),
    ATTENDED("Attended"),
    SERVERLESSGENERIC("ServerlessGeneric");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("Type")
  private TypeEnum type = null;

  /**
   * Gets or Sets state
   */
  public enum StateEnum {
    PENDING("Pending"),
    RUNNING("Running"),
    STOPPING("Stopping"),
    TERMINATING("Terminating"),
    FAULTED("Faulted"),
    SUCCESSFUL("Successful"),
    STOPPED("Stopped"),
    SUSPENDED("Suspended"),
    RESUMED("Resumed");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StateEnum fromValue(String input) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("State")
  private StateEnum state = null;

  @JsonProperty("StartTime")
  private OffsetDateTime startTime = null;

  @JsonProperty("ResumeTime")
  private OffsetDateTime resumeTime = null;

  @JsonProperty("EndTime")
  private OffsetDateTime endTime = null;

  @JsonProperty("CreationTime")
  private OffsetDateTime creationTime = null;

  @JsonProperty("Info")
  private String info = null;

  @JsonProperty("SpecificPriorityValue")
  private Integer specificPriorityValue = null;

  @JsonProperty("ProjectKey")
  private UUID projectKey = null;

  /**
   * Gets or Sets runtimeType
   */
  public enum RuntimeTypeEnum {
    NONPRODUCTION("NonProduction"),
    ATTENDED("Attended"),
    UNATTENDED("Unattended"),
    DEVELOPMENT("Development"),
    STUDIO("Studio"),
    RPADEVELOPER("RpaDeveloper"),
    STUDIOX("StudioX"),
    CITIZENDEVELOPER("CitizenDeveloper"),
    HEADLESS("Headless"),
    STUDIOPRO("StudioPro"),
    RPADEVELOPERPRO("RpaDeveloperPro"),
    TESTAUTOMATION("TestAutomation"),
    AUTOMATIONCLOUD("AutomationCloud"),
    SERVERLESS("Serverless"),
    AUTOMATIONKIT("AutomationKit"),
    SERVERLESSTESTAUTOMATION("ServerlessTestAutomation"),
    AUTOMATIONCLOUDTESTAUTOMATION("AutomationCloudTestAutomation"),
    ATTENDEDSTUDIOWEB("AttendedStudioWeb");

    private String value;

    RuntimeTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static RuntimeTypeEnum fromValue(String input) {
      for (RuntimeTypeEnum b : RuntimeTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("RuntimeType")
  private RuntimeTypeEnum runtimeType = null;

  /**
   * Gets or Sets sourceType
   */
  public enum SourceTypeEnum {
    MANUAL("Manual"),
    SCHEDULE("Schedule"),
    AGENT("Agent"),
    QUEUE("Queue"),
    STUDIOWEB("StudioWeb"),
    INTEGRATIONTRIGGER("IntegrationTrigger"),
    STUDIODESKTOP("StudioDesktop"),
    AUTOMATIONOPSPIPELINES("AutomationOpsPipelines"),
    APPS("Apps"),
    SAP("SAP"),
    HTTPTRIGGER("HttpTrigger"),
    HTTPTRIGGERCALLBACK("HttpTriggerCallback"),
    ROBOTAPI("RobotAPI"),
    COMMANDLINE("CommandLine"),
    ROBOTNETAPI("RobotNetAPI");

    private String value;

    SourceTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SourceTypeEnum fromValue(String input) {
      for (SourceTypeEnum b : SourceTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("SourceType")
  private SourceTypeEnum sourceType = null;

  @JsonProperty("OutputArguments")
  private Object outputArguments = null;

  @JsonProperty("Robot")
  private SimpleRobotEventDto robot = null;

  @JsonProperty("Machine")
  private SimpleMachineDto machine = null;

  @JsonProperty("Release")
  private SimpleReleaseEventDto release = null;

  /**
   * Gets or Sets serverlessJobType
   */
  public enum ServerlessJobTypeEnum {
    ROBOTJOB("RobotJob"),
    STUDIOWEBDESIGNER("StudioWebDesigner"),
    PUBLISHSTUDIOPROJECT("PublishStudioProject");

    private String value;

    ServerlessJobTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ServerlessJobTypeEnum fromValue(String input) {
      for (ServerlessJobTypeEnum b : ServerlessJobTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("ServerlessJobType")
  private ServerlessJobTypeEnum serverlessJobType = null;

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

   /**
   * Get key
   * @return key
  **/
  public UUID getKey() {
    return key;
  }

   /**
   * Get type
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

   /**
   * Get state
   * @return state
  **/
  public StateEnum getState() {
    return state;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  public OffsetDateTime getStartTime() {
    return startTime;
  }

   /**
   * Get resumeTime
   * @return resumeTime
  **/
  public OffsetDateTime getResumeTime() {
    return resumeTime;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  public OffsetDateTime getEndTime() {
    return endTime;
  }

   /**
   * Get creationTime
   * @return creationTime
  **/
  public OffsetDateTime getCreationTime() {
    return creationTime;
  }

   /**
   * Get info
   * @return info
  **/
  public String getInfo() {
    return info;
  }

   /**
   * Get specificPriorityValue
   * @return specificPriorityValue
  **/
  public Integer getSpecificPriorityValue() {
    return specificPriorityValue;
  }

   /**
   * Get projectKey
   * @return projectKey
  **/
  public UUID getProjectKey() {
    return projectKey;
  }

  public SimpleJobEventDto runtimeType(RuntimeTypeEnum runtimeType) {
    this.runtimeType = runtimeType;
    return this;
  }

   /**
   * Get runtimeType
   * @return runtimeType
  **/
  public RuntimeTypeEnum getRuntimeType() {
    return runtimeType;
  }

  public void setRuntimeType(RuntimeTypeEnum runtimeType) {
    this.runtimeType = runtimeType;
  }

   /**
   * Get sourceType
   * @return sourceType
  **/
  public SourceTypeEnum getSourceType() {
    return sourceType;
  }

   /**
   * Get outputArguments
   * @return outputArguments
  **/
  public Object getOutputArguments() {
    return outputArguments;
  }

  public SimpleJobEventDto robot(SimpleRobotEventDto robot) {
    this.robot = robot;
    return this;
  }

   /**
   * Get robot
   * @return robot
  **/
  public SimpleRobotEventDto getRobot() {
    return robot;
  }

  public void setRobot(SimpleRobotEventDto robot) {
    this.robot = robot;
  }

  public SimpleJobEventDto machine(SimpleMachineDto machine) {
    this.machine = machine;
    return this;
  }

   /**
   * Get machine
   * @return machine
  **/
  public SimpleMachineDto getMachine() {
    return machine;
  }

  public void setMachine(SimpleMachineDto machine) {
    this.machine = machine;
  }

  public SimpleJobEventDto release(SimpleReleaseEventDto release) {
    this.release = release;
    return this;
  }

   /**
   * Get release
   * @return release
  **/
  public SimpleReleaseEventDto getRelease() {
    return release;
  }

  public void setRelease(SimpleReleaseEventDto release) {
    this.release = release;
  }

   /**
   * Get serverlessJobType
   * @return serverlessJobType
  **/
  public ServerlessJobTypeEnum getServerlessJobType() {
    return serverlessJobType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SimpleJobEventDto simpleJobEventDto = (SimpleJobEventDto) o;
    return Objects.equals(this.id, simpleJobEventDto.id) &&
        Objects.equals(this.key, simpleJobEventDto.key) &&
        Objects.equals(this.type, simpleJobEventDto.type) &&
        Objects.equals(this.state, simpleJobEventDto.state) &&
        Objects.equals(this.startTime, simpleJobEventDto.startTime) &&
        Objects.equals(this.resumeTime, simpleJobEventDto.resumeTime) &&
        Objects.equals(this.endTime, simpleJobEventDto.endTime) &&
        Objects.equals(this.creationTime, simpleJobEventDto.creationTime) &&
        Objects.equals(this.info, simpleJobEventDto.info) &&
        Objects.equals(this.specificPriorityValue, simpleJobEventDto.specificPriorityValue) &&
        Objects.equals(this.projectKey, simpleJobEventDto.projectKey) &&
        Objects.equals(this.runtimeType, simpleJobEventDto.runtimeType) &&
        Objects.equals(this.sourceType, simpleJobEventDto.sourceType) &&
        Objects.equals(this.outputArguments, simpleJobEventDto.outputArguments) &&
        Objects.equals(this.robot, simpleJobEventDto.robot) &&
        Objects.equals(this.machine, simpleJobEventDto.machine) &&
        Objects.equals(this.release, simpleJobEventDto.release) &&
        Objects.equals(this.serverlessJobType, simpleJobEventDto.serverlessJobType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, key, type, state, startTime, resumeTime, endTime, creationTime, info, specificPriorityValue, projectKey, runtimeType, sourceType, outputArguments, robot, machine, release, serverlessJobType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SimpleJobEventDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    resumeTime: ").append(toIndentedString(resumeTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    sb.append("    specificPriorityValue: ").append(toIndentedString(specificPriorityValue)).append("\n");
    sb.append("    projectKey: ").append(toIndentedString(projectKey)).append("\n");
    sb.append("    runtimeType: ").append(toIndentedString(runtimeType)).append("\n");
    sb.append("    sourceType: ").append(toIndentedString(sourceType)).append("\n");
    sb.append("    outputArguments: ").append(toIndentedString(outputArguments)).append("\n");
    sb.append("    robot: ").append(toIndentedString(robot)).append("\n");
    sb.append("    machine: ").append(toIndentedString(machine)).append("\n");
    sb.append("    release: ").append(toIndentedString(release)).append("\n");
    sb.append("    serverlessJobType: ").append(toIndentedString(serverlessJobType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
