/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
/**
 * Task Definition Properties created for a definition
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class TaskDefinitionPropertiesDto {
  @JsonProperty("version")
  private Integer version = null;

  @JsonProperty("schema")
  private String schema = null;

  @JsonProperty("allowedActions")
  private List<String> allowedActions = null;

  @JsonProperty("allowedActionsForDefinition")
  private String allowedActionsForDefinition = null;

  @JsonProperty("taskDefinitionKey")
  private UUID taskDefinitionKey = null;

  @JsonProperty("creationTime")
  private OffsetDateTime creationTime = null;

  @JsonProperty("creatorUserId")
  private Long creatorUserId = null;

  @JsonProperty("id")
  private Long id = null;

  public TaskDefinitionPropertiesDto version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * Version number of the property set
   * @return version
  **/
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }

  public TaskDefinitionPropertiesDto schema(String schema) {
    this.schema = schema;
    return this;
  }

   /**
   * Field Schema for the definition
   * @return schema
  **/
  public String getSchema() {
    return schema;
  }

  public void setSchema(String schema) {
    this.schema = schema;
  }

  public TaskDefinitionPropertiesDto allowedActions(List<String> allowedActions) {
    this.allowedActions = allowedActions;
    return this;
  }

  public TaskDefinitionPropertiesDto addAllowedActionsItem(String allowedActionsItem) {
    if (this.allowedActions == null) {
      this.allowedActions = new ArrayList<>();
    }
    this.allowedActions.add(allowedActionsItem);
    return this;
  }

   /**
   * Set of allowed actions for this version of Task Definition
   * @return allowedActions
  **/
  public List<String> getAllowedActions() {
    return allowedActions;
  }

  public void setAllowedActions(List<String> allowedActions) {
    this.allowedActions = allowedActions;
  }

  public TaskDefinitionPropertiesDto allowedActionsForDefinition(String allowedActionsForDefinition) {
    this.allowedActionsForDefinition = allowedActionsForDefinition;
    return this;
  }

   /**
   * Get allowedActionsForDefinition
   * @return allowedActionsForDefinition
  **/
  public String getAllowedActionsForDefinition() {
    return allowedActionsForDefinition;
  }

  public void setAllowedActionsForDefinition(String allowedActionsForDefinition) {
    this.allowedActionsForDefinition = allowedActionsForDefinition;
  }

  public TaskDefinitionPropertiesDto taskDefinitionKey(UUID taskDefinitionKey) {
    this.taskDefinitionKey = taskDefinitionKey;
    return this;
  }

   /**
   * Get taskDefinitionKey
   * @return taskDefinitionKey
  **/
  public UUID getTaskDefinitionKey() {
    return taskDefinitionKey;
  }

  public void setTaskDefinitionKey(UUID taskDefinitionKey) {
    this.taskDefinitionKey = taskDefinitionKey;
  }

  public TaskDefinitionPropertiesDto creationTime(OffsetDateTime creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * Get creationTime
   * @return creationTime
  **/
  public OffsetDateTime getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(OffsetDateTime creationTime) {
    this.creationTime = creationTime;
  }

  public TaskDefinitionPropertiesDto creatorUserId(Long creatorUserId) {
    this.creatorUserId = creatorUserId;
    return this;
  }

   /**
   * Get creatorUserId
   * @return creatorUserId
  **/
  public Long getCreatorUserId() {
    return creatorUserId;
  }

  public void setCreatorUserId(Long creatorUserId) {
    this.creatorUserId = creatorUserId;
  }

  public TaskDefinitionPropertiesDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskDefinitionPropertiesDto taskDefinitionPropertiesDto = (TaskDefinitionPropertiesDto) o;
    return Objects.equals(this.version, taskDefinitionPropertiesDto.version) &&
        Objects.equals(this.schema, taskDefinitionPropertiesDto.schema) &&
        Objects.equals(this.allowedActions, taskDefinitionPropertiesDto.allowedActions) &&
        Objects.equals(this.allowedActionsForDefinition, taskDefinitionPropertiesDto.allowedActionsForDefinition) &&
        Objects.equals(this.taskDefinitionKey, taskDefinitionPropertiesDto.taskDefinitionKey) &&
        Objects.equals(this.creationTime, taskDefinitionPropertiesDto.creationTime) &&
        Objects.equals(this.creatorUserId, taskDefinitionPropertiesDto.creatorUserId) &&
        Objects.equals(this.id, taskDefinitionPropertiesDto.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, schema, allowedActions, allowedActionsForDefinition, taskDefinitionKey, creationTime, creatorUserId, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskDefinitionPropertiesDto {\n");
    
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    schema: ").append(toIndentedString(schema)).append("\n");
    sb.append("    allowedActions: ").append(toIndentedString(allowedActions)).append("\n");
    sb.append("    allowedActionsForDefinition: ").append(toIndentedString(allowedActionsForDefinition)).append("\n");
    sb.append("    taskDefinitionKey: ").append(toIndentedString(taskDefinitionKey)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    creatorUserId: ").append(toIndentedString(creatorUserId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
