/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.uipath.orchestrator.TestSetDto;

import java.time.OffsetDateTime;
/**
 * TestSetPackageDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class TestSetPackageDto {
  @JsonProperty("TestSetId")
  private Long testSetId = null;

  @JsonProperty("TestSet")
  private TestSetDto testSet = null;

  @JsonProperty("VersionMask")
  private String versionMask = null;

  @JsonProperty("PackageIdentifier")
  private String packageIdentifier = null;

  @JsonProperty("IncludePrerelease")
  private Boolean includePrerelease = null;

  @JsonProperty("LastModificationTime")
  private OffsetDateTime lastModificationTime = null;

  @JsonProperty("LastModifierUserId")
  private Long lastModifierUserId = null;

  @JsonProperty("CreationTime")
  private OffsetDateTime creationTime = null;

  @JsonProperty("CreatorUserId")
  private Long creatorUserId = null;

  @JsonProperty("Id")
  private Long id = null;

  public TestSetPackageDto testSetId(Long testSetId) {
    this.testSetId = testSetId;
    return this;
  }

   /**
   * Get testSetId
   * @return testSetId
  **/
  public Long getTestSetId() {
    return testSetId;
  }

  public void setTestSetId(Long testSetId) {
    this.testSetId = testSetId;
  }

  public TestSetPackageDto testSet(TestSetDto testSet) {
    this.testSet = testSet;
    return this;
  }

   /**
   * Get testSet
   * @return testSet
  **/
  public TestSetDto getTestSet() {
    return testSet;
  }

  public void setTestSet(TestSetDto testSet) {
    this.testSet = testSet;
  }

  public TestSetPackageDto versionMask(String versionMask) {
    this.versionMask = versionMask;
    return this;
  }

   /**
   * Get versionMask
   * @return versionMask
  **/
  public String getVersionMask() {
    return versionMask;
  }

  public void setVersionMask(String versionMask) {
    this.versionMask = versionMask;
  }

  public TestSetPackageDto packageIdentifier(String packageIdentifier) {
    this.packageIdentifier = packageIdentifier;
    return this;
  }

   /**
   * Get packageIdentifier
   * @return packageIdentifier
  **/
  public String getPackageIdentifier() {
    return packageIdentifier;
  }

  public void setPackageIdentifier(String packageIdentifier) {
    this.packageIdentifier = packageIdentifier;
  }

  public TestSetPackageDto includePrerelease(Boolean includePrerelease) {
    this.includePrerelease = includePrerelease;
    return this;
  }

   /**
   * Get includePrerelease
   * @return includePrerelease
  **/
  public Boolean isIncludePrerelease() {
    return includePrerelease;
  }

  public void setIncludePrerelease(Boolean includePrerelease) {
    this.includePrerelease = includePrerelease;
  }

  public TestSetPackageDto lastModificationTime(OffsetDateTime lastModificationTime) {
    this.lastModificationTime = lastModificationTime;
    return this;
  }

   /**
   * Get lastModificationTime
   * @return lastModificationTime
  **/
  public OffsetDateTime getLastModificationTime() {
    return lastModificationTime;
  }

  public void setLastModificationTime(OffsetDateTime lastModificationTime) {
    this.lastModificationTime = lastModificationTime;
  }

  public TestSetPackageDto lastModifierUserId(Long lastModifierUserId) {
    this.lastModifierUserId = lastModifierUserId;
    return this;
  }

   /**
   * Get lastModifierUserId
   * @return lastModifierUserId
  **/
  public Long getLastModifierUserId() {
    return lastModifierUserId;
  }

  public void setLastModifierUserId(Long lastModifierUserId) {
    this.lastModifierUserId = lastModifierUserId;
  }

  public TestSetPackageDto creationTime(OffsetDateTime creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * Get creationTime
   * @return creationTime
  **/
  public OffsetDateTime getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(OffsetDateTime creationTime) {
    this.creationTime = creationTime;
  }

  public TestSetPackageDto creatorUserId(Long creatorUserId) {
    this.creatorUserId = creatorUserId;
    return this;
  }

   /**
   * Get creatorUserId
   * @return creatorUserId
  **/
  public Long getCreatorUserId() {
    return creatorUserId;
  }

  public void setCreatorUserId(Long creatorUserId) {
    this.creatorUserId = creatorUserId;
  }

  public TestSetPackageDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestSetPackageDto testSetPackageDto = (TestSetPackageDto) o;
    return Objects.equals(this.testSetId, testSetPackageDto.testSetId) &&
        Objects.equals(this.testSet, testSetPackageDto.testSet) &&
        Objects.equals(this.versionMask, testSetPackageDto.versionMask) &&
        Objects.equals(this.packageIdentifier, testSetPackageDto.packageIdentifier) &&
        Objects.equals(this.includePrerelease, testSetPackageDto.includePrerelease) &&
        Objects.equals(this.lastModificationTime, testSetPackageDto.lastModificationTime) &&
        Objects.equals(this.lastModifierUserId, testSetPackageDto.lastModifierUserId) &&
        Objects.equals(this.creationTime, testSetPackageDto.creationTime) &&
        Objects.equals(this.creatorUserId, testSetPackageDto.creatorUserId) &&
        Objects.equals(this.id, testSetPackageDto.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(testSetId, testSet, versionMask, packageIdentifier, includePrerelease, lastModificationTime, lastModifierUserId, creationTime, creatorUserId, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestSetPackageDto {\n");
    
    sb.append("    testSetId: ").append(toIndentedString(testSetId)).append("\n");
    sb.append("    testSet: ").append(toIndentedString(testSet)).append("\n");
    sb.append("    versionMask: ").append(toIndentedString(versionMask)).append("\n");
    sb.append("    packageIdentifier: ").append(toIndentedString(packageIdentifier)).append("\n");
    sb.append("    includePrerelease: ").append(toIndentedString(includePrerelease)).append("\n");
    sb.append("    lastModificationTime: ").append(toIndentedString(lastModificationTime)).append("\n");
    sb.append("    lastModifierUserId: ").append(toIndentedString(lastModifierUserId)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    creatorUserId: ").append(toIndentedString(creatorUserId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
