/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * TestDataQueueDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class TestDataQueueDto {
  @JsonProperty("Name")
  private String name = null;

  @JsonProperty("Description")
  private String description = null;

  @JsonProperty("ContentJsonSchema")
  private String contentJsonSchema = null;

  @JsonProperty("ItemsCount")
  private Integer itemsCount = null;

  @JsonProperty("ConsumedItemsCount")
  private Integer consumedItemsCount = null;

  @JsonProperty("IsDeleted")
  private Boolean isDeleted = null;

  @JsonProperty("DeleterUserId")
  private Long deleterUserId = null;

  @JsonProperty("DeletionTime")
  private OffsetDateTime deletionTime = null;

  @JsonProperty("LastModificationTime")
  private OffsetDateTime lastModificationTime = null;

  @JsonProperty("LastModifierUserId")
  private Long lastModifierUserId = null;

  @JsonProperty("CreationTime")
  private OffsetDateTime creationTime = null;

  @JsonProperty("CreatorUserId")
  private Long creatorUserId = null;

  @JsonProperty("Id")
  private Long id = null;

  public TestDataQueueDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TestDataQueueDto description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TestDataQueueDto contentJsonSchema(String contentJsonSchema) {
    this.contentJsonSchema = contentJsonSchema;
    return this;
  }

   /**
   * Get contentJsonSchema
   * @return contentJsonSchema
  **/
  public String getContentJsonSchema() {
    return contentJsonSchema;
  }

  public void setContentJsonSchema(String contentJsonSchema) {
    this.contentJsonSchema = contentJsonSchema;
  }

  public TestDataQueueDto itemsCount(Integer itemsCount) {
    this.itemsCount = itemsCount;
    return this;
  }

   /**
   * Get itemsCount
   * @return itemsCount
  **/
  public Integer getItemsCount() {
    return itemsCount;
  }

  public void setItemsCount(Integer itemsCount) {
    this.itemsCount = itemsCount;
  }

  public TestDataQueueDto consumedItemsCount(Integer consumedItemsCount) {
    this.consumedItemsCount = consumedItemsCount;
    return this;
  }

   /**
   * Get consumedItemsCount
   * @return consumedItemsCount
  **/
  public Integer getConsumedItemsCount() {
    return consumedItemsCount;
  }

  public void setConsumedItemsCount(Integer consumedItemsCount) {
    this.consumedItemsCount = consumedItemsCount;
  }

  public TestDataQueueDto isDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
    return this;
  }

   /**
   * Get isDeleted
   * @return isDeleted
  **/
  public Boolean isIsDeleted() {
    return isDeleted;
  }

  public void setIsDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }

  public TestDataQueueDto deleterUserId(Long deleterUserId) {
    this.deleterUserId = deleterUserId;
    return this;
  }

   /**
   * Get deleterUserId
   * @return deleterUserId
  **/
  public Long getDeleterUserId() {
    return deleterUserId;
  }

  public void setDeleterUserId(Long deleterUserId) {
    this.deleterUserId = deleterUserId;
  }

  public TestDataQueueDto deletionTime(OffsetDateTime deletionTime) {
    this.deletionTime = deletionTime;
    return this;
  }

   /**
   * Get deletionTime
   * @return deletionTime
  **/
  public OffsetDateTime getDeletionTime() {
    return deletionTime;
  }

  public void setDeletionTime(OffsetDateTime deletionTime) {
    this.deletionTime = deletionTime;
  }

  public TestDataQueueDto lastModificationTime(OffsetDateTime lastModificationTime) {
    this.lastModificationTime = lastModificationTime;
    return this;
  }

   /**
   * Get lastModificationTime
   * @return lastModificationTime
  **/
  public OffsetDateTime getLastModificationTime() {
    return lastModificationTime;
  }

  public void setLastModificationTime(OffsetDateTime lastModificationTime) {
    this.lastModificationTime = lastModificationTime;
  }

  public TestDataQueueDto lastModifierUserId(Long lastModifierUserId) {
    this.lastModifierUserId = lastModifierUserId;
    return this;
  }

   /**
   * Get lastModifierUserId
   * @return lastModifierUserId
  **/
  public Long getLastModifierUserId() {
    return lastModifierUserId;
  }

  public void setLastModifierUserId(Long lastModifierUserId) {
    this.lastModifierUserId = lastModifierUserId;
  }

  public TestDataQueueDto creationTime(OffsetDateTime creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * Get creationTime
   * @return creationTime
  **/
  public OffsetDateTime getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(OffsetDateTime creationTime) {
    this.creationTime = creationTime;
  }

  public TestDataQueueDto creatorUserId(Long creatorUserId) {
    this.creatorUserId = creatorUserId;
    return this;
  }

   /**
   * Get creatorUserId
   * @return creatorUserId
  **/
  public Long getCreatorUserId() {
    return creatorUserId;
  }

  public void setCreatorUserId(Long creatorUserId) {
    this.creatorUserId = creatorUserId;
  }

  public TestDataQueueDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestDataQueueDto testDataQueueDto = (TestDataQueueDto) o;
    return Objects.equals(this.name, testDataQueueDto.name) &&
        Objects.equals(this.description, testDataQueueDto.description) &&
        Objects.equals(this.contentJsonSchema, testDataQueueDto.contentJsonSchema) &&
        Objects.equals(this.itemsCount, testDataQueueDto.itemsCount) &&
        Objects.equals(this.consumedItemsCount, testDataQueueDto.consumedItemsCount) &&
        Objects.equals(this.isDeleted, testDataQueueDto.isDeleted) &&
        Objects.equals(this.deleterUserId, testDataQueueDto.deleterUserId) &&
        Objects.equals(this.deletionTime, testDataQueueDto.deletionTime) &&
        Objects.equals(this.lastModificationTime, testDataQueueDto.lastModificationTime) &&
        Objects.equals(this.lastModifierUserId, testDataQueueDto.lastModifierUserId) &&
        Objects.equals(this.creationTime, testDataQueueDto.creationTime) &&
        Objects.equals(this.creatorUserId, testDataQueueDto.creatorUserId) &&
        Objects.equals(this.id, testDataQueueDto.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, contentJsonSchema, itemsCount, consumedItemsCount, isDeleted, deleterUserId, deletionTime, lastModificationTime, lastModifierUserId, creationTime, creatorUserId, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestDataQueueDto {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    contentJsonSchema: ").append(toIndentedString(contentJsonSchema)).append("\n");
    sb.append("    itemsCount: ").append(toIndentedString(itemsCount)).append("\n");
    sb.append("    consumedItemsCount: ").append(toIndentedString(consumedItemsCount)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deleterUserId: ").append(toIndentedString(deleterUserId)).append("\n");
    sb.append("    deletionTime: ").append(toIndentedString(deletionTime)).append("\n");
    sb.append("    lastModificationTime: ").append(toIndentedString(lastModificationTime)).append("\n");
    sb.append("    lastModifierUserId: ").append(toIndentedString(lastModifierUserId)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    creatorUserId: ").append(toIndentedString(creatorUserId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
