/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.uipath.orchestrator.TestCaseAssertionDto;
import com.uipath.orchestrator.TestCaseDto;
import com.uipath.orchestrator.TestCaseExecutionAttachmentDto;
import com.uipath.orchestrator.TestSetExecutionDto;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
/**
 * TestCaseExecutionDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class TestCaseExecutionDto {
  @JsonProperty("JobId")
  private Long jobId = null;

  @JsonProperty("JobKey")
  private UUID jobKey = null;

  @JsonProperty("TestSetExecutionId")
  private Long testSetExecutionId = null;

  @JsonProperty("TestSetExecution")
  private TestSetExecutionDto testSetExecution = null;

  @JsonProperty("TestCaseId")
  private Long testCaseId = null;

  @JsonProperty("TestCase")
  private TestCaseDto testCase = null;

  @JsonProperty("ReleaseVersionId")
  private Long releaseVersionId = null;

  @JsonProperty("VersionNumber")
  private String versionNumber = null;

  @JsonProperty("EntryPointPath")
  private String entryPointPath = null;

  @JsonProperty("StartTime")
  private OffsetDateTime startTime = null;

  @JsonProperty("EndTime")
  private OffsetDateTime endTime = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    PENDING("Pending"),
    RUNNING("Running"),
    CANCELLING("Cancelling"),
    PASSED("Passed"),
    FAILED("Failed"),
    CANCELLED("Cancelled");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("Status")
  private StatusEnum status = null;

  @JsonProperty("TestCaseAssertions")
  private List<TestCaseAssertionDto> testCaseAssertions = null;

  @JsonProperty("TestCaseExecutionAttachments")
  private List<TestCaseExecutionAttachmentDto> testCaseExecutionAttachments = null;

  @JsonProperty("DataVariationIdentifier")
  private String dataVariationIdentifier = null;

  @JsonProperty("OutputArguments")
  private String outputArguments = null;

  @JsonProperty("InputArguments")
  private String inputArguments = null;

  @JsonProperty("Info")
  private String info = null;

  @JsonProperty("HostMachineName")
  private String hostMachineName = null;

  /**
   * Gets or Sets runtimeType
   */
  public enum RuntimeTypeEnum {
    NONPRODUCTION("NonProduction"),
    ATTENDED("Attended"),
    UNATTENDED("Unattended"),
    DEVELOPMENT("Development"),
    STUDIO("Studio"),
    RPADEVELOPER("RpaDeveloper"),
    STUDIOX("StudioX"),
    CITIZENDEVELOPER("CitizenDeveloper"),
    HEADLESS("Headless"),
    STUDIOPRO("StudioPro"),
    RPADEVELOPERPRO("RpaDeveloperPro"),
    TESTAUTOMATION("TestAutomation"),
    AUTOMATIONCLOUD("AutomationCloud"),
    SERVERLESS("Serverless"),
    AUTOMATIONKIT("AutomationKit"),
    SERVERLESSTESTAUTOMATION("ServerlessTestAutomation"),
    AUTOMATIONCLOUDTESTAUTOMATION("AutomationCloudTestAutomation"),
    ATTENDEDSTUDIOWEB("AttendedStudioWeb");

    private String value;

    RuntimeTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static RuntimeTypeEnum fromValue(String input) {
      for (RuntimeTypeEnum b : RuntimeTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("RuntimeType")
  private RuntimeTypeEnum runtimeType = null;

  @JsonProperty("RobotName")
  private String robotName = null;

  @JsonProperty("HasAssertions")
  private Boolean hasAssertions = null;

  @JsonProperty("RunId")
  private Integer runId = null;

  /**
   * Gets or Sets testCaseType
   */
  public enum TestCaseTypeEnum {
    TESTCASE("TestCase"),
    TESTDATASETUP("TestDataSetup");

    private String value;

    TestCaseTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TestCaseTypeEnum fromValue(String input) {
      for (TestCaseTypeEnum b : TestCaseTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("TestCaseType")
  private TestCaseTypeEnum testCaseType = null;

  @JsonProperty("ExecutionOrder")
  private Integer executionOrder = null;

  @JsonProperty("Id")
  private Long id = null;

  public TestCaseExecutionDto jobId(Long jobId) {
    this.jobId = jobId;
    return this;
  }

   /**
   * Get jobId
   * @return jobId
  **/
  public Long getJobId() {
    return jobId;
  }

  public void setJobId(Long jobId) {
    this.jobId = jobId;
  }

  public TestCaseExecutionDto jobKey(UUID jobKey) {
    this.jobKey = jobKey;
    return this;
  }

   /**
   * Get jobKey
   * @return jobKey
  **/
  public UUID getJobKey() {
    return jobKey;
  }

  public void setJobKey(UUID jobKey) {
    this.jobKey = jobKey;
  }

  public TestCaseExecutionDto testSetExecutionId(Long testSetExecutionId) {
    this.testSetExecutionId = testSetExecutionId;
    return this;
  }

   /**
   * Get testSetExecutionId
   * @return testSetExecutionId
  **/
  public Long getTestSetExecutionId() {
    return testSetExecutionId;
  }

  public void setTestSetExecutionId(Long testSetExecutionId) {
    this.testSetExecutionId = testSetExecutionId;
  }

  public TestCaseExecutionDto testSetExecution(TestSetExecutionDto testSetExecution) {
    this.testSetExecution = testSetExecution;
    return this;
  }

   /**
   * Get testSetExecution
   * @return testSetExecution
  **/
  public TestSetExecutionDto getTestSetExecution() {
    return testSetExecution;
  }

  public void setTestSetExecution(TestSetExecutionDto testSetExecution) {
    this.testSetExecution = testSetExecution;
  }

  public TestCaseExecutionDto testCaseId(Long testCaseId) {
    this.testCaseId = testCaseId;
    return this;
  }

   /**
   * Get testCaseId
   * @return testCaseId
  **/
  public Long getTestCaseId() {
    return testCaseId;
  }

  public void setTestCaseId(Long testCaseId) {
    this.testCaseId = testCaseId;
  }

  public TestCaseExecutionDto testCase(TestCaseDto testCase) {
    this.testCase = testCase;
    return this;
  }

   /**
   * Get testCase
   * @return testCase
  **/
  public TestCaseDto getTestCase() {
    return testCase;
  }

  public void setTestCase(TestCaseDto testCase) {
    this.testCase = testCase;
  }

  public TestCaseExecutionDto releaseVersionId(Long releaseVersionId) {
    this.releaseVersionId = releaseVersionId;
    return this;
  }

   /**
   * Get releaseVersionId
   * @return releaseVersionId
  **/
  public Long getReleaseVersionId() {
    return releaseVersionId;
  }

  public void setReleaseVersionId(Long releaseVersionId) {
    this.releaseVersionId = releaseVersionId;
  }

  public TestCaseExecutionDto versionNumber(String versionNumber) {
    this.versionNumber = versionNumber;
    return this;
  }

   /**
   * Get versionNumber
   * @return versionNumber
  **/
  public String getVersionNumber() {
    return versionNumber;
  }

  public void setVersionNumber(String versionNumber) {
    this.versionNumber = versionNumber;
  }

  public TestCaseExecutionDto entryPointPath(String entryPointPath) {
    this.entryPointPath = entryPointPath;
    return this;
  }

   /**
   * Get entryPointPath
   * @return entryPointPath
  **/
  public String getEntryPointPath() {
    return entryPointPath;
  }

  public void setEntryPointPath(String entryPointPath) {
    this.entryPointPath = entryPointPath;
  }

  public TestCaseExecutionDto startTime(OffsetDateTime startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  public OffsetDateTime getStartTime() {
    return startTime;
  }

  public void setStartTime(OffsetDateTime startTime) {
    this.startTime = startTime;
  }

  public TestCaseExecutionDto endTime(OffsetDateTime endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  public OffsetDateTime getEndTime() {
    return endTime;
  }

  public void setEndTime(OffsetDateTime endTime) {
    this.endTime = endTime;
  }

  public TestCaseExecutionDto status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public TestCaseExecutionDto testCaseAssertions(List<TestCaseAssertionDto> testCaseAssertions) {
    this.testCaseAssertions = testCaseAssertions;
    return this;
  }

  public TestCaseExecutionDto addTestCaseAssertionsItem(TestCaseAssertionDto testCaseAssertionsItem) {
    if (this.testCaseAssertions == null) {
      this.testCaseAssertions = new ArrayList<>();
    }
    this.testCaseAssertions.add(testCaseAssertionsItem);
    return this;
  }

   /**
   * Get testCaseAssertions
   * @return testCaseAssertions
  **/
  public List<TestCaseAssertionDto> getTestCaseAssertions() {
    return testCaseAssertions;
  }

  public void setTestCaseAssertions(List<TestCaseAssertionDto> testCaseAssertions) {
    this.testCaseAssertions = testCaseAssertions;
  }

  public TestCaseExecutionDto testCaseExecutionAttachments(List<TestCaseExecutionAttachmentDto> testCaseExecutionAttachments) {
    this.testCaseExecutionAttachments = testCaseExecutionAttachments;
    return this;
  }

  public TestCaseExecutionDto addTestCaseExecutionAttachmentsItem(TestCaseExecutionAttachmentDto testCaseExecutionAttachmentsItem) {
    if (this.testCaseExecutionAttachments == null) {
      this.testCaseExecutionAttachments = new ArrayList<>();
    }
    this.testCaseExecutionAttachments.add(testCaseExecutionAttachmentsItem);
    return this;
  }

   /**
   * Get testCaseExecutionAttachments
   * @return testCaseExecutionAttachments
  **/
  public List<TestCaseExecutionAttachmentDto> getTestCaseExecutionAttachments() {
    return testCaseExecutionAttachments;
  }

  public void setTestCaseExecutionAttachments(List<TestCaseExecutionAttachmentDto> testCaseExecutionAttachments) {
    this.testCaseExecutionAttachments = testCaseExecutionAttachments;
  }

  public TestCaseExecutionDto dataVariationIdentifier(String dataVariationIdentifier) {
    this.dataVariationIdentifier = dataVariationIdentifier;
    return this;
  }

   /**
   * Get dataVariationIdentifier
   * @return dataVariationIdentifier
  **/
  public String getDataVariationIdentifier() {
    return dataVariationIdentifier;
  }

  public void setDataVariationIdentifier(String dataVariationIdentifier) {
    this.dataVariationIdentifier = dataVariationIdentifier;
  }

  public TestCaseExecutionDto outputArguments(String outputArguments) {
    this.outputArguments = outputArguments;
    return this;
  }

   /**
   * Get outputArguments
   * @return outputArguments
  **/
  public String getOutputArguments() {
    return outputArguments;
  }

  public void setOutputArguments(String outputArguments) {
    this.outputArguments = outputArguments;
  }

  public TestCaseExecutionDto inputArguments(String inputArguments) {
    this.inputArguments = inputArguments;
    return this;
  }

   /**
   * Get inputArguments
   * @return inputArguments
  **/
  public String getInputArguments() {
    return inputArguments;
  }

  public void setInputArguments(String inputArguments) {
    this.inputArguments = inputArguments;
  }

  public TestCaseExecutionDto info(String info) {
    this.info = info;
    return this;
  }

   /**
   * Get info
   * @return info
  **/
  public String getInfo() {
    return info;
  }

  public void setInfo(String info) {
    this.info = info;
  }

  public TestCaseExecutionDto hostMachineName(String hostMachineName) {
    this.hostMachineName = hostMachineName;
    return this;
  }

   /**
   * Get hostMachineName
   * @return hostMachineName
  **/
  public String getHostMachineName() {
    return hostMachineName;
  }

  public void setHostMachineName(String hostMachineName) {
    this.hostMachineName = hostMachineName;
  }

  public TestCaseExecutionDto runtimeType(RuntimeTypeEnum runtimeType) {
    this.runtimeType = runtimeType;
    return this;
  }

   /**
   * Get runtimeType
   * @return runtimeType
  **/
  public RuntimeTypeEnum getRuntimeType() {
    return runtimeType;
  }

  public void setRuntimeType(RuntimeTypeEnum runtimeType) {
    this.runtimeType = runtimeType;
  }

  public TestCaseExecutionDto robotName(String robotName) {
    this.robotName = robotName;
    return this;
  }

   /**
   * Get robotName
   * @return robotName
  **/
  public String getRobotName() {
    return robotName;
  }

  public void setRobotName(String robotName) {
    this.robotName = robotName;
  }

  public TestCaseExecutionDto hasAssertions(Boolean hasAssertions) {
    this.hasAssertions = hasAssertions;
    return this;
  }

   /**
   * Get hasAssertions
   * @return hasAssertions
  **/
  public Boolean isHasAssertions() {
    return hasAssertions;
  }

  public void setHasAssertions(Boolean hasAssertions) {
    this.hasAssertions = hasAssertions;
  }

  public TestCaseExecutionDto runId(Integer runId) {
    this.runId = runId;
    return this;
  }

   /**
   * Get runId
   * @return runId
  **/
  public Integer getRunId() {
    return runId;
  }

  public void setRunId(Integer runId) {
    this.runId = runId;
  }

  public TestCaseExecutionDto testCaseType(TestCaseTypeEnum testCaseType) {
    this.testCaseType = testCaseType;
    return this;
  }

   /**
   * Get testCaseType
   * @return testCaseType
  **/
  public TestCaseTypeEnum getTestCaseType() {
    return testCaseType;
  }

  public void setTestCaseType(TestCaseTypeEnum testCaseType) {
    this.testCaseType = testCaseType;
  }

  public TestCaseExecutionDto executionOrder(Integer executionOrder) {
    this.executionOrder = executionOrder;
    return this;
  }

   /**
   * Get executionOrder
   * @return executionOrder
  **/
  public Integer getExecutionOrder() {
    return executionOrder;
  }

  public void setExecutionOrder(Integer executionOrder) {
    this.executionOrder = executionOrder;
  }

  public TestCaseExecutionDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestCaseExecutionDto testCaseExecutionDto = (TestCaseExecutionDto) o;
    return Objects.equals(this.jobId, testCaseExecutionDto.jobId) &&
        Objects.equals(this.jobKey, testCaseExecutionDto.jobKey) &&
        Objects.equals(this.testSetExecutionId, testCaseExecutionDto.testSetExecutionId) &&
        Objects.equals(this.testSetExecution, testCaseExecutionDto.testSetExecution) &&
        Objects.equals(this.testCaseId, testCaseExecutionDto.testCaseId) &&
        Objects.equals(this.testCase, testCaseExecutionDto.testCase) &&
        Objects.equals(this.releaseVersionId, testCaseExecutionDto.releaseVersionId) &&
        Objects.equals(this.versionNumber, testCaseExecutionDto.versionNumber) &&
        Objects.equals(this.entryPointPath, testCaseExecutionDto.entryPointPath) &&
        Objects.equals(this.startTime, testCaseExecutionDto.startTime) &&
        Objects.equals(this.endTime, testCaseExecutionDto.endTime) &&
        Objects.equals(this.status, testCaseExecutionDto.status) &&
        Objects.equals(this.testCaseAssertions, testCaseExecutionDto.testCaseAssertions) &&
        Objects.equals(this.testCaseExecutionAttachments, testCaseExecutionDto.testCaseExecutionAttachments) &&
        Objects.equals(this.dataVariationIdentifier, testCaseExecutionDto.dataVariationIdentifier) &&
        Objects.equals(this.outputArguments, testCaseExecutionDto.outputArguments) &&
        Objects.equals(this.inputArguments, testCaseExecutionDto.inputArguments) &&
        Objects.equals(this.info, testCaseExecutionDto.info) &&
        Objects.equals(this.hostMachineName, testCaseExecutionDto.hostMachineName) &&
        Objects.equals(this.runtimeType, testCaseExecutionDto.runtimeType) &&
        Objects.equals(this.robotName, testCaseExecutionDto.robotName) &&
        Objects.equals(this.hasAssertions, testCaseExecutionDto.hasAssertions) &&
        Objects.equals(this.runId, testCaseExecutionDto.runId) &&
        Objects.equals(this.testCaseType, testCaseExecutionDto.testCaseType) &&
        Objects.equals(this.executionOrder, testCaseExecutionDto.executionOrder) &&
        Objects.equals(this.id, testCaseExecutionDto.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobId, jobKey, testSetExecutionId, testSetExecution, testCaseId, testCase, releaseVersionId, versionNumber, entryPointPath, startTime, endTime, status, testCaseAssertions, testCaseExecutionAttachments, dataVariationIdentifier, outputArguments, inputArguments, info, hostMachineName, runtimeType, robotName, hasAssertions, runId, testCaseType, executionOrder, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestCaseExecutionDto {\n");
    
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("    jobKey: ").append(toIndentedString(jobKey)).append("\n");
    sb.append("    testSetExecutionId: ").append(toIndentedString(testSetExecutionId)).append("\n");
    sb.append("    testSetExecution: ").append(toIndentedString(testSetExecution)).append("\n");
    sb.append("    testCaseId: ").append(toIndentedString(testCaseId)).append("\n");
    sb.append("    testCase: ").append(toIndentedString(testCase)).append("\n");
    sb.append("    releaseVersionId: ").append(toIndentedString(releaseVersionId)).append("\n");
    sb.append("    versionNumber: ").append(toIndentedString(versionNumber)).append("\n");
    sb.append("    entryPointPath: ").append(toIndentedString(entryPointPath)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    testCaseAssertions: ").append(toIndentedString(testCaseAssertions)).append("\n");
    sb.append("    testCaseExecutionAttachments: ").append(toIndentedString(testCaseExecutionAttachments)).append("\n");
    sb.append("    dataVariationIdentifier: ").append(toIndentedString(dataVariationIdentifier)).append("\n");
    sb.append("    outputArguments: ").append(toIndentedString(outputArguments)).append("\n");
    sb.append("    inputArguments: ").append(toIndentedString(inputArguments)).append("\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    sb.append("    hostMachineName: ").append(toIndentedString(hostMachineName)).append("\n");
    sb.append("    runtimeType: ").append(toIndentedString(runtimeType)).append("\n");
    sb.append("    robotName: ").append(toIndentedString(robotName)).append("\n");
    sb.append("    hasAssertions: ").append(toIndentedString(hasAssertions)).append("\n");
    sb.append("    runId: ").append(toIndentedString(runId)).append("\n");
    sb.append("    testCaseType: ").append(toIndentedString(testCaseType)).append("\n");
    sb.append("    executionOrder: ").append(toIndentedString(executionOrder)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
