/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * TestSetInputArgumentDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class TestSetInputArgumentDto {
  @JsonProperty("Name")
  private String name = null;

  @JsonProperty("Type")
  private String type = null;

  @JsonProperty("Value")
  private String value = null;

  @JsonProperty("LastModificationTime")
  private OffsetDateTime lastModificationTime = null;

  @JsonProperty("LastModifierUserId")
  private Long lastModifierUserId = null;

  @JsonProperty("CreationTime")
  private OffsetDateTime creationTime = null;

  @JsonProperty("CreatorUserId")
  private Long creatorUserId = null;

  @JsonProperty("Id")
  private Long id = null;

  public TestSetInputArgumentDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TestSetInputArgumentDto type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public TestSetInputArgumentDto value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public TestSetInputArgumentDto lastModificationTime(OffsetDateTime lastModificationTime) {
    this.lastModificationTime = lastModificationTime;
    return this;
  }

   /**
   * Get lastModificationTime
   * @return lastModificationTime
  **/
  public OffsetDateTime getLastModificationTime() {
    return lastModificationTime;
  }

  public void setLastModificationTime(OffsetDateTime lastModificationTime) {
    this.lastModificationTime = lastModificationTime;
  }

  public TestSetInputArgumentDto lastModifierUserId(Long lastModifierUserId) {
    this.lastModifierUserId = lastModifierUserId;
    return this;
  }

   /**
   * Get lastModifierUserId
   * @return lastModifierUserId
  **/
  public Long getLastModifierUserId() {
    return lastModifierUserId;
  }

  public void setLastModifierUserId(Long lastModifierUserId) {
    this.lastModifierUserId = lastModifierUserId;
  }

  public TestSetInputArgumentDto creationTime(OffsetDateTime creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * Get creationTime
   * @return creationTime
  **/
  public OffsetDateTime getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(OffsetDateTime creationTime) {
    this.creationTime = creationTime;
  }

  public TestSetInputArgumentDto creatorUserId(Long creatorUserId) {
    this.creatorUserId = creatorUserId;
    return this;
  }

   /**
   * Get creatorUserId
   * @return creatorUserId
  **/
  public Long getCreatorUserId() {
    return creatorUserId;
  }

  public void setCreatorUserId(Long creatorUserId) {
    this.creatorUserId = creatorUserId;
  }

  public TestSetInputArgumentDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestSetInputArgumentDto testSetInputArgumentDto = (TestSetInputArgumentDto) o;
    return Objects.equals(this.name, testSetInputArgumentDto.name) &&
        Objects.equals(this.type, testSetInputArgumentDto.type) &&
        Objects.equals(this.value, testSetInputArgumentDto.value) &&
        Objects.equals(this.lastModificationTime, testSetInputArgumentDto.lastModificationTime) &&
        Objects.equals(this.lastModifierUserId, testSetInputArgumentDto.lastModifierUserId) &&
        Objects.equals(this.creationTime, testSetInputArgumentDto.creationTime) &&
        Objects.equals(this.creatorUserId, testSetInputArgumentDto.creatorUserId) &&
        Objects.equals(this.id, testSetInputArgumentDto.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, type, value, lastModificationTime, lastModifierUserId, creationTime, creatorUserId, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestSetInputArgumentDto {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    lastModificationTime: ").append(toIndentedString(lastModificationTime)).append("\n");
    sb.append("    lastModifierUserId: ").append(toIndentedString(lastModifierUserId)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    creatorUserId: ").append(toIndentedString(creatorUserId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
