/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
/**
 * Stores data sent when processing of an existing or a new item starts.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class TransactionDataDto {
  @JsonProperty("Name")
  private String name = null;

  @JsonProperty("RobotIdentifier")
  private UUID robotIdentifier = null;

  @JsonProperty("SpecificContent")
  private Map<String, Object> specificContent = null;

  @JsonProperty("DeferDate")
  private OffsetDateTime deferDate = null;

  @JsonProperty("DueDate")
  private OffsetDateTime dueDate = null;

  @JsonProperty("Reference")
  private String reference = null;

  /**
   * Declares the strategy used to filter the Reference value.
   */
  public enum ReferenceFilterOptionEnum {
    EQUALS("Equals"),
    STARTSWITH("StartsWith");

    private String value;

    ReferenceFilterOptionEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ReferenceFilterOptionEnum fromValue(String input) {
      for (ReferenceFilterOptionEnum b : ReferenceFilterOptionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("ReferenceFilterOption")
  private ReferenceFilterOptionEnum referenceFilterOption = null;

  @JsonProperty("ParentOperationId")
  private String parentOperationId = null;

  public TransactionDataDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the queue in which to search for the next item or in which to insert the item before marking it as InProgress and sending it to the robot.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TransactionDataDto robotIdentifier(UUID robotIdentifier) {
    this.robotIdentifier = robotIdentifier;
    return this;
  }

   /**
   * The unique key identifying the robot that sent the request.
   * @return robotIdentifier
  **/
  public UUID getRobotIdentifier() {
    return robotIdentifier;
  }

  public void setRobotIdentifier(UUID robotIdentifier) {
    this.robotIdentifier = robotIdentifier;
  }

  public TransactionDataDto specificContent(Map<String, Object> specificContent) {
    this.specificContent = specificContent;
    return this;
  }

  public TransactionDataDto putSpecificContentItem(String key, Object specificContentItem) {
    if (this.specificContent == null) {
      this.specificContent = new HashMap<>();
    }
    this.specificContent.put(key, specificContentItem);
    return this;
  }

   /**
   * If not null a new item will be added to the queue with this content before being moved to InProgress state and returned to the robot for processing.  &lt;para /&gt;If null the next available item in the list will be moved to InProgress state and returned to the robot for processing.
   * @return specificContent
  **/
  public Map<String, Object> getSpecificContent() {
    return specificContent;
  }

  public void setSpecificContent(Map<String, Object> specificContent) {
    this.specificContent = specificContent;
  }

  public TransactionDataDto deferDate(OffsetDateTime deferDate) {
    this.deferDate = deferDate;
    return this;
  }

   /**
   * The earliest date and time at which the item is available for processing. If empty the item can be processed as soon as possible.
   * @return deferDate
  **/
  public OffsetDateTime getDeferDate() {
    return deferDate;
  }

  public void setDeferDate(OffsetDateTime deferDate) {
    this.deferDate = deferDate;
  }

  public TransactionDataDto dueDate(OffsetDateTime dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * The latest date and time at which the item should be processed. If empty the item can be processed at any given time.
   * @return dueDate
  **/
  public OffsetDateTime getDueDate() {
    return dueDate;
  }

  public void setDueDate(OffsetDateTime dueDate) {
    this.dueDate = dueDate;
  }

  public TransactionDataDto reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * An optional, user-specified value for queue item identification.
   * @return reference
  **/
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public TransactionDataDto referenceFilterOption(ReferenceFilterOptionEnum referenceFilterOption) {
    this.referenceFilterOption = referenceFilterOption;
    return this;
  }

   /**
   * Declares the strategy used to filter the Reference value.
   * @return referenceFilterOption
  **/
  public ReferenceFilterOptionEnum getReferenceFilterOption() {
    return referenceFilterOption;
  }

  public void setReferenceFilterOption(ReferenceFilterOptionEnum referenceFilterOption) {
    this.referenceFilterOption = referenceFilterOption;
  }

  public TransactionDataDto parentOperationId(String parentOperationId) {
    this.parentOperationId = parentOperationId;
    return this;
  }

   /**
   * Operation id which created the queue item.
   * @return parentOperationId
  **/
  public String getParentOperationId() {
    return parentOperationId;
  }

  public void setParentOperationId(String parentOperationId) {
    this.parentOperationId = parentOperationId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionDataDto transactionDataDto = (TransactionDataDto) o;
    return Objects.equals(this.name, transactionDataDto.name) &&
        Objects.equals(this.robotIdentifier, transactionDataDto.robotIdentifier) &&
        Objects.equals(this.specificContent, transactionDataDto.specificContent) &&
        Objects.equals(this.deferDate, transactionDataDto.deferDate) &&
        Objects.equals(this.dueDate, transactionDataDto.dueDate) &&
        Objects.equals(this.reference, transactionDataDto.reference) &&
        Objects.equals(this.referenceFilterOption, transactionDataDto.referenceFilterOption) &&
        Objects.equals(this.parentOperationId, transactionDataDto.parentOperationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, robotIdentifier, specificContent, deferDate, dueDate, reference, referenceFilterOption, parentOperationId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionDataDto {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    robotIdentifier: ").append(toIndentedString(robotIdentifier)).append("\n");
    sb.append("    specificContent: ").append(toIndentedString(specificContent)).append("\n");
    sb.append("    deferDate: ").append(toIndentedString(deferDate)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    referenceFilterOption: ").append(toIndentedString(referenceFilterOption)).append("\n");
    sb.append("    parentOperationId: ").append(toIndentedString(parentOperationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
