/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The policy applied for update robots&#x27; versions
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class UpdatePolicyDto {
  /**
   * The type of the policy (None/ SpecificVersion/ LatestVersion)
   */
  public enum TypeEnum {
    NONE("None"),
    SPECIFICVERSION("SpecificVersion"),
    LATESTVERSION("LatestVersion"),
    LATESTPATCH("LatestPatch");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("Type")
  private TypeEnum type = null;

  @JsonProperty("SpecificVersion")
  private String specificVersion = null;

  public UpdatePolicyDto type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * The type of the policy (None/ SpecificVersion/ LatestVersion)
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public UpdatePolicyDto specificVersion(String specificVersion) {
    this.specificVersion = specificVersion;
    return this;
  }

   /**
   * The specific version used for SpecificVersion policy type
   * @return specificVersion
  **/
  public String getSpecificVersion() {
    return specificVersion;
  }

  public void setSpecificVersion(String specificVersion) {
    this.specificVersion = specificVersion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdatePolicyDto updatePolicyDto = (UpdatePolicyDto) o;
    return Objects.equals(this.type, updatePolicyDto.type) &&
        Objects.equals(this.specificVersion, updatePolicyDto.specificVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, specificVersion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdatePolicyDto {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    specificVersion: ").append(toIndentedString(specificVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
