/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * UpdateSettingsDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class UpdateSettingsDto {
  /**
   * Gets or Sets updateServerSource
   */
  public enum UpdateServerSourceEnum {
    ORCHESTRATOR("Orchestrator");

    private String value;

    UpdateServerSourceEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static UpdateServerSourceEnum fromValue(String input) {
      for (UpdateServerSourceEnum b : UpdateServerSourceEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("UpdateServerSource")
  private UpdateServerSourceEnum updateServerSource = null;

  @JsonProperty("UpdateServerUrl")
  private String updateServerUrl = null;

  @JsonProperty("PollingInterval")
  private Integer pollingInterval = null;

  public UpdateSettingsDto updateServerSource(UpdateServerSourceEnum updateServerSource) {
    this.updateServerSource = updateServerSource;
    return this;
  }

   /**
   * Get updateServerSource
   * @return updateServerSource
  **/
  public UpdateServerSourceEnum getUpdateServerSource() {
    return updateServerSource;
  }

  public void setUpdateServerSource(UpdateServerSourceEnum updateServerSource) {
    this.updateServerSource = updateServerSource;
  }

  public UpdateSettingsDto updateServerUrl(String updateServerUrl) {
    this.updateServerUrl = updateServerUrl;
    return this;
  }

   /**
   * Get updateServerUrl
   * @return updateServerUrl
  **/
  public String getUpdateServerUrl() {
    return updateServerUrl;
  }

  public void setUpdateServerUrl(String updateServerUrl) {
    this.updateServerUrl = updateServerUrl;
  }

  public UpdateSettingsDto pollingInterval(Integer pollingInterval) {
    this.pollingInterval = pollingInterval;
    return this;
  }

   /**
   * Get pollingInterval
   * @return pollingInterval
  **/
  public Integer getPollingInterval() {
    return pollingInterval;
  }

  public void setPollingInterval(Integer pollingInterval) {
    this.pollingInterval = pollingInterval;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateSettingsDto updateSettingsDto = (UpdateSettingsDto) o;
    return Objects.equals(this.updateServerSource, updateSettingsDto.updateServerSource) &&
        Objects.equals(this.updateServerUrl, updateSettingsDto.updateServerUrl) &&
        Objects.equals(this.pollingInterval, updateSettingsDto.pollingInterval);
  }

  @Override
  public int hashCode() {
    return Objects.hash(updateServerSource, updateServerUrl, pollingInterval);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateSettingsDto {\n");
    
    sb.append("    updateServerSource: ").append(toIndentedString(updateServerSource)).append("\n");
    sb.append("    updateServerUrl: ").append(toIndentedString(updateServerUrl)).append("\n");
    sb.append("    pollingInterval: ").append(toIndentedString(pollingInterval)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
