/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * UsersToggleOrganizationUnitRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class UsersToggleOrganizationUnitRequest {
  @JsonProperty("organizationUnitId")
  private Long organizationUnitId = null;

  @JsonProperty("toggle")
  private Boolean toggle = null;

  public UsersToggleOrganizationUnitRequest organizationUnitId(Long organizationUnitId) {
    this.organizationUnitId = organizationUnitId;
    return this;
  }

   /**
   * Get organizationUnitId
   * @return organizationUnitId
  **/
  public Long getOrganizationUnitId() {
    return organizationUnitId;
  }

  public void setOrganizationUnitId(Long organizationUnitId) {
    this.organizationUnitId = organizationUnitId;
  }

  public UsersToggleOrganizationUnitRequest toggle(Boolean toggle) {
    this.toggle = toggle;
    return this;
  }

   /**
   * Get toggle
   * @return toggle
  **/
  public Boolean isToggle() {
    return toggle;
  }

  public void setToggle(Boolean toggle) {
    this.toggle = toggle;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsersToggleOrganizationUnitRequest usersToggleOrganizationUnitRequest = (UsersToggleOrganizationUnitRequest) o;
    return Objects.equals(this.organizationUnitId, usersToggleOrganizationUnitRequest.organizationUnitId) &&
        Objects.equals(this.toggle, usersToggleOrganizationUnitRequest.toggle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(organizationUnitId, toggle);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsersToggleOrganizationUnitRequest {\n");
    
    sb.append("    organizationUnitId: ").append(toIndentedString(organizationUnitId)).append("\n");
    sb.append("    toggle: ").append(toIndentedString(toggle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
