/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * ValidationResultDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class ValidationResultDto {
  @JsonProperty("IsValid")
  private Boolean isValid = null;

  @JsonProperty("Errors")
  private List<String> errors = null;

  /**
   * Gets or Sets errorCodes
   */
  public enum ErrorCodesEnum {
    ROBOTNOTASSIGNEDTOFOLDER("RobotNotAssignedToFolder"),
    ROBOTNOTFOUND("RobotNotFound"),
    ROBOTNOCREDENTIALS("RobotNoCredentials"),
    ROBOTBUSY("RobotBusy"),
    ROBOTCONCURRENCYLIMIT("RobotConcurrencyLimit"),
    ROBOTNOMATCHINGUSERNAMES("RobotNoMatchingUsernames"),
    TEMPLATENORUNTIME("TemplateNoRuntime"),
    TEMPLATENOHOSTSAVAILABLE("TemplateNoHostsAvailable"),
    TEMPLATENOLICENSE("TemplateNoLicense"),
    TEMPLATEFULLCAPACITY("TemplateFullCapacity"),
    TEMPLATENOTASSIGNEDTOFOLDER("TemplateNotAssignedToFolder"),
    TEMPLATEMAINTENANCEMODE("TemplateMaintenanceMode"),
    DYNAMICJOBACCOUNTCREDENTIALSINVALID("DynamicJobAccountCredentialsInvalid"),
    DYNAMICJOBFOREGROUNDAUTOMATIONTYPEINVALID("DynamicJobForegroundAutomationTypeInvalid"),
    DYNAMICJOBBACKGROUNDAUTOMATIONTYPEINVALID("DynamicJobBackgroundAutomationTypeInvalid"),
    DYNAMICJOBWINDOWSTARGETFRAMEWORKINVALID("DynamicJobWindowsTargetFrameworkInvalid"),
    DYNAMICJOBCROSSPLATFORMTARGETFRAMEWORKINVALID("DynamicJobCrossPlatformTargetFrameworkInvalid"),
    DYNAMICJOBCONNECTEDMACHINESINVALID("DynamicJobConnectedMachinesInvalid"),
    DYNAMICJOBCONNECTEDMACHINESUSERCREDENTIALSINVALID("DynamicJobConnectedMachinesUserCredentialsInvalid"),
    DYNAMICJOBCONNECTEDMACHINESCROSSPLATFORMROBOTVERSIONINVALID("DynamicJobConnectedMachinesCrossPlatformRobotVersionInvalid"),
    DYNAMICJOBCONNECTEDMACHINESWINDOWSROBOTVERSIONINVALID("DynamicJobConnectedMachinesWindowsRobotVersionInvalid");

    private String value;

    ErrorCodesEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ErrorCodesEnum fromValue(String input) {
      for (ErrorCodesEnum b : ErrorCodesEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("ErrorCodes")
  private List<ErrorCodesEnum> errorCodes = null;

  public ValidationResultDto isValid(Boolean isValid) {
    this.isValid = isValid;
    return this;
  }

   /**
   * Get isValid
   * @return isValid
  **/
  public Boolean isIsValid() {
    return isValid;
  }

  public void setIsValid(Boolean isValid) {
    this.isValid = isValid;
  }

   /**
   * Get errors
   * @return errors
  **/
  public List<String> getErrors() {
    return errors;
  }

   /**
   * Get errorCodes
   * @return errorCodes
  **/
  public List<ErrorCodesEnum> getErrorCodes() {
    return errorCodes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidationResultDto validationResultDto = (ValidationResultDto) o;
    return Objects.equals(this.isValid, validationResultDto.isValid) &&
        Objects.equals(this.errors, validationResultDto.errors) &&
        Objects.equals(this.errorCodes, validationResultDto.errorCodes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isValid, errors, errorCodes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidationResultDto {\n");
    
    sb.append("    isValid: ").append(toIndentedString(isValid)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    errorCodes: ").append(toIndentedString(errorCodes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
