/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.uipath.orchestrator.SmtpSettingModel;

/**
 * VerifySmtpSettingRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class VerifySmtpSettingRequest {
  @JsonProperty("sendTo")
  private String sendTo = null;

  @JsonProperty("smtpSettingModel")
  private SmtpSettingModel smtpSettingModel = null;

  public VerifySmtpSettingRequest sendTo(String sendTo) {
    this.sendTo = sendTo;
    return this;
  }

   /**
   * Get sendTo
   * @return sendTo
  **/
  public String getSendTo() {
    return sendTo;
  }

  public void setSendTo(String sendTo) {
    this.sendTo = sendTo;
  }

  public VerifySmtpSettingRequest smtpSettingModel(SmtpSettingModel smtpSettingModel) {
    this.smtpSettingModel = smtpSettingModel;
    return this;
  }

   /**
   * Get smtpSettingModel
   * @return smtpSettingModel
  **/
  public SmtpSettingModel getSmtpSettingModel() {
    return smtpSettingModel;
  }

  public void setSmtpSettingModel(SmtpSettingModel smtpSettingModel) {
    this.smtpSettingModel = smtpSettingModel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerifySmtpSettingRequest verifySmtpSettingRequest = (VerifySmtpSettingRequest) o;
    return Objects.equals(this.sendTo, verifySmtpSettingRequest.sendTo) &&
        Objects.equals(this.smtpSettingModel, verifySmtpSettingRequest.smtpSettingModel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sendTo, smtpSettingModel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerifySmtpSettingRequest {\n");
    
    sb.append("    sendTo: ").append(toIndentedString(sendTo)).append("\n");
    sb.append("    smtpSettingModel: ").append(toIndentedString(smtpSettingModel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
