/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
import java.util.UUID;
/**
 * WebhookSimpleUserDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class WebhookSimpleUserDto {
  @JsonProperty("Id")
  private Long id = null;

  @JsonProperty("Key")
  private UUID key = null;

  @JsonProperty("UserName")
  private String userName = null;

  @JsonProperty("Domain")
  private String domain = null;

  @JsonProperty("FullName")
  private String fullName = null;

  @JsonProperty("EmailAddress")
  private String emailAddress = null;

  /**
   * The user type.
   */
  public enum TypeEnum {
    USER("User"),
    ROBOT("Robot"),
    DIRECTORYUSER("DirectoryUser"),
    DIRECTORYGROUP("DirectoryGroup"),
    DIRECTORYROBOT("DirectoryRobot"),
    DIRECTORYEXTERNALAPPLICATION("DirectoryExternalApplication");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("Type")
  private TypeEnum type = null;

  @JsonProperty("IsActive")
  private Boolean isActive = null;

  @JsonProperty("LastLoginTime")
  private OffsetDateTime lastLoginTime = null;

  @JsonProperty("CreationTime")
  private OffsetDateTime creationTime = null;

  @JsonProperty("AuthenticationSource")
  private String authenticationSource = null;

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

   /**
   * Get key
   * @return key
  **/
  public UUID getKey() {
    return key;
  }

   /**
   * The name used to login to Orchestrator.
   * @return userName
  **/
  public String getUserName() {
    return userName;
  }

   /**
   * The domain from which the user is imported
   * @return domain
  **/
  public String getDomain() {
    return domain;
  }

   /**
   * The full name of the person constructed with the format Name Surname.
   * @return fullName
  **/
  public String getFullName() {
    return fullName;
  }

   /**
   * The e-mail address associated with the user.
   * @return emailAddress
  **/
  public String getEmailAddress() {
    return emailAddress;
  }

   /**
   * The user type.
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

   /**
   * States if the user is active or not. An inactive user cannot login to Orchestrator.
   * @return isActive
  **/
  public Boolean isIsActive() {
    return isActive;
  }

   /**
   * The date and time when the user last logged in, or null if the user never logged in.
   * @return lastLoginTime
  **/
  public OffsetDateTime getLastLoginTime() {
    return lastLoginTime;
  }

   /**
   * The date and time when the user was created.
   * @return creationTime
  **/
  public OffsetDateTime getCreationTime() {
    return creationTime;
  }

   /**
   * The source which authenticated this user.
   * @return authenticationSource
  **/
  public String getAuthenticationSource() {
    return authenticationSource;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookSimpleUserDto webhookSimpleUserDto = (WebhookSimpleUserDto) o;
    return Objects.equals(this.id, webhookSimpleUserDto.id) &&
        Objects.equals(this.key, webhookSimpleUserDto.key) &&
        Objects.equals(this.userName, webhookSimpleUserDto.userName) &&
        Objects.equals(this.domain, webhookSimpleUserDto.domain) &&
        Objects.equals(this.fullName, webhookSimpleUserDto.fullName) &&
        Objects.equals(this.emailAddress, webhookSimpleUserDto.emailAddress) &&
        Objects.equals(this.type, webhookSimpleUserDto.type) &&
        Objects.equals(this.isActive, webhookSimpleUserDto.isActive) &&
        Objects.equals(this.lastLoginTime, webhookSimpleUserDto.lastLoginTime) &&
        Objects.equals(this.creationTime, webhookSimpleUserDto.creationTime) &&
        Objects.equals(this.authenticationSource, webhookSimpleUserDto.authenticationSource);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, key, userName, domain, fullName, emailAddress, type, isActive, lastLoginTime, creationTime, authenticationSource);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookSimpleUserDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    lastLoginTime: ").append(toIndentedString(lastLoginTime)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    authenticationSource: ").append(toIndentedString(authenticationSource)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
