/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.uipath.orchestrator.WrappedEnvironmentDto;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
/**
 * WrappedRobotDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class WrappedRobotDto {
  @JsonProperty("Id")
  private Long id = null;

  @JsonProperty("Key")
  private UUID key = null;

  @JsonProperty("Name")
  private String name = null;

  @JsonProperty("MachineId")
  private Long machineId = null;

  @JsonProperty("MachineKey")
  private UUID machineKey = null;

  @JsonProperty("MachineName")
  private String machineName = null;

  @JsonProperty("Description")
  private String description = null;

  @JsonProperty("UserName")
  private String userName = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    NONPRODUCTION("NonProduction"),
    ATTENDED("Attended"),
    UNATTENDED("Unattended"),
    DEVELOPMENT("Development"),
    STUDIO("Studio"),
    RPADEVELOPER("RpaDeveloper"),
    STUDIOX("StudioX"),
    CITIZENDEVELOPER("CitizenDeveloper"),
    HEADLESS("Headless"),
    STUDIOPRO("StudioPro"),
    RPADEVELOPERPRO("RpaDeveloperPro"),
    TESTAUTOMATION("TestAutomation"),
    AUTOMATIONCLOUD("AutomationCloud"),
    SERVERLESS("Serverless"),
    AUTOMATIONKIT("AutomationKit"),
    SERVERLESSTESTAUTOMATION("ServerlessTestAutomation"),
    AUTOMATIONCLOUDTESTAUTOMATION("AutomationCloudTestAutomation"),
    ATTENDEDSTUDIOWEB("AttendedStudioWeb");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("Type")
  private TypeEnum type = null;

  /**
   * Gets or Sets hostingType
   */
  public enum HostingTypeEnum {
    STANDARD("Standard"),
    FLOATING("Floating");

    private String value;

    HostingTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static HostingTypeEnum fromValue(String input) {
      for (HostingTypeEnum b : HostingTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("HostingType")
  private HostingTypeEnum hostingType = null;

  @JsonProperty("Environments")
  private List<WrappedEnvironmentDto> environments = null;

  @JsonProperty("ExecutionSettings")
  private Map<String, Object> executionSettings = null;

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

   /**
   * Get key
   * @return key
  **/
  public UUID getKey() {
    return key;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

   /**
   * Get machineId
   * @return machineId
  **/
  public Long getMachineId() {
    return machineId;
  }

   /**
   * Get machineKey
   * @return machineKey
  **/
  public UUID getMachineKey() {
    return machineKey;
  }

   /**
   * Get machineName
   * @return machineName
  **/
  public String getMachineName() {
    return machineName;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

   /**
   * Get userName
   * @return userName
  **/
  public String getUserName() {
    return userName;
  }

   /**
   * Get type
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

   /**
   * Get hostingType
   * @return hostingType
  **/
  public HostingTypeEnum getHostingType() {
    return hostingType;
  }

   /**
   * Get environments
   * @return environments
  **/
  public List<WrappedEnvironmentDto> getEnvironments() {
    return environments;
  }

   /**
   * Get executionSettings
   * @return executionSettings
  **/
  public Map<String, Object> getExecutionSettings() {
    return executionSettings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WrappedRobotDto wrappedRobotDto = (WrappedRobotDto) o;
    return Objects.equals(this.id, wrappedRobotDto.id) &&
        Objects.equals(this.key, wrappedRobotDto.key) &&
        Objects.equals(this.name, wrappedRobotDto.name) &&
        Objects.equals(this.machineId, wrappedRobotDto.machineId) &&
        Objects.equals(this.machineKey, wrappedRobotDto.machineKey) &&
        Objects.equals(this.machineName, wrappedRobotDto.machineName) &&
        Objects.equals(this.description, wrappedRobotDto.description) &&
        Objects.equals(this.userName, wrappedRobotDto.userName) &&
        Objects.equals(this.type, wrappedRobotDto.type) &&
        Objects.equals(this.hostingType, wrappedRobotDto.hostingType) &&
        Objects.equals(this.environments, wrappedRobotDto.environments) &&
        Objects.equals(this.executionSettings, wrappedRobotDto.executionSettings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, key, name, machineId, machineKey, machineName, description, userName, type, hostingType, environments, executionSettings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WrappedRobotDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    machineId: ").append(toIndentedString(machineId)).append("\n");
    sb.append("    machineKey: ").append(toIndentedString(machineKey)).append("\n");
    sb.append("    machineName: ").append(toIndentedString(machineName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    hostingType: ").append(toIndentedString(hostingType)).append("\n");
    sb.append("    environments: ").append(toIndentedString(environments)).append("\n");
    sb.append("    executionSettings: ").append(toIndentedString(executionSettings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
