/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * This class defines DTO for Tasks Collection for webhook event Task.Forwarded
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class WrappedTaskForwardedDto {
  @JsonProperty("Title")
  private String title = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    FORMTASK("FormTask"),
    EXTERNALTASK("ExternalTask"),
    DOCUMENTVALIDATIONTASK("DocumentValidationTask"),
    DOCUMENTCLASSIFICATIONTASK("DocumentClassificationTask"),
    DATALABELINGTASK("DataLabelingTask"),
    APPTASK("AppTask");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("Type")
  private TypeEnum type = null;

  /**
   * Gets or Sets priority
   */
  public enum PriorityEnum {
    LOW("Low"),
    MEDIUM("Medium"),
    HIGH("High"),
    CRITICAL("Critical");

    private String value;

    PriorityEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PriorityEnum fromValue(String input) {
      for (PriorityEnum b : PriorityEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("Priority")
  private PriorityEnum priority = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    UNASSIGNED("Unassigned"),
    PENDING("Pending"),
    COMPLETED("Completed");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("Status")
  private StatusEnum status = null;

  @JsonProperty("CreationTime")
  private OffsetDateTime creationTime = null;

  @JsonProperty("TaskCatalogName")
  private String taskCatalogName = null;

  @JsonProperty("Id")
  private Long id = null;

  @JsonProperty("OrganizationUnitId")
  private Long organizationUnitId = null;

  @JsonProperty("AssignedToUserId")
  private Long assignedToUserId = null;

  @JsonProperty("ForwardedByUserId")
  private Long forwardedByUserId = null;

   /**
   * Get title
   * @return title
  **/
  public String getTitle() {
    return title;
  }

   /**
   * Get type
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

   /**
   * Get priority
   * @return priority
  **/
  public PriorityEnum getPriority() {
    return priority;
  }

   /**
   * Get status
   * @return status
  **/
  public StatusEnum getStatus() {
    return status;
  }

   /**
   * Get creationTime
   * @return creationTime
  **/
  public OffsetDateTime getCreationTime() {
    return creationTime;
  }

   /**
   * Get taskCatalogName
   * @return taskCatalogName
  **/
  public String getTaskCatalogName() {
    return taskCatalogName;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

   /**
   * Get organizationUnitId
   * @return organizationUnitId
  **/
  public Long getOrganizationUnitId() {
    return organizationUnitId;
  }

   /**
   * Get assignedToUserId
   * @return assignedToUserId
  **/
  public Long getAssignedToUserId() {
    return assignedToUserId;
  }

   /**
   * Id of the user who forwarded this task
   * @return forwardedByUserId
  **/
  public Long getForwardedByUserId() {
    return forwardedByUserId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WrappedTaskForwardedDto wrappedTaskForwardedDto = (WrappedTaskForwardedDto) o;
    return Objects.equals(this.title, wrappedTaskForwardedDto.title) &&
        Objects.equals(this.type, wrappedTaskForwardedDto.type) &&
        Objects.equals(this.priority, wrappedTaskForwardedDto.priority) &&
        Objects.equals(this.status, wrappedTaskForwardedDto.status) &&
        Objects.equals(this.creationTime, wrappedTaskForwardedDto.creationTime) &&
        Objects.equals(this.taskCatalogName, wrappedTaskForwardedDto.taskCatalogName) &&
        Objects.equals(this.id, wrappedTaskForwardedDto.id) &&
        Objects.equals(this.organizationUnitId, wrappedTaskForwardedDto.organizationUnitId) &&
        Objects.equals(this.assignedToUserId, wrappedTaskForwardedDto.assignedToUserId) &&
        Objects.equals(this.forwardedByUserId, wrappedTaskForwardedDto.forwardedByUserId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, type, priority, status, creationTime, taskCatalogName, id, organizationUnitId, assignedToUserId, forwardedByUserId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WrappedTaskForwardedDto {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    taskCatalogName: ").append(toIndentedString(taskCatalogName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    organizationUnitId: ").append(toIndentedString(organizationUnitId)).append("\n");
    sb.append("    assignedToUserId: ").append(toIndentedString(assignedToUserId)).append("\n");
    sb.append("    forwardedByUserId: ").append(toIndentedString(forwardedByUserId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
