/*
 * UiPath.WebApi 18.0
 * Orchestrator API
 *
 * OpenAPI spec version: 18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uipath.orchestrator;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.uipath.orchestrator.WrappedReleaseDto;
import com.uipath.orchestrator.WrappedRobotDto;

import java.time.OffsetDateTime;
import java.util.UUID;
/**
 * WrappedJobDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-24T09:07:18.266604900+07:00[Asia/Bangkok]")
public class WrappedJobDto {
  @JsonProperty("Id")
  private Long id = null;

  @JsonProperty("Key")
  private UUID key = null;

  @JsonProperty("CreationTime")
  private OffsetDateTime creationTime = null;

  @JsonProperty("StartTime")
  private OffsetDateTime startTime = null;

  @JsonProperty("EndTime")
  private OffsetDateTime endTime = null;

  /**
   * The state in which the job is.
   */
  public enum StateEnum {
    PENDING("Pending"),
    RUNNING("Running"),
    STOPPING("Stopping"),
    TERMINATING("Terminating"),
    FAULTED("Faulted"),
    SUCCESSFUL("Successful"),
    STOPPED("Stopped"),
    SUSPENDED("Suspended"),
    RESUMED("Resumed");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StateEnum fromValue(String input) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("State")
  private StateEnum state = null;

  @JsonProperty("Source")
  private String source = null;

  /**
   * The Source type of the job.
   */
  public enum SourceTypeEnum {
    MANUAL("Manual"),
    SCHEDULE("Schedule"),
    AGENT("Agent"),
    QUEUE("Queue"),
    STUDIOWEB("StudioWeb"),
    INTEGRATIONTRIGGER("IntegrationTrigger"),
    STUDIODESKTOP("StudioDesktop"),
    AUTOMATIONOPSPIPELINES("AutomationOpsPipelines"),
    APPS("Apps"),
    SAP("SAP"),
    HTTPTRIGGER("HttpTrigger"),
    HTTPTRIGGERCALLBACK("HttpTriggerCallback"),
    ROBOTAPI("RobotAPI"),
    COMMANDLINE("CommandLine"),
    ROBOTNETAPI("RobotNetAPI");

    private String value;

    SourceTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SourceTypeEnum fromValue(String input) {
      for (SourceTypeEnum b : SourceTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("SourceType")
  private SourceTypeEnum sourceType = null;

  @JsonProperty("BatchExecutionKey")
  private UUID batchExecutionKey = null;

  @JsonProperty("Info")
  private String info = null;

  @JsonProperty("StartingScheduleId")
  private Long startingScheduleId = null;

  @JsonProperty("ReleaseName")
  private String releaseName = null;

  /**
   * The type of the job, Attended if started via the robot, Unattended otherwise
   */
  public enum TypeEnum {
    UNATTENDED("Unattended"),
    ATTENDED("Attended"),
    SERVERLESSGENERIC("ServerlessGeneric");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("Type")
  private TypeEnum type = null;

  @JsonProperty("HostMachineName")
  private String hostMachineName = null;

  @JsonProperty("Robot")
  private WrappedRobotDto robot = null;

  @JsonProperty("Release")
  private WrappedReleaseDto release = null;

  @JsonProperty("InputArguments")
  private Object inputArguments = null;

  @JsonProperty("OutputArguments")
  private Object outputArguments = null;

  /**
   * The type of license used to run the job
   */
  public enum RuntimeTypeEnum {
    NONPRODUCTION("NonProduction"),
    ATTENDED("Attended"),
    UNATTENDED("Unattended"),
    DEVELOPMENT("Development"),
    STUDIO("Studio"),
    RPADEVELOPER("RpaDeveloper"),
    STUDIOX("StudioX"),
    CITIZENDEVELOPER("CitizenDeveloper"),
    HEADLESS("Headless"),
    STUDIOPRO("StudioPro"),
    RPADEVELOPERPRO("RpaDeveloperPro"),
    TESTAUTOMATION("TestAutomation"),
    AUTOMATIONCLOUD("AutomationCloud"),
    SERVERLESS("Serverless"),
    AUTOMATIONKIT("AutomationKit"),
    SERVERLESSTESTAUTOMATION("ServerlessTestAutomation"),
    AUTOMATIONCLOUDTESTAUTOMATION("AutomationCloudTestAutomation"),
    ATTENDEDSTUDIOWEB("AttendedStudioWeb");

    private String value;

    RuntimeTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static RuntimeTypeEnum fromValue(String input) {
      for (RuntimeTypeEnum b : RuntimeTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("RuntimeType")
  private RuntimeTypeEnum runtimeType = null;

  /**
   * The type of process
   */
  public enum ProcessTypeEnum {
    UNDEFINED("Undefined"),
    PROCESS("Process"),
    TESTAUTOMATIONPROCESS("TestAutomationProcess");

    private String value;

    ProcessTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ProcessTypeEnum fromValue(String input) {
      for (ProcessTypeEnum b : ProcessTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("ProcessType")
  private ProcessTypeEnum processType = null;

  @JsonProperty("SpecificPriorityValue")
  private Integer specificPriorityValue = null;

  @JsonProperty("ProjectKey")
  private String projectKey = null;

  /**
   * The serverless job type for this job
   */
  public enum ServerlessJobTypeEnum {
    ROBOTJOB("RobotJob"),
    STUDIOWEBDESIGNER("StudioWebDesigner"),
    PUBLISHSTUDIOPROJECT("PublishStudioProject");

    private String value;

    ServerlessJobTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ServerlessJobTypeEnum fromValue(String input) {
      for (ServerlessJobTypeEnum b : ServerlessJobTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("ServerlessJobType")
  private ServerlessJobTypeEnum serverlessJobType = null;

  @JsonProperty("ParentOperationId")
  private String parentOperationId = null;

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

   /**
   * The unique job identifier.
   * @return key
  **/
  public UUID getKey() {
    return key;
  }

   /**
   * The Creation time of the job
   * @return creationTime
  **/
  public OffsetDateTime getCreationTime() {
    return creationTime;
  }

   /**
   * The date and time when the job execution started or null if the job hasn&#x27;t started yet.
   * @return startTime
  **/
  public OffsetDateTime getStartTime() {
    return startTime;
  }

   /**
   * The date and time when the job execution ended or null if the job hasn&#x27;t ended yet.
   * @return endTime
  **/
  public OffsetDateTime getEndTime() {
    return endTime;
  }

   /**
   * The state in which the job is.
   * @return state
  **/
  public StateEnum getState() {
    return state;
  }

   /**
   * The Source name of the job.
   * @return source
  **/
  public String getSource() {
    return source;
  }

   /**
   * The Source type of the job.
   * @return sourceType
  **/
  public SourceTypeEnum getSourceType() {
    return sourceType;
  }

   /**
   * The unique identifier grouping multiple jobs. It is usually generated when the job is created by a schedule.
   * @return batchExecutionKey
  **/
  public UUID getBatchExecutionKey() {
    return batchExecutionKey;
  }

   /**
   * Additional information about the current job.
   * @return info
  **/
  public String getInfo() {
    return info;
  }

   /**
   * The Id of the schedule that started the job, or null if the job was started by the user.
   * @return startingScheduleId
  **/
  public Long getStartingScheduleId() {
    return startingScheduleId;
  }

   /**
   * The name of the release associated with the current name.
   * @return releaseName
  **/
  public String getReleaseName() {
    return releaseName;
  }

   /**
   * The type of the job, Attended if started via the robot, Unattended otherwise
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

   /**
   * The name of the machine where the Robot run the job.
   * @return hostMachineName
  **/
  public String getHostMachineName() {
    return hostMachineName;
  }

  public WrappedJobDto robot(WrappedRobotDto robot) {
    this.robot = robot;
    return this;
  }

   /**
   * Get robot
   * @return robot
  **/
  public WrappedRobotDto getRobot() {
    return robot;
  }

  public void setRobot(WrappedRobotDto robot) {
    this.robot = robot;
  }

  public WrappedJobDto release(WrappedReleaseDto release) {
    this.release = release;
    return this;
  }

   /**
   * Get release
   * @return release
  **/
  public WrappedReleaseDto getRelease() {
    return release;
  }

  public void setRelease(WrappedReleaseDto release) {
    this.release = release;
  }

   /**
   * Input parameters in JSON format to be passed to job execution
   * @return inputArguments
  **/
  public Object getInputArguments() {
    return inputArguments;
  }

   /**
   * Output parameters in JSON format resulted from job execution
   * @return outputArguments
  **/
  public Object getOutputArguments() {
    return outputArguments;
  }

   /**
   * The type of license used to run the job
   * @return runtimeType
  **/
  public RuntimeTypeEnum getRuntimeType() {
    return runtimeType;
  }

   /**
   * The type of process
   * @return processType
  **/
  public ProcessTypeEnum getProcessType() {
    return processType;
  }

   /**
   * The priority for a job
   * @return specificPriorityValue
  **/
  public Integer getSpecificPriorityValue() {
    return specificPriorityValue;
  }

   /**
   * The project key which the job is part of
   * @return projectKey
  **/
  public String getProjectKey() {
    return projectKey;
  }

   /**
   * The serverless job type for this job
   * @return serverlessJobType
  **/
  public ServerlessJobTypeEnum getServerlessJobType() {
    return serverlessJobType;
  }

   /**
   * The operation id which created the job
   * @return parentOperationId
  **/
  public String getParentOperationId() {
    return parentOperationId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WrappedJobDto wrappedJobDto = (WrappedJobDto) o;
    return Objects.equals(this.id, wrappedJobDto.id) &&
        Objects.equals(this.key, wrappedJobDto.key) &&
        Objects.equals(this.creationTime, wrappedJobDto.creationTime) &&
        Objects.equals(this.startTime, wrappedJobDto.startTime) &&
        Objects.equals(this.endTime, wrappedJobDto.endTime) &&
        Objects.equals(this.state, wrappedJobDto.state) &&
        Objects.equals(this.source, wrappedJobDto.source) &&
        Objects.equals(this.sourceType, wrappedJobDto.sourceType) &&
        Objects.equals(this.batchExecutionKey, wrappedJobDto.batchExecutionKey) &&
        Objects.equals(this.info, wrappedJobDto.info) &&
        Objects.equals(this.startingScheduleId, wrappedJobDto.startingScheduleId) &&
        Objects.equals(this.releaseName, wrappedJobDto.releaseName) &&
        Objects.equals(this.type, wrappedJobDto.type) &&
        Objects.equals(this.hostMachineName, wrappedJobDto.hostMachineName) &&
        Objects.equals(this.robot, wrappedJobDto.robot) &&
        Objects.equals(this.release, wrappedJobDto.release) &&
        Objects.equals(this.inputArguments, wrappedJobDto.inputArguments) &&
        Objects.equals(this.outputArguments, wrappedJobDto.outputArguments) &&
        Objects.equals(this.runtimeType, wrappedJobDto.runtimeType) &&
        Objects.equals(this.processType, wrappedJobDto.processType) &&
        Objects.equals(this.specificPriorityValue, wrappedJobDto.specificPriorityValue) &&
        Objects.equals(this.projectKey, wrappedJobDto.projectKey) &&
        Objects.equals(this.serverlessJobType, wrappedJobDto.serverlessJobType) &&
        Objects.equals(this.parentOperationId, wrappedJobDto.parentOperationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, key, creationTime, startTime, endTime, state, source, sourceType, batchExecutionKey, info, startingScheduleId, releaseName, type, hostMachineName, robot, release, inputArguments, outputArguments, runtimeType, processType, specificPriorityValue, projectKey, serverlessJobType, parentOperationId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WrappedJobDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    sourceType: ").append(toIndentedString(sourceType)).append("\n");
    sb.append("    batchExecutionKey: ").append(toIndentedString(batchExecutionKey)).append("\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    sb.append("    startingScheduleId: ").append(toIndentedString(startingScheduleId)).append("\n");
    sb.append("    releaseName: ").append(toIndentedString(releaseName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    hostMachineName: ").append(toIndentedString(hostMachineName)).append("\n");
    sb.append("    robot: ").append(toIndentedString(robot)).append("\n");
    sb.append("    release: ").append(toIndentedString(release)).append("\n");
    sb.append("    inputArguments: ").append(toIndentedString(inputArguments)).append("\n");
    sb.append("    outputArguments: ").append(toIndentedString(outputArguments)).append("\n");
    sb.append("    runtimeType: ").append(toIndentedString(runtimeType)).append("\n");
    sb.append("    processType: ").append(toIndentedString(processType)).append("\n");
    sb.append("    specificPriorityValue: ").append(toIndentedString(specificPriorityValue)).append("\n");
    sb.append("    projectKey: ").append(toIndentedString(projectKey)).append("\n");
    sb.append("    serverlessJobType: ").append(toIndentedString(serverlessJobType)).append("\n");
    sb.append("    parentOperationId: ").append(toIndentedString(parentOperationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
